openapi: 3.0.0
info:
  title: Nuapay TPP API Specification
  description: >-
    Swagger Spec for the Nuapay TPP OpenBanking/PSD2. Provides PISP and Banks
    Endpoints
  version: 1.16.1
  contact:
    name: Nuapay
    email: api.support@nuapay.com
  license:
    name: Nuapay
    url: https://sentenial.com
  x-logo:
    backgroundColor: '#FFFFFF'
    url: https://www.nuapay.com/wp-content/uploads/2018/04/nuapay.svg
servers:
  - url: https://api.nuapay.com/tpp
tags:
  - description: |-
      Payment initiation endpoints allow a merchant to,
      - Initiate payment requests in Open Banking
      - Retrieve the status of a previously initiated payment request
    name: PISP Service
  - description: |-
      Bank endpoints allow a merchant to,
      - Retrieve a list of banks that support the Open Banking scheme
      - View details of a specific bank that supports the Open Banking scheme
    name: Bank Service
paths:
  /bankfamilies:
    get:
      tags:
        - Bank Service
      summary: View Bank Families
      operationId: BankService_viewBankFamilies
      security:
        - MerchantOAuth2:
            - openbanking_aisp
            - openbanking_pisp
        - MerchantApiKey: []
        - PartnerOAuth2:
            - openbanking_aisp
            - openbanking_pisp
        - PartnerApiKey: []
      description: Get list of Bank Families
  /bankfamilies/{bankfamilyId}:
    get:
      tags:
        - Bank Service
      summary: View Bank Family
      operationId: BankService_getBankFamily
      security:
        - MerchantOAuth2:
            - openbanking_aisp
            - openbanking_pisp
        - MerchantApiKey: []
        - PartnerOAuth2:
            - openbanking_aisp
            - openbanking_pisp
        - PartnerApiKey: []
      description: View Bank Family Details
  /banks:
    get:
      tags:
        - Bank Service
      summary: Retrieve Banks
      operationId: BankService_getSupportedBanks
      security:
        - MerchantOAuth2:
            - openbanking_aisp
            - openbanking_pisp
        - MerchantApiKey: []
        - PartnerOAuth2:
            - openbanking_aisp
            - openbanking_pisp
        - PartnerApiKey: []
      description: Get Supported Banks On This TPP
  /payments:
    post:
      tags:
        - PISP Service
      summary: Create Payment
      operationId: PispService_makePayment
      security:
        - MerchantOAuth2:
            - openbanking_pisp
        - MerchantApiKey: []
      description: Create a payment request POST endpoint
    get:
      tags:
        - PISP Service
      summary: List payments
      operationId: PispService_listPayments
      security:
        - MerchantOAuth2:
            - openbanking_pisp
        - MerchantApiKey: []
        - PartnerOAuth2:
            - openbanking_pisp
        - PartnerApiKey: []
      description: GET payments list endpoint
  /payments/callback:
    post:
      tags:
        - PISP Service
      summary: Forward Payment Callback
      operationId: PispService_forwardPaymentCallback
      security:
        - MerchantOAuth2:
            - openbanking_callback
        - PartnerOAuth2:
            - openbanking_callback
      description: Forward Payment Callback POST endpoint
  /payments/{paymentId}:
    get:
      tags:
        - PISP Service
      summary: Retrieve Payment
      operationId: PispService_getPayment
      security:
        - MerchantOAuth2:
            - openbanking_pisp
        - MerchantApiKey: []
      description: GET Payment details endpoint
    patch:
      tags:
        - PISP Service
      summary: Retry Payment
      operationId: PispService_retryPaymentPatch
      security:
        - MerchantOAuth2:
            - openbanking_pisp
      description: Retry Payment
  /payments/{paymentId}/history:
    get:
      tags:
        - PISP Service
      summary: Retrieve Payment  History
      operationId: PispService_getPaymentHistory
      security:
        - MerchantOAuth2:
            - openbanking_pisp_read
        - MerchantApiKey: []
      description: Retrieve Payment History
  /payments/{paymentId}/refunds:
    post:
      tags:
        - PISP Service
      summary: Refund Payment
      operationId: PispService_refundPayment
      security:
        - MerchantOAuth2:
            - openbanking_refund
        - MerchantApiKey: []
      description: Refund a payment using POST
    get:
      tags:
        - PISP Service
      summary: List Payment Refunds
      operationId: PispService_getPaymentRefunds
      security:
        - MerchantOAuth2:
            - openbanking_refund_read
        - MerchantApiKey: []
      description: List refunds using GET
  /payments/{paymentId}/refunds/{refundId}:
    get:
      tags:
        - PISP Service
      summary: Retrieve Refund
      operationId: PispService_getRefund
      security:
        - MerchantOAuth2:
            - openbanking_refund_read
        - MerchantApiKey: []
      description: GET Refund details endpoint
components:
  securitySchemes:
    MerchantApiKey:
      type: http
      scheme: basic
    PartnerApiKey:
      type: http
      scheme: basic
    MerchantOAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: https://api.nuapay.com/oauth/token_key
          scopes:
            openbanking_pisp: Payment Initiation Service Provider access
            openbanking_pisp_read: Read Account and Payment Information  access
            openbanking_refund: Open Banking Refund access
            openbanking_refund_read: Read Open Banking Refunds access
            openbanking_callback: Open Banking callback forwarding access
    PartnerOAuth2:
      type: oauth2
      flows:
        password:
          tokenUrl: https://api.nuapay.com/oauth/token_key
          scopes:
            openbanking_aisp: Account Information Service Provider access
            openbanking_pisp: Payment Initiation Service Provider access
            openbanking_pisp_read: Read Account and Payment Information  access
            openbanking_callback: Open Banking callback forwarding access