openapi: 3.0.1
info:
  title: Payments API
  description: >

    The payments API allows you to initiate and manage payments and vendors from
    your Brex business accounts.
  version: '1.0'
  contact:
    name: Admin
    url: https://brex.com
    email: developer-access@brex.com
servers:
  - description: Production
    url: https://platform.brexapis.com
  - description: >-
      Staging (Note: This is not a sandbox. It will not work with customer
      tokens.)
    url: https://platform.staging.brexapps.com
tags:
  - description: Endpoints to manage vendors
    name: Vendors
  - description: >-
      Endpoints to initiate transfers and view transfer statuses. Note that for
      all transfer endpoints, the 'money' field is positive or unsigned for
      outgoing transfers (debits), and negative for incoming transfers
      (credits).
    name: Transfers
  - description: Endpoint to view connected linked accounts
    name: Linked Accounts
paths:
  /v1/incoming_transfers:
    post:
      tags:
        - Transfers
      summary: |

        Create incoming transfer
      operationId: Transfers_createIncomingTransfer
      security:
        - OAuth2:
            - incoming_transfers
      description: >

        This endpoint creates a new incoming transfer. You may use use any
        eligible bank account connection to fund (ACH Debit) 

        any active Brex business account.


        **Reminder**: You may not use the Brex API for any activity that
        requires a license or registration from any 

        governmental authority without Brex's prior review and approval. This
        includes but is not limited to any money services

        business or money transmission activity.


        Please review the <a
        href="https://www.brex.com/legal/developer-portal/">Brex Access
        Agreement</a> and contact us if 

        you have any questions.
  /v1/linked_accounts:
    get:
      tags:
        - Linked Accounts
      summary: |

        Lists linked accounts
      operationId: LinkedAccounts_list
      security:
        - OAuth2:
            - linked_accounts.readonly
      description: >

        This endpoint lists all bank connections that are eligible to make ACH
        transfers to Brex business account
  /v1/transfers:
    get:
      tags:
        - Transfers
      summary: |

        Lists transfers 
      operationId: Transfers_list
      security:
        - OAuth2:
            - transfers.readonly
            - incoming_transfers
      description: >

        This endpoint lists existing transfers for an account.


        Currently, the API can only return transfers for the following payment
        rails:

        - ACH

        - DOMESTIC_WIRE

        - CHEQUE

        - INTERNATIONAL_WIRE
    post:
      tags:
        - Transfers
      summary: |

        Create transfer
      operationId: Transfers_createTransfer
      security:
        - OAuth2:
            - transfers
      description: >

        This endpoint creates a new transfer.


        Currently, the API can only create transfers for the following payment
        rails:

        - ACH

        - DOMESTIC_WIRE

        - CHEQUE

        - INTERNATIONAL_WIRES (For vendors already created through dashboard.
        Rate limited to 100/day - Please reach out to developer-support@brex.com
        if you need to do more)


        **Transaction Descriptions**

        * For outgoing check payments, a successful transfer will return a
        response containing a description value with a format of `Check #<check
        number> to <recipient_name> - <external_memo>`.

        * For book transfers (from one Brex Business account to another), the
        recipient value will have a format of `<customer_account.dba_name> -
        <external_memo>` and the sender will have a format of `<target customer
        account's dba name> - <external_memo>`.

        * For other payment rails, the format will be `<counterparty_name> -
        <external_memo>`, where Counterparty name is
        `payment_instrument.beneficiary_name` or `contact.name`

        For vendors created from the Payments API, the `counterparty_name` will
        be the `company_name`
        [field](https://developer.brex.com/openapi/payments_api/).


        **Reminder**: You may not use the Brex API for any activity that
        requires a license or registration from any 

        governmental authority without Brex's prior review and approval. This
        includes but is not limited to any money services

        business or money transmission activity.


        Please review the <a
        href="https://www.brex.com/legal/developer-portal/">Brex Access
        Agreement</a> and contact us if 

        you have any questions.
  /v1/transfers/{id}:
    get:
      tags:
        - Transfers
      summary: |

        Get transfer
      operationId: Transfers_getById
      security:
        - OAuth2:
            - transfers.readonly
            - incoming_transfers
      description: >

        This endpoint gets a transfer by ID.


        Currently, the API can only return transfers for the following payment
        rails:

        - ACH

        - DOMESTIC_WIRE

        - CHEQUE

        - INTERNATIONAL_WIRE
  /v1/vendors:
    get:
      tags:
        - Vendors
      summary: |

        Lists vendors 
      operationId: Vendors_list
      security:
        - OAuth2:
            - vendors.readonly
      description: |

        This endpoint lists all existing vendors for an account.
        Takes an optional parameter to match by vendor name.
    post:
      tags:
        - Vendors
      summary: |

        Create vendor
      operationId: Vendors_createNewVendor
      security:
        - OAuth2:
            - vendors
      description: |

        This endpoint creates a new vendor.
  /v1/vendors/{id}:
    get:
      tags:
        - Vendors
      summary: |

        Get vendor
      operationId: Vendors_getById
      security:
        - OAuth2:
            - vendors.readonly
      description: |

        This endpoint gets a vendor by ID.
    put:
      tags:
        - Vendors
      summary: Update vendor
      operationId: Vendors_updateById
      security:
        - OAuth2:
            - vendors
      description: |2

            Updates an existing vendor by ID.
    delete:
      tags:
        - Vendors
      summary: |

        Delete vendor.
      operationId: Vendors_deleteVendorById
      security:
        - OAuth2:
            - vendors
      description: |

        This endpoint deletes a vendor by ID.
components:
  securitySchemes:
    OAuth2:
      description: OAuth2 security scheme
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
          scopes:
            openid: openid
            offline_access: offline access
            vendors: View and manage vendor data
            vendors.readonly: View vendor data
            transfers: View and manage transfer data
            transfers.readonly: View transfer data
            incoming_transfers: View and manage incoming transfer data
            linked_accounts.readonly: View linked accounts
security:
  - OAuth2: []
x-explorer-enabled: false
