openapi: 3.0.1
info:
  title: Budgets API
  description: |

    The budgets API lets you manage your Brex budgets.
  version: '1.0'
  contact:
    name: Admin
    url: https://brex.com
    email: developer-access@brex.com
servers:
  - description: Production
    url: https://platform.brexapis.com
  - description: >-
      Staging (Note: This is not a sandbox. It will not work with customer
      tokens.)
    url: https://platform.staging.brexapps.com
tags:
  - description: Endpoints for budgets data.
    name: Budgets
  - description: Endpoints for budgets programs data.
    name: Budget Programs
paths:
  /v1/budget_programs:
    get:
      tags:
        - Budget Programs
      summary: |

        List Budget Programs
      operationId: BudgetPrograms_list
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
      description: |

        Lists Budget Programs belonging to this account
    post:
      tags:
        - Budget Programs
      summary: |

        Create Budget Program
      operationId: BudgetPrograms_create
      security:
        - OAuth2:
            - budgets
      description: >

        Creates a Budget Program.

        If your account does not have access to budget program features, a 403
        response status will be returned.

        If this is the case and you want to gain access to this endpoint, please
        contact Brex support.
  /v1/budget_programs/{id}:
    get:
      tags:
        - Budget Programs
      summary: |

        Get Budget Program
      operationId: BudgetPrograms_getById
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
      description: |

        Retrieves a Budget Program by ID
    put:
      tags:
        - Budget Programs
      summary: |

        Update Budget Program
      operationId: BudgetPrograms_updateProgramById
      security:
        - OAuth2:
            - budgets
      description: >

        Updates a Budget Program.

        This endpoint requires budget management. If your account does not have
        access to budget management features, a 403 response status will be
        returned. 

        If this is the case and you want to gain access to this endpoint, please
        contact Brex support.
    delete:
      tags:
        - Budget Programs
      summary: |

        Delete Budget Program
      operationId: BudgetPrograms_removeProgramById
      security:
        - OAuth2:
            - budgets
      description: >

        Delete a Budget Program by ID.

        This endpoint requires budget management. If your account does not have
        access to budget management features, a 403 response status will be
        returned. 

        If this is the case and you want to gain access to this endpoint, please
        contact Brex support.
  /v1/budgets:
    get:
      tags:
        - Budgets
      summary: |

        List Budgets
      operationId: Budgets_list
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
      description: |

        Lists Budgets belonging to this account
    post:
      tags:
        - Budgets
      summary: |

        Create Budget
      operationId: Budgets_create
      security:
        - OAuth2:
            - budgets
      description: >

        Creates a Budget.

        This endpoint requires budget management. If your account does not have
        access to budget management features, a 403 response status will be
        returned. 

        If this is the case and you want to gain access to this endpoint, please
        contact Brex support.
  /v1/budgets/{id}:
    get:
      tags:
        - Budgets
      summary: |

        Get Budget
      operationId: Budgets_getById
      security:
        - OAuth2:
            - budgets.readonly
            - budgets
      description: |

        Retrieves a Budget by ID
    put:
      tags:
        - Budgets
      summary: |

        Update Budget
      operationId: Budgets_updateBudget
      security:
        - OAuth2:
            - budgets
      description: >

        Updates a Budget.

        This endpoint requires budget management. If your account does not have
        access to budget management features, a 403 response status will be
        returned. 

        If this is the case and you want to gain access to this endpoint, please
        contact Brex support.
  /v1/budgets/{id}/archive:
    post:
      tags:
        - Budgets
      summary: |

        Archive a budget
      operationId: Budgets_archiveBudgetById
      security:
        - OAuth2:
            - budgets
      description: >

        Archives a budget, making it unusable for future expenses and removing
        it from the UI
components:
  securitySchemes:
    OAuth2:
      description: OAuth2 security scheme
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
          scopes:
            openid: openid
            offline_access: offline access
            budgets: View and manage budgets data
            budgets.readonly: View budgets data
security:
  - OAuth2: []
x-explorer-enabled: false
