openapi: 3.0.1
info:
  title: Team API
  description: |

    The team API lets you manage users, departments, locations, and cards.
  version: '1.0'
  contact:
    name: Admin
    url: https://brex.com
    email: developer-access@brex.com
servers:
  - description: Production
    url: https://platform.brexapis.com
  - description: >-
      Staging (Note: This is not a sandbox. It will not work with customer
      tokens.)
    url: https://platform.staging.brexapps.com
tags:
  - description: Endpoints for card management.
    name: Cards
  - description: Endpoints for user management.
    name: Users
  - description: Endpoints for location management.
    name: Locations
  - description: Endpoints for department management.
    name: Departments
  - description: Endpoints for title management.
    name: Titles
  - name: Companies
paths:
  /v2/cards:
    get:
      tags:
        - Cards
      summary: |

        List cards
      operationId: Cards_listByUserId
      security:
        - OAuth2:
            - cards.readonly
            - cards
      description: |

        Lists all cards by a `user_id`.
        Only cards with `limit_type = CARD` have `spend_controls`
    post:
      tags:
        - Cards
      summary: |

        Create card
      operationId: Cards_createNewCard
      security:
        - OAuth2:
            - cards
      description: >

        Creates a new card.

        The `spend_controls` field is required when `limit_type` = `CARD`.

        The `mailing_address` field is required for physical cards and is the
        shipping address used to send the card; it is not the same as the
        billing and mailing address used for online purchases.

        The first 2 lines of this address must be under 60 characters long. Each
        user can only have up to 10 active physical cards.

        For Empower accounts, this endpoint requires budget management. If your
        account does not have access to budget management features, a 403
        response status will be returned. 

        If this is the case and you want to gain access to this endpoint, please
        contact Brex support.
  /v2/cards/{id}:
    get:
      tags:
        - Cards
      summary: |

        Get card
      operationId: Cards_getById
      security:
        - OAuth2:
            - cards
            - cards.readonly
      description: >

        Retrieves a card by ID. Only cards with `limit_type = CARD` have
        `spend_controls`
    put:
      tags:
        - Cards
      summary: |

        Update card
      operationId: Cards_updateCard
      security:
        - OAuth2:
            - cards
      description: |

        Update an existing vendor card
  /v2/cards/{id}/lock:
    post:
      tags:
        - Cards
      summary: |

        Lock card
      operationId: Cards_lockCard
      security:
        - OAuth2:
            - cards
      description: >

        Locks an existing, unlocked card. And the card owner will receive a
        notification about it.
  /v2/cards/{id}/pan:
    get:
      servers:
        - description: Production
          url: https://secure-platform.brexapis.com
        - description: >-
            Staging (Note: This is not a sandbox. It will not work with customer
            tokens.)
          url: https://secure-platform.staging.brexapps.com
      tags:
        - Cards
      summary: |

        Get card number
      operationId: Cards_getCardDetails
      security:
        - OAuth2:
            - cards.pan
      description: |

        Retrieves card number, CVV, and expiration date of a card by ID.
  /v2/cards/{id}/secure_email:
    post:
      tags:
        - Cards
      summary: |

        Create secure email to send card number 
      operationId: Cards_createSecureEmail
      security:
        - OAuth2:
            - cards.pan
      description: >

        Creates a secure email to send card number, CVV, and expiration date of
        a card by ID to the specified email.


        This endpoint is currently gated. If you would like to request access,
        please reach out to

        developer-access@brex.com
  /v2/cards/{id}/terminate:
    post:
      tags:
        - Cards
      summary: |

        Terminate card
      operationId: Cards_terminateExistingCard
      security:
        - OAuth2:
            - cards
      description: >

        Terminates an existing card. The card owner will receive a notification
        about it.
  /v2/cards/{id}/unlock:
    post:
      tags:
        - Cards
      summary: |

        Unlock card
      operationId: Cards_unlockExistingCard
      security:
        - OAuth2:
            - cards
      description: |

        Unlocks an existing card.
  /v2/company:
    get:
      tags:
        - Companies
      summary: |

        Get company
      operationId: Companies_getInfo
      security:
        - OAuth2:
            - companies.readonly
      description: >

        This endpoint returns the company associated with the OAuth2 access
        token.
  /v2/departments:
    get:
      tags:
        - Departments
      summary: |

        List departments
      operationId: Departments_listAll
      security:
        - OAuth2:
            - departments
            - departments.readonly
      description: |

        This endpoint lists all departments.
    post:
      tags:
        - Departments
      summary: |

        Create department
      operationId: Departments_addNewDepartment
      security:
        - OAuth2:
            - departments
      description: |

        This endpoint creates a new department
  /v2/departments/{id}:
    get:
      tags:
        - Departments
      summary: |

        Get department
      operationId: Departments_getById
      security:
        - OAuth2:
            - departments
            - departments.readonly
      description: |

        This endpoint gets a department by ID.
  /v2/locations:
    get:
      tags:
        - Locations
      summary: |

        List locations
      operationId: Locations_getAllLocations
      security:
        - OAuth2:
            - locations
            - locations.readonly
      description: |

        This endpoint lists all locations.
    post:
      tags:
        - Locations
      summary: |

        Create location
      operationId: Locations_addNewLocation
      security:
        - OAuth2:
            - locations
      description: |

        This endpoint creates a new location.
  /v2/locations/{id}:
    get:
      tags:
        - Locations
      summary: |

        Get location
      operationId: Locations_getLocationById
      security:
        - OAuth2:
            - locations
            - locations.readonly
      description: |

        This endpoint gets a location by ID.
  /v2/titles:
    get:
      tags:
        - Titles
      summary: |

        List titles
      operationId: Titles_getAll
      security:
        - OAuth2:
            - titles
            - titles.readonly
      description: |

        This endpoint lists all titles.
    post:
      tags:
        - Titles
      summary: |

        Create title
      operationId: Titles_createNewTitle
      security:
        - OAuth2:
            - titles
      description: |

        This endpoint creates a new title
  /v2/titles/{id}:
    get:
      tags:
        - Titles
      summary: |

        Get title
      operationId: Titles_getTitleById
      security:
        - OAuth2:
            - titles
            - titles.readonly
      description: |

        This endpoint gets a title by ID.
  /v2/users:
    get:
      tags:
        - Users
      summary: |

        List users
      operationId: Users_listUsers
      security:
        - OAuth2:
            - users
            - users.readonly
      description: >

        This endpoint lists all users. To find a user id by email, you can
        filter using the `email` query parameter.
    post:
      tags:
        - Users
      summary: |

        Invite user
      operationId: Users_inviteNewEmployee
      security:
        - OAuth2:
            - users
      description: >

        This endpoint invites a new user as an employee.

        To update user's role, check out [this
        article](https://support.brex.com/how-do-i-change-another-user-s-role/).
  /v2/users/me:
    get:
      tags:
        - Users
      summary: |

        Get current user
      operationId: Users_getCurrentUser
      security:
        - OAuth2:
            - users
            - users.readonly
      description: |

        This endpoint returns the user associated with the OAuth2 access token.
  /v2/users/{id}:
    get:
      tags:
        - Users
      summary: |

        Get user
      operationId: Users_getUserById
      security:
        - OAuth2:
            - users
            - users.readonly
      description: |

        This endpoint gets a user by ID.
    put:
      tags:
        - Users
      summary: |

        Update user
      operationId: Users_updateUser
      security:
        - OAuth2:
            - users
      description: >

        This endpoint updates a user. Any parameters not provided will be left
        unchanged.
  /v2/users/{id}/limit:
    get:
      tags:
        - Users
      summary: |

        Get limit for the user
      operationId: Users_getMonthlyLimit
      security:
        - OAuth2:
            - users
            - users.readonly
      description: >

        This endpoint gets the monthly limit for the user including the monthly
        available limit.
    post:
      tags:
        - Users
      summary: |

        Set limit for the user
      operationId: Users_setMonthlyLimit
      security:
        - OAuth2:
            - users
      description: >

        This endpoint sets the monthly limit for a user. 

        The limit amount must be non-negative. 

        To unset the monthly limit of the user, just set `monthly_limit` to
        null.
components:
  securitySchemes:
    OAuth2:
      description: OAuth2 security scheme
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts-api.brex.com/oauth2/default/v1/authorize
          tokenUrl: https://accounts-api.brex.com/oauth2/default/v1/token
          scopes:
            openid: openid
            offline_access: offline access
            users.readonly: View user data
            users: View and manage user data
            locations.readonly: View location data
            locations: View and manage location data
            departments.readonly: View department data
            departments: View and manage department data
            titles: View and manage title data
            titles.readonly: View title data
            cards: View and manage card data
            cards.readonly: View card data
            cards.pan: View and Send card number data
security:
  - OAuth2: []
x-explorer-enabled: false
