openapi: 3.0.0
info:
  title: Slack Web API
  description: >-
    One way to interact with the Slack platform is its HTTP RPC-based Web API, a
    collection of methods requiring OAuth 2.0-based user, bot, or workspace
    tokens blessed with related OAuth scopes.
  version: 1.7.0
  contact:
    name: Slack developer relations
    url: https://api.slack.com/support
  x-apisguru-categories:
    - collaboration
    - messaging
  x-logo:
    url: http://static.tumblr.com/wvuzcz9/LlKncfhmp/slack_logo_240.png
  x-origin:
    - version: '3.0'
      format: openapi
      url: >-
        https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json
  x-providerName: slack.com
  x-konfig-ignore:
    object-with-no-properties: true
servers:
  - url: https://slack.com/api
tags:
  - name: admin
  - name: conversations
  - name: admin.conversations
  - name: files
  - name: users
  - name: chat
  - name: admin.users
  - name: apps
  - name: usergroups
  - name: admin.teams.settings
  - name: calls
  - name: files.remote
  - name: admin.emoji
  - name: dnd
  - name: reminders
  - name: team
  - name: admin.usergroups
  - name: reactions
  - name: views
  - name: admin.conversations.restrictAccess
  - name: admin.inviteRequests
  - name: oauth
  - name: pins
  - name: stars
  - name: workflows
  - name: admin.apps
  - name: admin.teams
  - name: admin.users.session
  - name: apps.permissions
  - name: apps.permissions.users
  - name: auth
  - name: calls.participants
  - name: usergroups.users
  - name: users.profile
  - name: admin.apps.approved
  - name: admin.apps.requests
  - name: admin.apps.restricted
  - name: admin.conversations.ekm
  - name: admin.inviteRequests.approved
  - name: admin.inviteRequests.denied
  - name: admin.teams.admins
  - name: admin.teams.owners
  - name: api
  - name: apps.event.authorizations
  - name: apps.permissions.resources
  - name: apps.permissions.scopes
  - name: bots
  - name: chat.scheduledMessages
  - name: dialog
  - name: emoji
  - name: files.comments
  - name: migration
  - name: oauth.v2
  - name: rtm
  - name: search
  - name: team.profile
paths:
  /admin.apps.approve:
    post:
      tags:
        - admin.apps
        - admin
      operationId: Adminapps_approveAppInstallation
      security:
        - slackAuth:
            - admin.apps:write
      description: Approve an app for installation on a workspace.
  /admin.apps.approved.list:
    get:
      tags:
        - admin.apps.approved
        - admin
      operationId: Adminappsapproved_list
      security:
        - slackAuth:
            - admin.apps:read
      description: List approved apps for an org or workspace.
  /admin.apps.requests.list:
    get:
      tags:
        - admin.apps.requests
        - admin
      operationId: Adminappsrequests_list
      security:
        - slackAuth:
            - admin.apps:read
      description: List app requests for a team/workspace.
  /admin.apps.restrict:
    post:
      tags:
        - admin.apps
        - admin
      operationId: Adminapps_restrictApp
      security:
        - slackAuth:
            - admin.apps:write
      description: Restrict an app for installation on a workspace.
  /admin.apps.restricted.list:
    get:
      tags:
        - admin.apps.restricted
        - admin
      operationId: Adminappsrestricted_getList
      security:
        - slackAuth:
            - admin.apps:read
      description: List restricted apps for an org or workspace.
  /admin.conversations.archive:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_archiveChannel
      security:
        - slackAuth:
            - admin.conversations:write
      description: Archive a public or private channel.
  /admin.conversations.convertToPrivate:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_convertToPrivateChannel
      security:
        - slackAuth:
            - admin.conversations:write
      description: Convert a public channel to a private channel.
  /admin.conversations.create:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_createChannelBasedConversation
      security:
        - slackAuth:
            - admin.conversations:write
      description: Create a public or private channel-based conversation.
  /admin.conversations.delete:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_deleteChannel
      security:
        - slackAuth:
            - admin.conversations:write
      description: Delete a public or private channel.
  /admin.conversations.disconnectShared:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_disconnectSharedChannel
      security:
        - slackAuth:
            - admin.conversations:write
      description: Disconnect a connected channel from one or more workspaces.
  /admin.conversations.ekm.listOriginalConnectedChannelInfo:
    get:
      tags:
        - admin.conversations.ekm
        - admin
      operationId: Adminconversationsekm_listOriginalConnectedChannelInfo
      security:
        - slackAuth:
            - admin.conversations:read
      description: >-
        List all disconnected channels—i.e., channels that were once connected
        to other workspaces and then disconnected—and the corresponding original
        channel IDs for key revocation with EKM.
  /admin.conversations.getConversationPrefs:
    get:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_getConversationPrefs
      security:
        - slackAuth:
            - admin.conversations:read
      description: Get conversation preferences for a public or private channel.
  /admin.conversations.getTeams:
    get:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_getTeamsList
      security:
        - slackAuth:
            - admin.conversations:read
      description: >-
        Get all the workspaces a given public or private channel is connected to
        within this Enterprise org.
  /admin.conversations.invite:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_inviteUserToChannel
      security:
        - slackAuth:
            - admin.conversations:write
      description: Invite a user to a public or private channel.
  /admin.conversations.rename:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_renameChannel
      security:
        - slackAuth:
            - admin.conversations:write
      description: Rename a public or private channel.
  /admin.conversations.restrictAccess.addGroup:
    post:
      tags:
        - admin.conversations.restrictAccess
        - admin
      operationId: AdminconversationsrestrictAccess_addGroupIdpGroups
      security:
        - slackAuth:
            - admin.conversations:write
      description: Add an allowlist of IDP groups for accessing a channel
  /admin.conversations.restrictAccess.listGroups:
    get:
      tags:
        - admin.conversations.restrictAccess
        - admin
      operationId: AdminconversationsrestrictAccess_listGroups
      security:
        - slackAuth:
            - admin.conversations:read
      description: List all IDP Groups linked to a channel
  /admin.conversations.restrictAccess.removeGroup:
    post:
      tags:
        - admin.conversations.restrictAccess
        - admin
      operationId: AdminconversationsrestrictAccess_removeIdpGroup
      security:
        - slackAuth:
            - admin.conversations:write
      description: Remove a linked IDP group linked from a private channel
  /admin.conversations.search:
    get:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_searchChannels
      security:
        - slackAuth:
            - admin.conversations:read
      description: Search for public or private channels in an Enterprise organization.
  /admin.conversations.setConversationPrefs:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_setConversationPrefs
      security:
        - slackAuth:
            - admin.conversations:write
      description: Set the posting permissions for a public or private channel.
  /admin.conversations.setTeams:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_setTeamsWorkspaceConnection
      security:
        - slackAuth:
            - admin.conversations:write
      description: >-
        Set the workspaces in an Enterprise grid org that connect to a public or
        private channel.
  /admin.conversations.unarchive:
    post:
      tags:
        - admin.conversations
        - admin
      operationId: Adminconversations_unarchiveChannel
      security:
        - slackAuth:
            - admin.conversations:write
      description: Unarchive a public or private channel.
  /admin.emoji.add:
    post:
      tags:
        - admin.emoji
        - admin
      operationId: Adminemoji_addEmoji
      security:
        - slackAuth:
            - admin.teams:write
      description: Add an emoji.
  /admin.emoji.addAlias:
    post:
      tags:
        - admin.emoji
        - admin
      operationId: Adminemoji_aliasAdd
      security:
        - slackAuth:
            - admin.teams:write
      description: Add an emoji alias.
  /admin.emoji.list:
    get:
      tags:
        - admin.emoji
        - admin
      operationId: Adminemoji_listEnterpriseEmoji
      security:
        - slackAuth:
            - admin.teams:read
      description: List emoji for an Enterprise Grid organization.
  /admin.emoji.remove:
    post:
      tags:
        - admin.emoji
        - admin
      operationId: Adminemoji_removeEnterpriseEmoji
      security:
        - slackAuth:
            - admin.teams:write
      description: Remove an emoji across an Enterprise Grid organization
  /admin.emoji.rename:
    post:
      tags:
        - admin.emoji
        - admin
      operationId: Adminemoji_renameEmoji
      security:
        - slackAuth:
            - admin.teams:write
      description: Rename an emoji.
  /admin.inviteRequests.approve:
    post:
      tags:
        - admin.inviteRequests
        - admin
      operationId: AdmininviteRequests_approveRequest
      security:
        - slackAuth:
            - admin.invites:write
      description: Approve a workspace invite request.
  /admin.inviteRequests.approved.list:
    get:
      tags:
        - admin.inviteRequests.approved
        - admin
      operationId: AdmininviteRequestsapproved_list
      security:
        - slackAuth:
            - admin.invites:read
      description: List all approved workspace invite requests.
  /admin.inviteRequests.denied.list:
    get:
      tags:
        - admin.inviteRequests.denied
        - admin
      operationId: AdmininviteRequestsdenied_list
      security:
        - slackAuth:
            - admin.invites:read
      description: List all denied workspace invite requests.
  /admin.inviteRequests.deny:
    post:
      tags:
        - admin.inviteRequests
        - admin
      operationId: AdmininviteRequests_denyRequest
      security:
        - slackAuth:
            - admin.invites:write
      description: Deny a workspace invite request.
  /admin.inviteRequests.list:
    get:
      tags:
        - admin.inviteRequests
        - admin
      operationId: AdmininviteRequests_listPendingWorkspaceInviteRequests
      security:
        - slackAuth:
            - admin.invites:read
      description: List all pending workspace invite requests.
  /admin.teams.admins.list:
    get:
      tags:
        - admin.teams.admins
        - admin
      operationId: Adminteamsadmins_getAll
      security:
        - slackAuth:
            - admin.teams:read
      description: List all of the admins on a given workspace.
  /admin.teams.create:
    post:
      tags:
        - admin.teams
        - admin
      operationId: Adminteams_createEnterpriseTeam
      security:
        - slackAuth:
            - admin.teams:write
      description: Create an Enterprise team.
  /admin.teams.list:
    get:
      tags:
        - admin.teams
        - admin
      operationId: Adminteams_listAll
      security:
        - slackAuth:
            - admin.teams:read
      description: List all teams on an Enterprise organization
  /admin.teams.owners.list:
    get:
      tags:
        - admin.teams.owners
        - admin
      operationId: Adminteamsowners_listOwners
      security:
        - slackAuth:
            - admin.teams:read
      description: List all of the owners on a given workspace.
  /admin.teams.settings.info:
    get:
      tags:
        - admin.teams.settings
        - admin
      operationId: Adminteamssettings_getInfo
      security:
        - slackAuth:
            - admin.teams:read
      description: Fetch information about settings in a workspace
  /admin.teams.settings.setDefaultChannels:
    post:
      tags:
        - admin.teams.settings
        - admin
      operationId: Adminteamssettings_setDefaultChannels
      security:
        - slackAuth:
            - admin.teams:write
      description: Set the default channels of a workspace.
  /admin.teams.settings.setDescription:
    post:
      tags:
        - admin.teams.settings
        - admin
      operationId: Adminteamssettings_setDescription
      security:
        - slackAuth:
            - admin.teams:write
      description: Set the description of a given workspace.
  /admin.teams.settings.setDiscoverability:
    post:
      tags:
        - admin.teams.settings
        - admin
      operationId: Adminteamssettings_setDiscoverabilityOfWorkspace
      security:
        - slackAuth:
            - admin.teams:write
      description: >-
        An API method that allows admins to set the discoverability of a given
        workspace
  /admin.teams.settings.setIcon:
    post:
      tags:
        - admin.teams.settings
        - admin
      operationId: Adminteamssettings_setIcon
      security:
        - slackAuth:
            - admin.teams:write
      description: Sets the icon of a workspace.
  /admin.teams.settings.setName:
    post:
      tags:
        - admin.teams.settings
        - admin
      operationId: Adminteamssettings_setName
      security:
        - slackAuth:
            - admin.teams:write
      description: Set the name of a given workspace.
  /admin.usergroups.addChannels:
    post:
      tags:
        - admin.usergroups
        - admin
      operationId: Adminusergroups_addDefaultChannels
      security:
        - slackAuth:
            - admin.usergroups:write
      description: Add one or more default channels to an IDP group.
  /admin.usergroups.addTeams:
    post:
      tags:
        - admin.usergroups
        - admin
      operationId: Adminusergroups_associateDefaultWorkspaces
      security:
        - slackAuth:
            - admin.teams:write
      description: >-
        Associate one or more default workspaces with an organization-wide IDP
        group.
  /admin.usergroups.listChannels:
    get:
      tags:
        - admin.usergroups
        - admin
      operationId: Adminusergroups_listChannelsGet
      security:
        - slackAuth:
            - admin.usergroups:read
      description: List the channels linked to an org-level IDP group (user group).
  /admin.usergroups.removeChannels:
    post:
      tags:
        - admin.usergroups
        - admin
      operationId: Adminusergroups_removeChannels
      security:
        - slackAuth:
            - admin.usergroups:write
      description: >-
        Remove one or more default channels from an org-level IDP group (user
        group).
  /admin.users.assign:
    post:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_addWorkspaceUser
      security:
        - slackAuth:
            - admin.users:write
      description: Add an Enterprise user to a workspace.
  /admin.users.invite:
    post:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_inviteUserToWorkspace
      security:
        - slackAuth:
            - admin.users:write
      description: Invite a user to a workspace.
  /admin.users.list:
    get:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_listWorkspaceUsers
      security:
        - slackAuth:
            - admin.users:read
      description: List users on a workspace
  /admin.users.remove:
    post:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_removeUserFromWorkspace
      security:
        - slackAuth:
            - admin.users:write
      description: Remove a user from a workspace.
  /admin.users.session.invalidate:
    post:
      tags:
        - admin.users.session
        - admin
      operationId: Adminuserssession_invalidateSession
      security:
        - slackAuth:
            - admin.users:write
      description: Invalidate a single session for a user by session_id
  /admin.users.session.reset:
    post:
      tags:
        - admin.users.session
        - admin
      operationId: Adminuserssession_resetSessions
      security:
        - slackAuth:
            - admin.users:write
      description: Wipes all valid sessions on all devices for a given user
  /admin.users.setAdmin:
    post:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_setAdminUser
      security:
        - slackAuth:
            - admin.users:write
      description: Set an existing guest, regular user, or owner to be an admin user.
  /admin.users.setExpiration:
    post:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_setExpirationGuest
      security:
        - slackAuth:
            - admin.users:write
      description: Set an expiration for a guest user
  /admin.users.setOwner:
    post:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_setWorkspaceOwner
      security:
        - slackAuth:
            - admin.users:write
      description: >-
        Set an existing guest, regular user, or admin user to be a workspace
        owner.
  /admin.users.setRegular:
    post:
      tags:
        - admin.users
        - admin
      operationId: Adminusers_setRegularUser
      security:
        - slackAuth:
            - admin.users:write
      description: Set an existing guest user, admin user, or owner to be a regular user.
  /api.test:
    get:
      tags:
        - api
      operationId: api_test
      security:
        - slackAuth:
            - none
      description: Checks API calling code.
  /apps.event.authorizations.list:
    get:
      tags:
        - apps.event.authorizations
        - apps
      operationId: Appseventauthorizations_getList
      security:
        - slackAuth:
            - authorizations:read
      description: >-
        Get a list of authorizations for the given event context. Each
        authorization represents an app installation that the event is visible
        to.
  /apps.permissions.info:
    get:
      tags:
        - apps.permissions
        - apps
      operationId: Appspermissions_listPermissions
      security:
        - slackAuth:
            - none
      description: Returns list of permissions this app has on a team.
  /apps.permissions.request:
    get:
      tags:
        - apps.permissions
        - apps
      operationId: Appspermissions_additionalScopesRequest
      security:
        - slackAuth:
            - none
      description: Allows an app to request additional scopes
  /apps.permissions.resources.list:
    get:
      tags:
        - apps.permissions.resources
        - apps
      operationId: Appspermissionsresources_getResourcesList
      security:
        - slackAuth:
            - none
      description: Returns list of resource grants this app has on a team.
  /apps.permissions.scopes.list:
    get:
      tags:
        - apps.permissions.scopes
        - apps
      operationId: Appspermissionsscopes_getList
      security:
        - slackAuth:
            - none
      description: Returns list of scopes this app has on a team.
  /apps.permissions.users.list:
    get:
      tags:
        - apps.permissions.users
        - apps
      operationId: Appspermissionsusers_listUserGrants
      security:
        - slackAuth:
            - none
      description: >-
        Returns list of user grants and corresponding scopes this app has on a
        team.
  /apps.permissions.users.request:
    get:
      tags:
        - apps.permissions.users
        - apps
      operationId: Appspermissionsusers_requestModal
      security:
        - slackAuth:
            - none
      description: >-
        Enables an app to trigger a permissions modal to grant an app access to
        a user access scope.
  /apps.uninstall:
    get:
      tags:
        - apps
      operationId: apps_uninstall
      security:
        - slackAuth:
            - none
      description: Uninstalls your app from a workspace.
  /auth.revoke:
    get:
      tags:
        - auth
      operationId: auth_revoke
      security:
        - slackAuth:
            - none
      description: Revokes a token.
  /auth.test:
    get:
      tags:
        - auth
      operationId: auth_test
      security:
        - slackAuth:
            - none
      description: Checks authentication & identity.
  /bots.info:
    get:
      tags:
        - bots
      operationId: bots_info
      security:
        - slackAuth:
            - users:read
      description: Gets information about a bot user.
  /calls.add:
    post:
      tags:
        - calls
      operationId: calls_add
      security:
        - slackAuth:
            - calls:write
      description: Registers a new Call.
  /calls.end:
    post:
      tags:
        - calls
      operationId: calls_end
      security:
        - slackAuth:
            - calls:write
      description: Ends a Call.
  /calls.info:
    get:
      tags:
        - calls
      operationId: calls_info
      security:
        - slackAuth:
            - calls:read
      description: Returns information about a Call.
  /calls.participants.add:
    post:
      tags:
        - calls.participants
        - calls
      operationId: Callsparticipants_addNewParticipant
      security:
        - slackAuth:
            - calls:write
      description: Registers new participants added to a Call.
  /calls.participants.remove:
    post:
      tags:
        - calls.participants
        - calls
      operationId: Callsparticipants_registerRemoved
      security:
        - slackAuth:
            - calls:write
      description: Registers participants removed from a Call.
  /calls.update:
    post:
      tags:
        - calls
      operationId: calls_update
      security:
        - slackAuth:
            - calls:write
      description: Updates information about a Call.
  /chat.delete:
    post:
      tags:
        - chat
      operationId: chat_delete
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      description: Deletes a message.
  /chat.deleteScheduledMessage:
    post:
      tags:
        - chat
      operationId: chat_deleteScheduledMessage
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      description: Deletes a pending scheduled message from the queue.
  /chat.getPermalink:
    get:
      tags:
        - chat
      operationId: chat_getPermalink
      security:
        - slackAuth:
            - none
      description: Retrieve a permalink URL for a specific extant message
  /chat.meMessage:
    post:
      tags:
        - chat
      operationId: chat_meMessage
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      description: Share a me message into a channel.
  /chat.postEphemeral:
    post:
      tags:
        - chat
      operationId: chat_postEphemeral
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      description: Sends an ephemeral message to a user in a channel.
  /chat.postMessage:
    post:
      tags:
        - chat
      operationId: chat_postMessage
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      description: Sends a message to a channel.
  /chat.scheduleMessage:
    post:
      tags:
        - chat
      operationId: chat_scheduleMessage
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      description: Schedules a message to be sent to a channel.
  /chat.scheduledMessages.list:
    get:
      tags:
        - chat.scheduledMessages
        - chat
      operationId: ChatscheduledMessages_list
      security:
        - slackAuth:
            - none
      description: Returns a list of scheduled messages.
  /chat.unfurl:
    post:
      tags:
        - chat
      operationId: chat_unfurl
      security:
        - slackAuth:
            - links:write
      description: Provide custom unfurl behavior for user-posted URLs
  /chat.update:
    post:
      tags:
        - chat
      operationId: chat_update
      security:
        - slackAuth:
            - chat:write:user
            - chat:write:bot
      description: Updates a message.
  /conversations.archive:
    post:
      tags:
        - conversations
      operationId: conversations_archive
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Archives a conversation.
  /conversations.close:
    post:
      tags:
        - conversations
      operationId: conversations_close
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Closes a direct message or multi-person direct message.
  /conversations.create:
    post:
      tags:
        - conversations
      operationId: conversations_create
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Initiates a public or private channel-based conversation
  /conversations.history:
    get:
      tags:
        - conversations
      operationId: conversations_history
      security:
        - slackAuth:
            - channels:history
            - groups:history
            - im:history
            - mpim:history
      description: Fetches a conversation's history of messages and events.
  /conversations.info:
    get:
      tags:
        - conversations
      operationId: conversations_info
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      description: Retrieve information about a conversation.
  /conversations.invite:
    post:
      tags:
        - conversations
      operationId: conversations_invite
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Invites users to a channel.
  /conversations.join:
    post:
      tags:
        - conversations
      operationId: conversations_join
      security:
        - slackAuth:
            - channels:write
      description: Joins an existing conversation.
  /conversations.kick:
    post:
      tags:
        - conversations
      operationId: conversations_kick
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Removes a user from a conversation.
  /conversations.leave:
    post:
      tags:
        - conversations
      operationId: conversations_leave
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Leaves a conversation.
  /conversations.list:
    get:
      tags:
        - conversations
      operationId: conversations_list
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      description: Lists all channels in a Slack team.
  /conversations.mark:
    post:
      tags:
        - conversations
      operationId: conversations_mark
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Sets the read cursor in a channel.
  /conversations.members:
    get:
      tags:
        - conversations
      operationId: conversations_members
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      description: Retrieve members of a conversation.
  /conversations.open:
    post:
      tags:
        - conversations
      operationId: conversations_open
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Opens or resumes a direct message or multi-person direct message.
  /conversations.rename:
    post:
      tags:
        - conversations
      operationId: conversations_rename
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Renames a conversation.
  /conversations.replies:
    get:
      tags:
        - conversations
      operationId: conversations_replies
      security:
        - slackAuth:
            - channels:history
            - groups:history
            - im:history
            - mpim:history
      description: Retrieve a thread of messages posted to a conversation
  /conversations.setPurpose:
    post:
      tags:
        - conversations
      operationId: conversations_setPurpose
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Sets the purpose for a conversation.
  /conversations.setTopic:
    post:
      tags:
        - conversations
      operationId: conversations_setTopic
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Sets the topic for a conversation.
  /conversations.unarchive:
    post:
      tags:
        - conversations
      operationId: conversations_unarchive
      security:
        - slackAuth:
            - channels:write
            - groups:write
            - im:write
            - mpim:write
      description: Reverses conversation archival.
  /dialog.open:
    get:
      tags:
        - dialog
      operationId: dialog_open
      security:
        - slackAuth:
            - none
      description: Open a dialog with a user
  /dnd.endDnd:
    post:
      tags:
        - dnd
      operationId: dnd_endDnd
      security:
        - slackAuth:
            - dnd:write
      description: Ends the current user's Do Not Disturb session immediately.
  /dnd.endSnooze:
    post:
      tags:
        - dnd
      operationId: dnd_endSnooze
      security:
        - slackAuth:
            - dnd:write
      description: Ends the current user's snooze mode immediately.
  /dnd.info:
    get:
      tags:
        - dnd
      operationId: dnd_info
      security:
        - slackAuth:
            - dnd:read
      description: Retrieves a user's current Do Not Disturb status.
  /dnd.setSnooze:
    post:
      tags:
        - dnd
      operationId: dnd_setSnooze
      security:
        - slackAuth:
            - dnd:write
      description: >-
        Turns on Do Not Disturb mode for the current user, or changes its
        duration.
  /dnd.teamInfo:
    get:
      tags:
        - dnd
      operationId: dnd_teamInfo
      security:
        - slackAuth:
            - dnd:read
      description: Retrieves the Do Not Disturb status for up to 50 users on a team.
  /emoji.list:
    get:
      tags:
        - emoji
      operationId: emoji_list
      security:
        - slackAuth:
            - emoji:read
      description: Lists custom emoji for a team.
  /files.comments.delete:
    post:
      tags:
        - files.comments
        - files
      operationId: Filescomments_deleteComment
      security:
        - slackAuth:
            - files:write:user
      description: Deletes an existing comment on a file.
  /files.delete:
    post:
      tags:
        - files
      operationId: files_delete
      security:
        - slackAuth:
            - files:write:user
      description: Deletes a file.
  /files.info:
    get:
      tags:
        - files
      operationId: files_info
      security:
        - slackAuth:
            - files:read
      description: Gets information about a file.
  /files.list:
    get:
      tags:
        - files
      operationId: files_list
      security:
        - slackAuth:
            - files:read
      description: List for a team, in a channel, or from a user with applied filters.
  /files.remote.add:
    post:
      tags:
        - files.remote
        - files
      operationId: Filesremote_addFromRemote
      security:
        - slackAuth:
            - remote_files:write
      description: Adds a file from a remote service
  /files.remote.info:
    get:
      tags:
        - files.remote
        - files
      operationId: Filesremote_getInfo
      security:
        - slackAuth:
            - remote_files:read
      description: Retrieve information about a remote file added to Slack
  /files.remote.list:
    get:
      tags:
        - files.remote
        - files
      operationId: Filesremote_listRemoteFiles
      security:
        - slackAuth:
            - remote_files:read
      description: Retrieve information about a remote file added to Slack
  /files.remote.remove:
    post:
      tags:
        - files.remote
        - files
      operationId: Filesremote_deleteFile
      security:
        - slackAuth:
            - remote_files:write
      description: Remove a remote file.
  /files.remote.share:
    get:
      tags:
        - files.remote
        - files
      operationId: Filesremote_shareRemoteFile
      security:
        - slackAuth:
            - remote_files:share
      description: Share a remote file into a channel.
  /files.remote.update:
    post:
      tags:
        - files.remote
        - files
      operationId: Filesremote_updateRemoteFile
      security:
        - slackAuth:
            - remote_files:write
      description: Updates an existing remote file.
  /files.revokePublicURL:
    post:
      tags:
        - files
      operationId: files_revokePublicURL
      security:
        - slackAuth:
            - files:write:user
      description: Revokes public/external sharing access for a file
  /files.sharedPublicURL:
    post:
      tags:
        - files
      operationId: files_sharedPublicURL
      security:
        - slackAuth:
            - files:write:user
      description: Enables a file for public/external sharing.
  /files.upload:
    post:
      tags:
        - files
      operationId: files_upload
      security:
        - slackAuth:
            - files:write:user
      description: Uploads or creates a file.
  /migration.exchange:
    get:
      tags:
        - migration
      operationId: migration_exchange
      security:
        - slackAuth:
            - tokens.basic
      description: For Enterprise Grid workspaces, map local user IDs to global user IDs
  /oauth.access:
    get:
      tags:
        - oauth
      operationId: oauth_access
      security:
        - slackAuth:
            - none
      description: Exchanges a temporary OAuth verifier code for an access token.
  /oauth.token:
    get:
      tags:
        - oauth
      operationId: oauth_token
      security:
        - slackAuth:
            - none
      description: Exchanges a temporary OAuth verifier code for a workspace token.
  /oauth.v2.access:
    get:
      tags:
        - oauth.v2
        - oauth
      operationId: Oauthv2_exchangeToken
      security:
        - slackAuth:
            - none
      description: Exchanges a temporary OAuth verifier code for an access token.
  /pins.add:
    post:
      tags:
        - pins
      operationId: pins_add
      security:
        - slackAuth:
            - pins:write
      description: Pins an item to a channel.
  /pins.list:
    get:
      tags:
        - pins
      operationId: pins_list
      security:
        - slackAuth:
            - pins:read
      description: Lists items pinned to a channel.
  /pins.remove:
    post:
      tags:
        - pins
      operationId: pins_remove
      security:
        - slackAuth:
            - pins:write
      description: Un-pins an item from a channel.
  /reactions.add:
    post:
      tags:
        - reactions
      operationId: reactions_add
      security:
        - slackAuth:
            - reactions:write
      description: Adds a reaction to an item.
  /reactions.get:
    get:
      tags:
        - reactions
      operationId: reactions_get
      security:
        - slackAuth:
            - reactions:read
      description: Gets reactions for an item.
  /reactions.list:
    get:
      tags:
        - reactions
      operationId: reactions_list
      security:
        - slackAuth:
            - reactions:read
      description: Lists reactions made by a user.
  /reactions.remove:
    post:
      tags:
        - reactions
      operationId: reactions_remove
      security:
        - slackAuth:
            - reactions:write
      description: Removes a reaction from an item.
  /reminders.add:
    post:
      tags:
        - reminders
      operationId: reminders_add
      security:
        - slackAuth:
            - reminders:write
      description: Creates a reminder.
  /reminders.complete:
    post:
      tags:
        - reminders
      operationId: reminders_complete
      security:
        - slackAuth:
            - reminders:write
      description: Marks a reminder as complete.
  /reminders.delete:
    post:
      tags:
        - reminders
      operationId: reminders_delete
      security:
        - slackAuth:
            - reminders:write
      description: Deletes a reminder.
  /reminders.info:
    get:
      tags:
        - reminders
      operationId: reminders_info
      security:
        - slackAuth:
            - reminders:read
      description: Gets information about a reminder.
  /reminders.list:
    get:
      tags:
        - reminders
      operationId: reminders_list
      security:
        - slackAuth:
            - reminders:read
      description: Lists all reminders created by or for a given user.
  /rtm.connect:
    get:
      tags:
        - rtm
      operationId: rtm_connect
      security:
        - slackAuth:
            - rtm:stream
      description: Starts a Real Time Messaging session.
  /search.messages:
    get:
      tags:
        - search
      operationId: search_messages
      security:
        - slackAuth:
            - search:read
      description: Searches for messages matching a query.
  /stars.add:
    post:
      tags:
        - stars
      operationId: stars_add
      security:
        - slackAuth:
            - stars:write
      description: Adds a star to an item.
  /stars.list:
    get:
      tags:
        - stars
      operationId: stars_list
      security:
        - slackAuth:
            - stars:read
      description: Lists stars for a user.
  /stars.remove:
    post:
      tags:
        - stars
      operationId: stars_remove
      security:
        - slackAuth:
            - stars:write
      description: Removes a star from an item.
  /team.accessLogs:
    get:
      tags:
        - team
      operationId: team_accessLogs
      security:
        - slackAuth:
            - admin
      description: Gets the access logs for the current team.
  /team.billableInfo:
    get:
      tags:
        - team
      operationId: team_billableInfo
      security:
        - slackAuth:
            - admin
      description: Gets billable users information for the current team.
  /team.info:
    get:
      tags:
        - team
      operationId: team_info
      security:
        - slackAuth:
            - team:read
      description: Gets information about the current team.
  /team.integrationLogs:
    get:
      tags:
        - team
      operationId: team_integrationLogs
      security:
        - slackAuth:
            - admin
      description: Gets the integration logs for the current team.
  /team.profile.get:
    get:
      tags:
        - team.profile
        - team
      operationId: Teamprofile_getProfile
      security:
        - slackAuth:
            - users.profile:read
      description: Retrieve a team's profile.
  /usergroups.create:
    post:
      tags:
        - usergroups
      operationId: usergroups_create
      security:
        - slackAuth:
            - usergroups:write
      description: Create a User Group
  /usergroups.disable:
    post:
      tags:
        - usergroups
      operationId: usergroups_disable
      security:
        - slackAuth:
            - usergroups:write
      description: Disable an existing User Group
  /usergroups.enable:
    post:
      tags:
        - usergroups
      operationId: usergroups_enable
      security:
        - slackAuth:
            - usergroups:write
      description: Enable a User Group
  /usergroups.list:
    get:
      tags:
        - usergroups
      operationId: usergroups_list
      security:
        - slackAuth:
            - usergroups:read
      description: List all User Groups for a team
  /usergroups.update:
    post:
      tags:
        - usergroups
      operationId: usergroups_update
      security:
        - slackAuth:
            - usergroups:write
      description: Update an existing User Group
  /usergroups.users.list:
    get:
      tags:
        - usergroups.users
        - usergroups
      operationId: Usergroupsusers_listAllUsers
      security:
        - slackAuth:
            - usergroups:read
      description: List all users in a User Group
  /usergroups.users.update:
    post:
      tags:
        - usergroups.users
        - usergroups
      operationId: Usergroupsusers_updateList
      security:
        - slackAuth:
            - usergroups:write
      description: Update the list of users for a User Group
  /users.conversations:
    get:
      tags:
        - users
      operationId: users_conversations
      security:
        - slackAuth:
            - channels:read
            - groups:read
            - im:read
            - mpim:read
      description: List conversations the calling user may access.
  /users.deletePhoto:
    post:
      tags:
        - users
      operationId: users_deletePhoto
      security:
        - slackAuth:
            - users.profile:write
      description: Delete the user profile photo
  /users.getPresence:
    get:
      tags:
        - users
      operationId: users_getPresence
      security:
        - slackAuth:
            - users:read
      description: Gets user presence information.
  /users.identity:
    get:
      tags:
        - users
      operationId: users_identity
      security:
        - slackAuth:
            - identity.basic
      description: Get a user's identity.
  /users.info:
    get:
      tags:
        - users
      operationId: users_info
      security:
        - slackAuth:
            - users:read
      description: Gets information about a user.
  /users.list:
    get:
      tags:
        - users
      operationId: users_list
      security:
        - slackAuth:
            - users:read
      description: Lists all users in a Slack team.
  /users.lookupByEmail:
    get:
      tags:
        - users
      operationId: users_lookupByEmail
      security:
        - slackAuth:
            - users:read.email
      description: Find a user with an email address.
  /users.profile.get:
    get:
      tags:
        - users.profile
        - users
      operationId: Usersprofile_getProfileInfo
      security:
        - slackAuth:
            - users.profile:read
      description: Retrieves a user's profile information.
  /users.profile.set:
    post:
      tags:
        - users.profile
        - users
      operationId: Usersprofile_setProfileInfo
      security:
        - slackAuth:
            - users.profile:write
      description: Set the profile information for a user.
  /users.setActive:
    post:
      tags:
        - users
      operationId: users_setActive
      security:
        - slackAuth:
            - users:write
      description: Marked a user as active. Deprecated and non-functional.
  /users.setPhoto:
    post:
      tags:
        - users
      operationId: users_setPhoto
      security:
        - slackAuth:
            - users.profile:write
      description: Set the user profile photo
  /users.setPresence:
    post:
      tags:
        - users
      operationId: users_setPresence
      security:
        - slackAuth:
            - users:write
      description: Manually sets user presence.
  /views.open:
    get:
      tags:
        - views
      operationId: views_open
      security:
        - slackAuth:
            - none
      description: Open a view for a user.
  /views.publish:
    get:
      tags:
        - views
      operationId: views_publish
      security:
        - slackAuth:
            - none
      description: Publish a static view for a User.
  /views.push:
    get:
      tags:
        - views
      operationId: views_push
      security:
        - slackAuth:
            - none
      description: Push a view onto the stack of a root view.
  /views.update:
    get:
      tags:
        - views
      operationId: views_update
      security:
        - slackAuth:
            - none
      description: Update an existing view.
  /workflows.stepCompleted:
    get:
      tags:
        - workflows
      operationId: workflows_stepCompleted
      security:
        - slackAuth:
            - workflow.steps:execute
      description: Indicate that an app's step in a workflow completed execution.
  /workflows.stepFailed:
    get:
      tags:
        - workflows
      operationId: workflows_stepFailed
      security:
        - slackAuth:
            - workflow.steps:execute
      description: Indicate that an app's step in a workflow failed to execute.
  /workflows.updateStep:
    get:
      tags:
        - workflows
      operationId: workflows_updateStep
      security:
        - slackAuth:
            - workflow.steps:execute
      description: Update the configuration for a workflow extension step.
components:
  securitySchemes:
    slackAuth:
      flows:
        authorizationCode:
          authorizationUrl: https://slack.com/oauth/authorize
          scopes:
            admin: admin
            admin.apps:read: admin.apps:read
            admin.apps:write: admin.apps:write
            admin.conversations:read: admin.conversations:read
            admin.conversations:write: admin.conversations:write
            admin.invites:read: admin.invites:read
            admin.invites:write: admin.invites:write
            admin.teams:read: admin.teams:read
            admin.teams:write: admin.teams:write
            admin.usergroups:read: admin.usergroups:read
            admin.usergroups:write: admin.usergroups:write
            admin.users:read: admin.users:read
            admin.users:write: admin.users:write
            authorizations:read: authorizations:read
            bot: Bot user scope
            calls:read: calls:read
            calls:write: calls:write
            channels:history: channels:history
            channels:manage: channels:manage
            channels:read: channels:read
            channels:write: channels:write
            chat:write: chat:write
            chat:write:bot: Author messages as a bot
            chat:write:user: Author messages as a user
            conversations:history: conversations:history
            conversations:read: conversations:read
            conversations:write: conversations:write
            dnd:read: dnd:read
            dnd:write: dnd:write
            emoji:read: emoji:read
            files:read: files:read
            files:write:user: files:write:user
            groups:history: groups:history
            groups:read: groups:read
            groups:write: groups:write
            identity.basic: identity.basic
            im:history: im:history
            im:read: im:read
            im:write: im:write
            links:write: links:write
            mpim:history: mpim:history
            mpim:read: mpim:read
            mpim:write: mpim:write
            none: No scope required
            pins:read: pins:read
            pins:write: pins:write
            reactions:read: reactions:read
            reactions:write: reactions:write
            reminders:read: reminders:read
            reminders:write: reminders:write
            remote_files:read: remote_files:read
            remote_files:share: remote_files:share
            remote_files:write: remote_files:write
            rtm:stream: rtm:stream
            search:read: search:read
            stars:read: stars:read
            stars:write: stars:write
            team:read: team:read
            tokens.basic: tokens.basic
            usergroups:read: usergroups:read
            usergroups:write: usergroups:write
            users.profile:read: users.profile:read
            users.profile:write: users.profile:write
            users:read: users:read
            users:read.email: users:read.email
            users:write: users:write
            workflow.steps:execute: workflow.steps:execute
          tokenUrl: https://slack.com/api/oauth.access
      type: oauth2