openapi: 3.0.1
info:
  title: Adatree ADR Platform Consent API
  description: >-
    Consent Dashboard REST APIs. This allows ADR / consumers to perform CDR
    consumer authorization flow with Data Holders
  version: 1.3.0
  contact:
    name: Adatree
    email: engineering@adatree.com.au
  x-konfig-ignore:
    potential-incorrect-type: true
servers:
  - description: Server url
    url: https://cdr-insights-prod.api.adatree.com.au
tags:
  - name: Consent
  - name: Consent Authorization
  - name: Get consent events
  - name: Data Holders
  - name: Tokens
  - name: UseCase
paths:
  /consents:
    get:
      tags:
        - Consent
      summary: Get Consents
      operationId: Consent_getAllRecords
      security:
        - bearerAuth:
            - consumer:consents:read
            - consents:read
        - m2m:
            - consents:read
      description: Get all consent records for this consumer
    post:
      tags:
        - Consent
      summary: Create Consent
      operationId: Consent_recordCreate
      security:
        - bearerAuth:
            - consumer:consents:write
            - consents:write
        - m2m:
            - consents:write
      description: Create a consent record for consumer
  /consents/{consentId}:
    get:
      tags:
        - Consent
      summary: Get Consent
      operationId: Consent_getRecord
      security:
        - bearerAuth:
            - consumer:consents:read
            - consents:read
        - m2m:
            - consents:read
      description: Retreive a single consent record for this consumer
    patch:
      tags:
        - Consent
      summary: Update a consent's via dashboard or back channel
      operationId: Consent_updateViaDashboard
      security:
        - bearerAuth:
            - consumer:consents:write
            - consents:write
        - m2m:
            - consents:write
      description: >
        <ul><li>Update postUsageAction, directMarketing option or sharing end
        date when a dashboard token is received</li><br/>

        <li>Update externalId when a machine (backchannel) token is
        received</li></ul>
    delete:
      tags:
        - Consent
      summary: Revoke Consent
      operationId: Consent_revokeRecord
      security:
        - bearerAuth:
            - consumer:consents:write
            - consents:write
        - m2m:
            - consents:write
      description: Revoke a single consent record for this consumer
  /consents/{consentId}/authorization:
    get:
      tags:
        - Consent Authorization
      summary: Get Authorization Redirect URL for a Consent
      operationId: ConsentAuthorization_redirectUrl
      security:
        - bearerAuth:
            - consumer:consents:read
            - consents:read
        - m2m:
            - consents:read
      description: >-
        Get the authorization redirect URL to send the consumer to the data
        holder
  /consents/events:
    get:
      tags:
        - Get consent events
      summary: Retrieve consent events
      operationId: GetConsentEvents_list
      security:
        - bearerAuth:
            - consumer:consents:read
            - consents:read
        - m2m:
            - consents:read
  /software-products/{softwareProductId}/data-holders:
    get:
      tags:
        - Data Holders
      summary: Get Data Holders
      operationId: DataHolders_listAvailable
      security:
        - bearerAuth:
            - consumer:data-holders:read
            - data-holders:read
        - m2m:
            - data-holders:read
      description: Get the list of available data holders for a software product
  /tokens:
    post:
      tags:
        - Tokens
      summary: Create Tokens
      operationId: Tokens_establishDataAccess
      security:
        - bearerAuth:
            - consumer:tokens:write
            - consumer_tokens_write
            - tokens:write
            - tokens_write
        - m2m:
            - tokens:write
      description: >-
        Send the required parameters from the data holder to the ADR Platform
        backend to finish extablishing data access
  /use-cases:
    get:
      tags:
        - UseCase
      summary: Get Use-cases
      operationId: UseCase_getAll
      security:
        - bearerAuth:
            - consumer:use-cases:read
            - use-cases:read
        - m2m:
            - use-cases:read
      description: >-
        Get all use-cases that have been configured. A use case is your reason
        for requesting consent from a consumer e.g. a home loan assessment, a
        budgeting app.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    m2m:
      description: Machine to machine OAuth2 to access infosec token service
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: >-
            https://adatree-nonprod-adr.auth.ap-southeast-2.amazoncognito.com/oauth2/token
          scopes:
            authorizations:write: allow ADR to create a Authorisation Request for a consumer
            tokens:write: allow ADR to create or update Authorisation Request