openapi: 3.0.0
info:
  title: Zoom Meeting API
  description: 'The Zoom Meeting APIs let developers to access information from Zoom. '
  version: '2'
  termsOfService: https://zoom.us/docs/en-us/zoom_api_license_and_tou.html
  contact:
    name: Zoom Developers
    url: https://developer.zoom.us/
  x-konfig-ignore:
    object-with-no-properties: true
    potential-incorrect-type: true
servers:
  - url: https://api.zoom.us/v2
tags:
  - name: Webinars
  - name: Meetings
  - name: Reports
  - name: Cloud Recording
  - name: Devices
  - name: TSP
  - name: Archiving
  - name: Tracking Field
  - name: H323 Devices
  - name: SIP Phone
  - name: PAC
paths:
  /archive_files:
    get:
      tags:
        - Archiving
      summary: List archived files
      operationId: Archiving_meetingFilesList
      security:
        - openapi_oauth:
            - recording:read:admin
          openapi_authorization: []
      description: >-
        Get an account's archived meeting or webinar files. 

         Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) lets account administrators set up an automated mechanism to record, collect, and archive meeting data to a third-party platform of their choice to satisfy FINRA or other compliance requirements. 

         **Prerequisites:** 
        * The [**Meeting and Webinar Archiving**
        feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)
        enabled for your account by [Zoom
        Support](https://support.zoom.us/hc/en-us/articles/201362003).


        **Scopes:** `recording:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - Recording:Read
        x-macro-scopes:
          - recording:read:admin
        x-granular-scopes:
          - archiving:read:list_archived_files:admin
          - archiving:read:list_archived_files
  /archive_files/statistics:
    get:
      tags:
        - Archiving
      summary: Get archived file statistics
      operationId: Archiving_getStatistics
      security:
        - openapi_oauth:
            - recording:read:admin
          openapi_authorization: []
      description: >-
        Get statistics about an account's archived meeting or webinar files. 

         Zoom's [archiving solution](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators) lets account administrators set up an automated mechanism to record, collect, and archive meeting data to a third-party platform of their choice to satisfy FINRA and other compliance requirements. 

         **Prerequisites:** 
        * The [**Meeting and Webinar Archiving**
        feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)
        enabled for your account by [Zoom
        Support](https://support.zoom.us/hc/en-us/articles/201362003).


        **Scopes:** `recording:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - recording:read:admin
  /archive_files/{fileId}:
    patch:
      tags:
        - Archiving
      summary: Update an archived file's auto-delete status
      operationId: Archiving_updateAutoDeleteStatus
      security:
        - openapi_oauth:
            - recording:write
            - recording:write:admin
          openapi_authorization: []
      description: >-
        Update an archived file's auto-delete status. 

         **Prerequisites:** 
        * [Zoom Support](https://support.zoom.us/hc/en-us/articles/201362003)
        must enable the [**Meeting and Webinar Archiving**
        feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)
        for your account.

        * Open the disabling auto-delete feature in OP. Contact [Zoom
        Support](https://support.zoom.us/hc/en-us/articles/201362003) to open.


        **Scopes:** `recording:write`,`recording:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - Recording:Edit
        x-macro-scopes:
          - recording:write
          - recording:write:admin
  /past_meetings/{meetingUUID}/archive_files:
    get:
      tags:
        - Archiving
      summary: Get a meeting's archived files
      operationId: Archiving_meetingFilesList
      security:
        - openapi_oauth:
            - recording:read
          openapi_authorization: []
      description: >-
        Return a specific meeting instance's [archived
        files](https://support.zoom.us/hc/en-us/articles/360050431572-Archiving-indicators). 

         **Prerequisites:** 
        * The [**Meeting and Webinar Archiving**
        feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)
        enabled for your account by [Zoom
        Support](https://support.zoom.us/hc/en-us/articles/201362003).


        **Scopes:** `recording:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions: []
        x-macro-scopes:
          - recording:read
    delete:
      tags:
        - Archiving
      summary: Delete a meeting's archived files
      operationId: Archiving_meetingFilesDelete
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        Use this API to delete all of a meeting's archived files. 

         **Prerequisites:** 
        * The [**Meeting and Webinar Archiving**
        feature](https://support.zoom.us/hc/en-us/articles/4405656451213--Archiving-for-meetings-and-webinars)
        enabled for your account by [Zoom
        Support](https://support.zoom.us/hc/en-us/articles/201362003).


        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /meetings/{meetingId}/recordings:
    get:
      tags:
        - Cloud Recording
      summary: Get meeting recordings
      operationId: CloudRecording_getMeetingRecordings
      security:
        - openapi_oauth:
            - recording:read
            - phone_recording:read:admin
          openapi_authorization: []
      description: >-
        Returns all of a meeting's
        [recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording#h_7420acb5-1897-4061-87b4-5b76e99c03b4).

         Use the `download_url` property listed in the response to download the recording files.  To access a passcode-protected cloud recording, send the user's [OAuth access token](https://developers.zoom.us/docs/integrations/oauth/) as a Bearer token in the Authorization header. 
         
         Example:  `curl -H 'Authorization: Bearer <ACCESS_TOKEN>' https://{{base-domain}}/rec/archive/download/xyz`  

        **Scopes:** `recording:read`,`phone_recording:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions: []
        x-macro-scopes:
          - recording:read
          - phone_recording:read:admin
    delete:
      tags:
        - Cloud Recording
      summary: Delete meeting recordings
      operationId: CloudRecording_deleteMeetingRecordings
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        Delete all recording files of a meeting.  
           
         

        **Prerequisites**:

        * Cloud Recording should be enabled on the user's account.  
         


        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /meetings/{meetingId}/recordings/analytics_details:
    get:
      tags:
        - Cloud Recording
      summary: Get Meeting Recording's Analytics Details
      operationId: analytics_details
      security:
        - openapi_oauth:
            - recording:read:admin
            - recording:read
          openapi_authorization: []
      description: >-
        Use this API to return a meeting recording's [analytics
        details](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163).
        **Maximum duration: 1 Month**. To access a password-protected cloud
        recording, send the user's [OAuth access
        token](https://developers.zoom.us/docs/integrations/oauth/) as a Bearer
        token in the Authorization header. For example, 

         `curl -H &quot;Authorization: Bearer &lt;ACCESS_TOKEN&gt;&quot; https://{{base-domain}}/rec/archive/download/xyz` 

         

        **Scopes:** `recording:read:admin`,`recording:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - recording:read:admin
          - recording:read
  /meetings/{meetingId}/recordings/analytics_summary:
    get:
      tags:
        - Cloud Recording
      summary: Get Meeting Recording's Analytics Summary
      operationId: analytics_summary
      security:
        - openapi_oauth:
            - recording:read:admin
            - recording:read
          openapi_authorization: []
      description: >-
        Use this API to return a meeting recording's [analytics
        summary](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings#h_0b665029-ce74-4849-9794-d1aa0320d163).
        **Maximum duration: 1 Month**. To access a password-protected cloud
        recording, send the user's [OAuth access
        token](https://developers.zoom.us/docs/integrations/oauth/) as a Bearer
        token in the Authorization header. For example, 

         `curl -H &quot;Authorization: Bearer &lt;ACCESS_TOKEN&gt;&quot; https://{{base-domain}}/rec/archive/download/xyz` 

         

        **Scopes:** `recording:read:admin`,`recording:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - recording:read:admin
          - recording:read
  /meetings/{meetingId}/recordings/registrants:
    get:
      tags:
        - Cloud Recording
      summary: List recording registrants
      operationId: CloudRecording_listRegistrants
      security:
        - openapi_oauth:
            - recording:read:admin
            - recording:read
          openapi_authorization: []
      description: >-
        Use this API to list registrants of a past meeting's [on-demand cloud
        recordings](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-recordings).
        Users must [register](https://developers.zoom.us) to view the
        recordings. 

         

        **Scopes:** `recording:read:admin`,`recording:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - recording:read:admin
          - recording:read
    post:
      tags:
        - Cloud Recording
      summary: Create a recording registrant
      operationId: CloudRecording_createRegistrant
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        Cloud Recordings of past Zoom Meetings can be made
        [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings).
        Users should be [registered](https://developers.zoom.us) to view these
        recordings.


        Use this API to register a user to gain access to **On-demand Cloud
        Recordings** of a past meeting.  
         


        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /meetings/{meetingId}/recordings/registrants/questions:
    get:
      tags:
        - Cloud Recording
      summary: Get registration questions
      operationId: CloudRecording_listRegistrationQuestions
      security:
        - openapi_oauth:
            - recording:read:admin
            - recording:read
          openapi_authorization: []
      description: >-
        For
        [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings)
        meeting recordings, you can include fields with questions that will be
        shown to registrants when they register to view the recording.


        Use this API to retrieve a list of questions that are displayed for
        users to complete when registering to view the recording of a specific
        meeting.  
         


        **Scopes:** `recording:read:admin`,`recording:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:read:admin
          - recording:read
    patch:
      tags:
        - Cloud Recording
      summary: Update registration questions
      operationId: CloudRecording_updateRegistrationQuestions
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        For
        [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings)
        meeting recordings, you can include fields with questions that will be
        shown to registrants when they register to view the recording.


        Use this API to update registration questions that are to be answered by
        users while registering to view a recording.  
         


        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /meetings/{meetingId}/recordings/registrants/status:
    put:
      tags:
        - Cloud Recording
      summary: Update registrant's status
      operationId: CloudRecording_updateRegistrantStatus
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        A registrant can either be approved or denied from viewing the
        [on-demand](https://support.zoom.us/hc/en-us/articles/360000488283-On-demand-Recordings)
        recording. 

        Use this API to update a registrant's status.




        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /meetings/{meetingId}/recordings/settings:
    get:
      tags:
        - Cloud Recording
      summary: Get meeting recording settings
      operationId: CloudRecording_getSettings
      security:
        - openapi_oauth:
            - recording:read:admin
            - recording:read
          openapi_authorization: []
      description: >-
        Retrieves settings applied to a meeting's [Cloud
        Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).  
           
         


        **Scopes:** `recording:read:admin`,`recording:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions: []
        x-macro-scopes:
          - recording:read:admin
          - recording:read
    patch:
      tags:
        - Cloud Recording
      summary: Update meeting recording settings
      operationId: CloudRecording_updateSettings
      security:
        - openapi_oauth:
            - recording:write
            - recording:write:admin
          openapi_authorization: []
      description: >-
        Updates settings applied to a meeting's [Cloud
        Recording](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording).      


        **Scopes:** `recording:write`,`recording:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions: []
        x-macro-scopes:
          - recording:write
          - recording:write:admin
  /meetings/{meetingId}/recordings/{recordingId}:
    delete:
      tags:
        - Cloud Recording
      summary: Delete a meeting recording file
      operationId: CloudRecording_deleteRecording
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        Delete a specific recording file from a meeting.&lt;p
        style=&quot;background-color:#e1f5fe; color:#01579b;
        padding:8px&quot;&gt; &lt;b&gt;Note:&lt;/b&gt; To use this API, you must
        enable the &lt;b&gt;The host can delete cloud recordings&lt;/b&gt;
        setting. You can find this setting in the &lt;b&gt;Recording&lt;/b&gt;
        tab of the &lt;b&gt;Settings&lt;/b&gt; interface in the [Zoom web
        portal](https://zoom.us/).&lt;/p&gt;




        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /meetings/{meetingId}/recordings/{recordingId}/status:
    put:
      tags:
        - Cloud Recording
      summary: Recover a single recording
      operationId: CloudRecording_recoverStatus
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        Zoom allows users to recover recordings from trash for up to 30 days
        from the deletion date. Use this API to recover a single recording file
        from the meeting.  
         


        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /meetings/{meetingUUID}/recordings/status:
    put:
      tags:
        - Cloud Recording
      summary: Recover meeting recordings
      operationId: CloudRecording_recoverRecordingStatus
      security:
        - openapi_oauth:
            - recording:write:admin
            - recording:write
          openapi_authorization: []
      description: >-
        Zoom allows users to recover recordings from trash for up to 30 days
        from the deletion date. Use this API to recover all deleted [Cloud
        Recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording)
        of a specific meeting.  
           
         
        **Prerequisites**:  
         
        * A Pro user with Cloud Recording enabled.


        **Scopes:** `recording:write:admin`,`recording:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - recording:write:admin
          - recording:write
  /users/{userId}/recordings:
    get:
      tags:
        - Cloud Recording
      summary: List all recordings
      operationId: CloudRecording_listRecordings
      security:
        - openapi_oauth:
            - recording:read:admin
            - recording:read
          openapi_authorization: []
      description: >-
        Lists all [cloud
        recordings](https://support.zoom.us/hc/en-us/articles/203741855-Cloud-Recording)
        for a user.  


        For user-level apps, pass the [`me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter.  To access a user's passcode
        protected cloud recording, send the user's [OAuth access
        token](https://developers.zoom.us/docs/integrations/oauth/) as a bearer
        token in the authorization header.  


        Example:  `curl -H "Authorization: Bearer <ACCESS_TOKEN>"
        https://{{base-domain}}/rec/archive/download/xyz`  


        **Prerequisites:**  

        * Must have a Pro or a higher plan.  

        * Must enable Cloud Recording on the user's account.


        **Scopes:** `recording:read:admin`,`recording:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - Recording:Read
        x-macro-scopes:
          - recording:read:admin
          - recording:read
        x-granular-scopes:
          - user:read:list_recordings
          - user:read:list_recordings:admin
          - user:read:list_recordings:master
  /devices:
    get:
      tags:
        - Devices
      summary: List devices
      operationId: Devices_list
      security:
        - openapi_oauth:
            - device:read:admin
            - device:write:admin
          openapi_authorization: []
      description: >-
        This API lets you list devices. 




        **Scopes:** `device:read:admin`,`device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - ZoomRooms:Read
          - ZoomRooms:Edit
        x-macro-scopes:
          - device:read:admin
          - device:write:admin
    post:
      tags:
        - Devices
      summary: Add a new device
      operationId: Devices_createNewDevice
      security:
        - openapi_oauth:
            - device:write:admin
          openapi_authorization: []
      description: >-
        Add a new device to Zoom account. 


        **Scope:** `device:write:admin`   
         
         **[Rate Limit Label](https://developers.zoom.us/docs/api/rest/rate-limits/):** `Medium`

        **Scopes:** `device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - ZoomRooms:Edit
        x-macro-scopes:
          - device:write:admin
  /devices/groups:
    get:
      tags:
        - Devices
      summary: Get zdm group info
      operationId: Devices_listZdmGroupInfo
      security:
        - openapi_oauth:
            - device:read:admin
          openapi_authorization: []
      description: >-
        Get Zoom Device Manager (ZDM) group information for an account.


        **Scopes:** `device:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - ZoomRooms:Read
          - MoileDeviceManagement:Read
        x-macro-scopes:
          - device:read:admin
        x-granular-scopes:
          - device:read:list_groups:admin
          - device:read:list_groups:master
  /devices/zpa/assignment:
    post:
      tags:
        - Devices
      summary: Assign a device to a user or commonarea
      operationId: Devices_assignDeviceZpaAssignment
      security:
        - openapi_oauth:
            - device:write:admin
          openapi_authorization: []
      description: >-
        Assign a device to a user or common area, or move a device to another
        user or common area, or remove a device.


        **Prerequisites:**

        * Device must be enrolled in Zoom Device Management (ZDM).


        **Scopes:** `device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - MobileDeviceManagement:Edit
          - ZoomRooms:Edit
        x-macro-scopes:
          - device:write:admin
        x-granular-scopes:
          - device:write:zpa_device:admin
          - device:write:zpa_device:master
  /devices/zpa/upgrade:
    post:
      tags:
        - Devices
      summary: upgrade zpa os/app
      operationId: Devices_upgradeZpaOsApp
      security:
        - openapi_oauth:
            - device:write:admin
          openapi_authorization: []
      description: >-
        Upgrade ZPA firmware or app by Zoom Device Manager (ZDM) group ID.


        **Scopes:** `device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - ZoomRooms:Edit
          - MobileDeviceManagement:Edit
        x-macro-scopes:
          - device:write:admin
        x-granular-scopes:
          - device:write:zpa_os_or_app:admin
          - device:write:zpa_os_or_app:master
  /devices/zpa/vendors/{vendor}/mac_addresses/{macAddress}:
    delete:
      tags:
        - Devices
      summary: Delete ZPA device by vendor and mac address
      operationId: Devices_removeZpaDeviceByVendorAndMacAddress
      security:
        - openapi_oauth:
            - device:write:admin
          openapi_authorization: []
      description: >-
        Remove a ZPA device from the device manager, by vendor and mac address.


        **Scopes:** `device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - ZoomRooms:Edit
          - MobileDeviceManagement:Edit
        x-macro-scopes:
          - device:write:admin
        x-granular-scopes:
          - device:delete:zpa_device:admin
          - device:delete:zpa_device:master
  /devices/zpa/zdm_groups/{zdmGroupId}/versions:
    get:
      tags:
        - Devices
      summary: Get ZPA version info
      operationId: Devices_getZpaVersionInfo
      security:
        - openapi_oauth:
            - device:read:admin
          openapi_authorization: []
      description: >-
        Get ZPA firmware and app version information that can be upgraded for
        devices.


        **Scopes:** `device:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - ZoomRooms:Read
          - MoileDeviceManagement:Read
        x-macro-scopes:
          - device:read:admin
        x-granular-scopes:
          - device:read:list_zpa_versions:admin
          - device:read:list_zpa_versions:master
  /devices/{deviceId}:
    get:
      tags:
        - Devices
      summary: Get device detail
      operationId: Devices_getDetail
      security:
        - openapi_oauth:
            - device:read:admin
            - device:write:admin
          openapi_authorization: []
      description: >-
        Retrieve a device's details.


        **Scopes:** `device:read:admin`,`device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - ZoomRooms:Read
          - ZoomRooms:Edit
        x-macro-scopes:
          - device:read:admin
          - device:write:admin
    delete:
      tags:
        - Devices
      summary: Delete device
      operationId: Devices_removeDeviceZMD
      security:
        - openapi_oauth:
            - device:write:admin
          openapi_authorization: []
      description: >-
        Delete a device from a Zoom account. 


        **Prerequisites:**

        * Device must be enrolled in ZMD (Zoom Device Management)


        **Scopes:** `device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - MobileDeviceManagement:Edit
        x-macro-scopes:
          - device:write:admin
    patch:
      tags:
        - Devices
      summary: 'Change device '
      operationId: Devices_updateDeviceName
      security:
        - openapi_oauth:
            - device:write:admin
          openapi_authorization: []
      description: >-
        Change device name. 


        **Prerequisites:**

        * Device must be enrolled in ZMD (Zoom Device Management)


        **Scopes:** `device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - ZoomRooms:Edit
        x-macro-scopes:
          - device:write:admin
  /devices/{deviceId}/assignment:
    patch:
      tags:
        - Devices
      summary: Change device association
      operationId: Devices_changeDeviceAssociation
      security:
        - openapi_oauth:
            - device:write:admin
          openapi_authorization: []
      description: >-
        This Device API lets you change device association from one Zoom Room to
        another. 


        **Prerequisites:**

        * Device must be enrolled in ZMD (Zoom Device Management) 




        **Scopes:** `device:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - device:write:admin
  /h323/devices:
    get:
      tags:
        - H323 Devices
      summary: List H.323/SIP devices
      operationId: H323Devices_listDevices
      security:
        - openapi_oauth:
            - h323:read:admin
          openapi_authorization: []
      description: >-
        A H.323 or SIP device can make a video call to a [Room
        Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)
        to join a Zoom cloud meeting. A Room Connector can also call out to a
        H.323 or SIP device to join a Zoom cloud meeting. Use this API to list
        all H.323/SIP Devices on a Zoom account.  
           
         


        **Scopes:** `h323:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - h323:read:admin
    post:
      tags:
        - H323 Devices
      summary: Create a H.323/SIP device
      operationId: H323Devices_createDevice
      security:
        - openapi_oauth:
            - h323:write:admin
          openapi_authorization: []
      description: >-
        A H.323 or SIP device can make a video call to a [Room
        Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)
        to join a Zoom cloud meeting. A Room Connector can also call out to a
        H.323 or SIP device to join a Zoom cloud meeting. Use this API to add a
        H.323/SIP device to your Zoom account  
           
         


        **Scopes:** `h323:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - h323:write:admin
  /h323/devices/{deviceId}:
    delete:
      tags:
        - H323 Devices
      summary: Delete a H.323/SIP device
      operationId: H323Devices_deleteDevice
      security:
        - openapi_oauth:
            - h323:write:admin
          openapi_authorization: []
      description: >-
        A H.323 or SIP device can make a video call to a [Room
        Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)
        to join a Zoom cloud meeting. A Room Connector can also call out to a
        H.323 or SIP device to join a Zoom cloud meeting. Use this API to delete
        a H.323/SIP device from your Zoom account.  
           
         


        **Scopes:** `h323:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - h323:write:admin
    patch:
      tags:
        - H323 Devices
      summary: Update a H.323/SIP device
      operationId: H323Devices_updateDeviceInfo
      security:
        - openapi_oauth:
            - h323:write:admin
          openapi_authorization: []
      description: >-
        A H.323 or SIP device can make a video call to a [Room
        Connector](https://support.zoom.us/hc/en-us/articles/201363273-Getting-Started-With-H-323-SIP-Room-Connector)
        to join a Zoom cloud meeting. A Room Connector can also call out to a
        H.323 or SIP device to join a Zoom cloud meeting. Use this API to edit
        information of a H.323/SIP device from your Zoom account.  
           
         


        **Scopes:** `h323:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - h323:write:admin
  /live_meetings/{meetingId}/chat/messages/{messageId}:
    delete:
      tags:
        - Meetings
      summary: Delete a live meeting message
      operationId: Meetings_deleteMeetingChatMessage
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      description: >-
        Delete a message in a live meeting, based on ID. 


        **Prerequisites:** 

        * Have Zoom enable the DLP for the in-meeting chat feature to use this
        API.


        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions: []
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
    patch:
      tags:
        - Meetings
      summary: Update a live meeting message
      operationId: Meetings_updateMessage
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      description: >-
        Update a message in a live meeting, based on ID. **Prerequisites:** *
        Have Zoom enable the DLP for the in-meeting chat feature to use this
        API.


        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
  /live_meetings/{meetingId}/events:
    patch:
      tags:
        - Meetings
      summary: Use in-meeting controls
      operationId: Meetings_controlInMeetingFeatures
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
            - meeting:master
          openapi_authorization: []
      description: >-
        Control
        [in-meeting](https://support.zoom.us/hc/en-us/articles/360021921032-In-Meeting-Controls)
        features. In-meeting controls include starting and stopping a recording,
        pausing and resuming a recording, and inviting participants. 


        **Note:** This API's recording control only works for cloud recordings.
        It does **not** work for local recordings. 


        **Prerequisites:**

        * The meeting **must** be a live meeting **except** inviting
        participants to the meeting through [call out (phone)/(room system)]. 

        * Recording control: [Cloud
        recording](https://support.zoom.us/hc/en-us/articles/360060231472-Enabling-cloud-recording)
        must be enabled on the account. 

        * The user calling this API must be the host or an alternative meeting
        host.

         

        **Scopes:** `meeting:write`,`meeting:write:admin`,`meeting:master`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
          - meeting:master
  /meetings/meeting_summaries:
    get:
      tags:
        - Meetings
      summary: List meeting summaries of an account
      operationId: Meetings_listMeetingSummaries
      security:
        - openapi_oauth:
            - meeting_summary:read:admin
          openapi_authorization: []
      description: >-
        Generates a list of all meeting summaries for an account.


        **Prerequisites**

        * Host user type must be Pro or higher plan.

        * The Meeting Summary with AI Companion feature enabled in the host's
        account.

        * E2ee meetings do not have summary feature enabled.


        **Scopes:** `meeting_summary:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - SmartMeetingSummaryMgt:Read
        x-macro-scopes:
          - meeting_summary:read:admin
        x-granular-scopes:
          - meeting:read:list_summaries:admin
  /meetings/{meetingId}:
    get:
      tags:
        - Meetings
      summary: Get a meeting
      operationId: Meetings_getDetails
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        Retrieve the given meeting's details. 
         
         


        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
        x-granular-scopes:
          - meeting:read:meeting
          - meeting:read:meeting:admin
    delete:
      tags:
        - Meetings
      summary: Delete a meeting
      operationId: Meetings_removeMeeting
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Delete a meeting.  
           
         


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
    patch:
      tags:
        - Meetings
      summary: Update a meeting
      operationId: Meetings_updateDetails
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      description: >-
        Update meeting details.


        **Note** 

        * The `start_time` value **must** be a future date. If the value is
        omitted or a date is in the past, the API ignores this value and does
        **not** update any recurring meetings. 

        * The `recurrence` object is **required**.

        * This API has a rate limit of **100 requests per day**. You can update
        a meeting for a maximum of **100 times within a 24-hour period**. 





        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
  /meetings/{meetingId}/batch_polls:
    post:
      tags:
        - Meetings
      summary: Perform batch poll creation
      operationId: Meetings_createBatchPolls
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Polls allow the meeting host to survey attendees. Create batch
        [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        for a meeting.  
           
         

        **Prerequisites**:  
         
        * Host user type must be **Pro** or higher plan.

        * Polling feature must be enabled in the host's account.

        * Meeting must be a scheduled meeting. Instant meetings do not have
        polling features enabled.


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/batch_registrants:
    post:
      tags:
        - Meetings
      summary: Perform batch registration
      operationId: Meetings_batchRegistrantsCreate
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      description: >-
        Register up to 30 registrants at once for a meeting that requires
        [registration](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).   
         

        **Prerequisites:**  
         
        * The meeting host must be a Licensed user.

        * The meeting must require registration and should be of type `2`, i.e.,
        they should be scheduled meetings. Instant meetings and Recurring
        meetings are not supported by this API.  
           
         


        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
  /meetings/{meetingId}/invitation:
    get:
      tags:
        - Meetings
      summary: Get meeting invitation
      operationId: Meetings_getInvitationNote
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        Retrieve the meeting invitation note for a specific meeting.


        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
  /meetings/{meetingId}/invite_links:
    post:
      tags:
        - Meetings
      summary: Create meeting's invite links
      operationId: Meetings_createInviteLinks
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Create a batch of invitation links for a meeting.




        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/jointoken/live_streaming:
    get:
      tags:
        - Meetings
      summary: Get a meeting's join token for live streaming
      operationId: Meetings_getJoinToken
      security:
        - openapi_oauth:
            - meeting_token:read:admin:live_streaming
            - meeting_token:read:live_streaming
          openapi_authorization: []
      description: >-
        Get a meeting's join token to allow live streaming. The join token
        allows a recording bot implemented using Zoom meeting SDK to connect to
        a Zoom meeting &quot;hosted by the issuer of the token&quot;, and can
        call the streaming method automatically. It supports both regular live
        streaming, and raw streaming. 


        **Prerequisites:** 

        * A Pro or higher plan for the meeting host. 

        * The **Allow livestreaming of meetings** user setting enabled in the
        Zoom web portal.


        **Scopes:**
        `meeting_token:read:admin:live_streaming`,`meeting_token:read:live_streaming`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting_token:read:admin:live_streaming
          - meeting_token:read:live_streaming
  /meetings/{meetingId}/jointoken/local_archiving:
    get:
      tags:
        - Meetings
      summary: Get a meeting's archive token for local archiving
      operationId: Meetings_getMeetingArchiveTokenForLocalArchiving
      security:
        - openapi_oauth:
            - meeting_token:read:admin:local_archiving
          openapi_authorization: []
      description: >-
        Get a meeting's archive token to allow local archiving. The archive
        token allows a meeting SDK app or bot to get archive permission to
        access the meeting's raw audio and video media stream in real-time. 


        **Prerequisites:** 

        * A Pro or higher plan for the meeting host. 

        * The **Archive meetings and webinars** account setting enabled in the
        Zoom web portal.


        **Scopes:** `meeting_token:read:admin:local_archiving`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting_token:read:admin:local_archiving
  /meetings/{meetingId}/jointoken/local_recording:
    get:
      tags:
        - Meetings
      summary: Get a meeting's join token for local recording
      operationId: Meetings_getJoinTokenLocalRecording
      security:
        - openapi_oauth:
            - meeting_token:read:local_recording
            - meeting_token:read:admin:local_recording
          openapi_authorization: []
      description: >-
        Get a meeting's join token to allow for local recording. The join token
        lets a recording bot implemented using Zoom Meeting SDK to connect to a
        Zoom meeting. The recording bot can then automatically start locally
        recording. This supports both regular and raw local recording types. 


        **Prerequisites:** 

        * The **Local recording** user setting enabled in the Zoom web portal.


        **Scopes:**
        `meeting_token:read:local_recording`,`meeting_token:read:admin:local_recording`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - meeting_token:read:local_recording
          - meeting_token:read:admin:local_recording
        x-granular-scopes:
          - meeting:read:local_recording_token
          - meeting:read:local_recording_token:admin
  /meetings/{meetingId}/livestream:
    get:
      tags:
        - Meetings
      summary: Get livestream details
      operationId: Meetings_getLivestreamDetails
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        Zoom allows users to [livestream a
        meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)
        to a custom platform. Get a meeting's livestream configuration details
        such as Stream URL, Stream Key and Page URL.  
           
         
        **Prerequisites:**  
         
        * Meeting host must be a licensed user with a Pro or higher plan.  
         
        * Live streaming details must have been
        [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)
        for the meeting.  
           
         


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
    patch:
      tags:
        - Meetings
      summary: Update a livestream
      operationId: Meetings_updateLivestream
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Update a meeting's livestream information. Zoom allows users to
        [livestream a
        meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)
        to a custom platform.


        **Prerequisites:** 

        * Meeting host must have a Pro license.


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/livestream/status:
    patch:
      tags:
        - Meetings
      summary: Update Live Stream Status
      operationId: Meetings_livestreamStatusUpdate
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Zoom allows users to [livestream a
        meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)
        to a custom platform. Update the status of a meeting's livestream.  
           
         
        **Prerequisites:**  
         
        * Meeting host must have a Pro license.  
         


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/meeting_summary:
    get:
      tags:
        - Meetings
      summary: Get a meeting summary
      operationId: Meetings_getMeetingSummary
      security:
        - openapi_oauth:
            - meeting_summary:read:admin
            - meeting_summary:read
          openapi_authorization: []
      description: >-
        Displays information about a meeting summary.


        **Prerequisites**:

        * Host user type must be Pro or higher plan.

        * The Meeting Summary with AI Companion feature enabled in the host's
        account.

        * E2ee meetings do not have summary feature enabled.


        **Scopes:** `meeting_summary:read:admin`,`meeting_summary:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - SmartMeetingSummaryMgt:Read
        x-macro-scopes:
          - meeting_summary:read:admin
          - meeting_summary:read
        x-granular-scopes:
          - meeting:read:summary
          - meeting:read:summary:admin
  /meetings/{meetingId}/polls:
    get:
      tags:
        - Meetings
      summary: List meeting polls
      operationId: Meetings_listMeetingPolls
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        Polls allow the meeting host to survey attendees. List all
        [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        of a meeting.  
           
         

        **Prerequisites**:  
         
        * Host user type must be **Pro** or higher plan.

        * Meeting must be a scheduled meeting. Instant meetings do not have
        polling features enabled.


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
    post:
      tags:
        - Meetings
      summary: Create a meeting poll
      operationId: Meetings_createPoll
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Polls allow the meeting host to survey attendees. Create a
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        for a meeting.  
           
         

        **Prerequisites**:  
         
        * Host user type must be **Pro** or higher plan.

        * Polling feature must be enabled in the host's account.

        * Meeting must be a scheduled meeting. Instant meetings do not have
        polling features enabled.


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/polls/{pollId}:
    get:
      tags:
        - Meetings
      summary: Get a meeting poll
      operationId: Meetings_getPoll
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        Polls allow the meeting host to survey attendees. Retrieve information
        about a specific meeting
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).  
           
         


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
    put:
      tags:
        - Meetings
      summary: Update a meeting poll
      operationId: Meetings_updateMeetingPoll
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Polls allow the meeting host to survey attendees. Update information of
        a specific meeting
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)  
           
         


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
    delete:
      tags:
        - Meetings
      summary: Delete a meeting poll
      operationId: Meetings_pollDelete
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Polls allow the meeting host to survey attendees. Delete a meeting
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).  
         
        **Prerequisites**:  
         
        * Host user type must be **Pro**.

        * Polling feature should be enabled in the host's account.

        * Meeting must be a scheduled meeting. Instant meetings do not have
        polling features enabled.


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/registrants:
    get:
      tags:
        - Meetings
      summary: List meeting registrants
      operationId: Meetings_listRegistrants
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        A host or a user with admin permission can require [registration for a
        Zoom
        meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).
        List users that have registered for a meeting.  
           
         


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
    post:
      tags:
        - Meetings
      summary: Add a meeting registrant
      operationId: Meetings_addRegistrant
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Create and submit a user's registration to a meeting. See [Customizing
        webinar
        registration](https://support.zoom.us/hc/en-us/articles/202835649-Customizing-webinar-registration)
        for details on how to set the requirements for these fields. Note that
        there is a maximum limit of 4,999 registrants per meeting and users will
        see an error if the meeting's capacity is reached. 

         **Prerequisites:** 
        * The host must be a **Licensed** user type.


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/registrants/questions:
    get:
      tags:
        - Meetings
      summary: 'List registration questions '
      operationId: Meetings_listRegistrationQuestions
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        List registration questions that will be displayed to users while
        [registering for a
        meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).  
         



        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
    patch:
      tags:
        - Meetings
      summary: Update registration questions
      operationId: Meetings_updateRegistrationQuestions
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      description: >-
        Update registration questions that will be displayed to users while
        [registering for a
        meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).  
           
         


        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
  /meetings/{meetingId}/registrants/status:
    put:
      tags:
        - Meetings
      summary: Update registrant's status
      operationId: Meetings_updateRegistrantStatus
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Update a meeting registrant's status by either approving, cancelling or
        denying a registrant from joining the meeting.  
           
         


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/registrants/{registrantId}:
    get:
      tags:
        - Meetings
      summary: Get a meeting registrant
      operationId: Meetings_getRegistrantDetails
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        Retrieve details on a specific user who has registered for the meeting.
        A host or a user with administrative permissions can require
        [registration for Zoom
        meetings](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).


        **Prerequisites:** 

        * The account must have a Meeting plan


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
    delete:
      tags:
        - Meetings
      summary: Delete a meeting registrant
      operationId: Meetings_deleteRegistrant
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Delete a meeting registrant.  
           
         


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/sip_dialing:
    post:
      tags:
        - Meetings
      summary: Get a meeting SIP URI with Passcode
      operationId: Meetings_getSipUriWithPasscode
      security:
        - openapi_oauth:
            - meeting:write:sip_dialing
            - meeting:write:admin:sip_dialing
          openapi_authorization: []
      description: >-
        Get a meeting's SIP URI.  The URI consists of the meeting ID, (optional,
        user-supplied) passcode and participant identifier code.  The API return
        data also includes additional fields to indicate whether the API caller
        has a valid Cloud Room Connector subscription, the participant
        identifier code from the URI, and the SIP URI validity period (in
        seconds). 




        **Scopes:**
        `meeting:write:sip_dialing`,`meeting:write:admin:sip_dialing`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:write:sip_dialing
          - meeting:write:admin:sip_dialing
  /meetings/{meetingId}/status:
    put:
      tags:
        - Meetings
      summary: Update meeting status
      operationId: Meetings_updateMeetingStatus
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Update the status of a meeting.  
           
         


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/survey:
    get:
      tags:
        - Meetings
      summary: Get a meeting survey
      operationId: Meetings_getMeetingSurvey
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        Display information about a [meeting
        survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). 
        **Prerequisites:** * The host has a **Pro** license. * The [**Meeting
        Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys)
        feature is enabled on the host's account. * The meeting must be a
        scheduled meeting. Instant meetings do not have survey features enabled.


        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
    delete:
      tags:
        - Meetings
      summary: Delete a meeting survey
      operationId: Meetings_deleteMeetingSurvey
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      description: >-
        Delete a [meeting
        survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). 

         **Prerequisites:** 
        * The host must be a **Pro** user type. 

        * The [**Meeting
        Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys)
        feature enabled in the host's account. 

        * The meeting must be a scheduled meeting. Instant meetings do not have
        survey features enabled.


        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
    patch:
      tags:
        - Meetings
      summary: Update a meeting survey
      operationId: Meetings_updateSurvey
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Update a [meeting
        survey](https://support.zoom.us/hc/en-us/articles/4404969060621-Post-meeting-survey-and-reporting). 
        **Prerequisites:** * The host must be a **Pro** user type. * The
        [**Meeting
        Survey**](https://support.zoom.us/hc/en-us/articles/4404939095053-Enabling-meeting-surveys)
        feature is enabled in the host's account. * The meeting must be a
        scheduled meeting. Instant meetings do not have survey features enabled.


        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /meetings/{meetingId}/token:
    get:
      tags:
        - Meetings
      summary: Get meeting's token
      operationId: Meetings_getMeetingToken
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        Get a meeting's [closed caption token (caption
        URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service).
        This token lets you use a third-party service to stream text to their
        closed captioning software to the Zoom meeting. 


        **Prerequisites:** 

        * The **Closed captioning** setting enabled in the Zoom web portal. 

        * The **Allow use of caption API Token to integrate with 3rd-party
        Closed Captioning services** setting enabled.


        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
  /past_meetings/{meetingId}:
    get:
      tags:
        - Meetings
      summary: Get past meeting details
      operationId: Meetings_getDetails
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        Get information about a past meeting. 

         

        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
  /past_meetings/{meetingId}/instances:
    get:
      tags:
        - Meetings
      summary: List past meeting instances
      operationId: Meetings_listPastMeetingInstances
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        Return a list of past meeting instances. 

         

        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
  /past_meetings/{meetingId}/participants:
    get:
      tags:
        - Meetings
      summary: Get past meeting participants
      operationId: Meetings_getPastMeetingParticipants
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        Retrieve information on participants from a past meeting. Note the API
        doesn't return results if there's only one participant in a meeting.  
           
         
        **Prerequisites:**  
         
        * Paid account on a Pro or higher plan.

          
            
           **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
        x-granular-scopes:
          - meeting:read:list_past_participants
          - meeting:read:list_past_participants:admin
  /past_meetings/{meetingId}/polls:
    get:
      tags:
        - Meetings
      summary: List past meeting's poll results
      operationId: Meetings_listPastMeetingPolls
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        [Polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        allow the meeting host to survey attendees. List poll results of a
        meeting.  
           
         

        **Prerequisites**:  
         
        * Host user type must be **Pro**.

        * Meeting must be a scheduled meeting. Instant meetings do not have
        polling features enabled.


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
  /past_meetings/{meetingId}/qa:
    get:
      tags:
        - Meetings
      summary: List past meetings' Q&A
      operationId: Meetings_listPastMeetingQA
      security:
        - openapi_oauth:
            - meeting:read:admin
            - meeting:read
          openapi_authorization: []
      description: >-
        The question &amp; answer (Q&amp;A) feature for Zoom Meetings lets
        attendees ask questions during a meeting and lets the other attendees
        answer those questions.  
         
        List Q&amp;A of a specific meeting.


        **Prerequisites:**  
         
        * 


        **Scopes:** `meeting:read:admin`,`meeting:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:read:admin
          - meeting:read
  /users/{userId}/meeting_templates:
    get:
      tags:
        - Meetings
      summary: List meeting templates
      operationId: Meetings_listMeetingTemplates
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        List available [meeting
        templates](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates)
        for a user. For user-level apps, pass [the `me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter.




        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
    post:
      tags:
        - Meetings
      summary: Create a meeting template from an existing meeting
      operationId: Meetings_createTemplateFromMeeting
      security:
        - openapi_oauth:
            - meeting:write:admin
            - meeting:write
          openapi_authorization: []
      description: >-
        Create a meeting template from an existing meeting. 




        **Scopes:** `meeting:write:admin`,`meeting:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - meeting:write:admin
          - meeting:write
  /users/{userId}/meetings:
    get:
      tags:
        - Meetings
      summary: List meetings
      operationId: Meetings_listHostScheduled
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        List a meeting host user's scheduled meetings. For user-level apps, pass
        [the `me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter. 


        **Note** 

        * This API **only** supports scheduled meetings. This API does not
        return information about instant meetings. 

        * This API only returns a user's [unexpired
        meetings](https://support.zoom.us/hc/en-us/articles/201362373-Meeting-ID#h_c73f9b08-c1c0-4a1a-b538-e01ebb98e844). 

         

        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
        x-granular-scopes:
          - meeting:read:list_meetings
          - meeting:read:list_meetings:admin
    post:
      tags:
        - Meetings
      summary: Create a meeting
      operationId: Meetings_createMeeting
      security:
        - openapi_oauth:
            - meeting:write
            - meeting:write:admin
          openapi_authorization: []
      description: >-
        [Create a
        meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings)
        for a user. For user-level apps, pass [the `me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter.


        * A meeting's `start_url` value is the URL a host or an alternative host
        can use to start a meeting. The expiration time for the `start_url`
        value is **two hours** for all regular users.

        * For `custCreate` meeting hosts (users created with the `custCreate`
        parameter via the [**Create
        users**](https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/userCreate)
        API), the expiration time of the `start_url` parameter is **90 days**
        from the generation of the `start_url`.


        **Note:** 


        For security reasons, the recommended way to programmatically get the
        updated `start_url` value after expiry is to call the [**Get a
        meeting**](/api-reference/zoom-api/methods#operation/meeting) API. Refer
        to the `start_url` value in the response. 

         **100 requests per day**. The rate limit is applied against the `userId` of the **meeting host** used to make the request.

        **Scopes:** `meeting:write`,`meeting:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - meeting:write
          - meeting:write:admin
        x-granular-scopes:
          - meeting:write:meeting
          - meeting:write:meeting:admin
  /users/{userId}/upcoming_meetings:
    get:
      tags:
        - Meetings
      summary: List upcoming meetings
      operationId: Meetings_listUpcomingMeetings
      security:
        - openapi_oauth:
            - meeting:read
            - meeting:read:admin
          openapi_authorization: []
      description: >-
        List a Zoom user's upcoming meetings. For user-level apps, pass [the
        `me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter.


        **Note**

        * This API includes the meetings that Zoom users schedule and the
        meetings they are invited to join.

        * This API **only** includes upcoming meetings within the next 24 hours.


        **Scopes:** `meeting:read`,`meeting:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - meeting:read
          - meeting:read:admin
        x-granular-scopes:
          - meeting:read:list_upcoming_meetings
          - meeting:read:list_upcoming_meetings:admin
  /users/{userId}/pac:
    get:
      tags:
        - PAC
      summary: List a user's PAC accounts
      operationId: Pac_listAccounts
      security:
        - openapi_oauth:
            - pac:read:admin
            - pac:read
          openapi_authorization: []
      description: >-
        Retrieve a list of a user's [personal audio conference
        (PAC)](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference)
        accounts. For user-level apps, pass [the `me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter. 

         PAC allows Pro or higher account holders to host meetings through PSTN (phone dial-in) only. 

         **Prerequisites** 
        * A Pro or higher plan with an [Audio
        Conferencing](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference)
        subscription. 

        * The [**Personal Audio
        Conference**](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference#h_01F5BPM447M6QDJXX50RSFXKJ3)
        setting enabled in the user's profile.


        **Scopes:** `pac:read:admin`,`pac:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - pac:read:admin
          - pac:read
  /report/activities:
    get:
      tags:
        - Reports
      summary: Get sign In / sign out activity report
      operationId: Reports_listSignInSignOutActivities
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a list of sign in / sign out activity logs
        [report](https://support.zoom.us/hc/en-us/articles/201363213-Getting-Started-with-Reports)
        of users under a Zoom account.  
         
        **Prerequisites**  
         
        * Pro or higher plan.  
         


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:user_activities:admin
  /report/billing:
    get:
      tags:
        - Reports
      summary: Get billing reports
      operationId: Reports_getBillingDepartmentReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Get department billing reports of a Zoom account.


        **Prerequisites:**  
         
        * Pro or a higher account with Department Billing option enabled.
        Contact Zoom Support team for details.




        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:billing:admin
  /report/billing/invoices:
    get:
      tags:
        - Reports
      summary: Get billing invoice reports
      operationId: Reports_getBillingInvoices
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Get department billing invoices reports for a specific billing period.
        Provide the `billing_id` of the billing period for which you would like
        to retrieve the invoices for. This ID can be retrieved from **Get
        Billing Reports** API. 


        **Prerequisites:**  
         
        * Pro or a higher account with Department Billing option enabled.
        Contact the Zoom Support team to enable this feature.




        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:billing_invoice:admin
  /report/cloud_recording:
    get:
      tags:
        - Reports
      summary: Get cloud recording usage report
      operationId: Reports_getCloudRecordingUsageReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve cloud recording usage report for a specified period. You can
        only get cloud recording reports that is one day earlier than the
        current date and for the most recent period of 6 months. The date gap
        between from and to dates should be smaller or equal to 30 days.   
         
        **Prerequisites**  
         
        * Pro or higher plan.  
         


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-macro-scopes:
          - report:read:admin
  /report/daily:
    get:
      tags:
        - Reports
      summary: Get daily usage report
      operationId: Reports_getDailyUsageReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve daily report to access the account-wide usage of Zoom services
        for each day in a given month. It lists the number of new users,
        meetings, participants, and meeting minutes.  
         
        **Prerequisites**  
         
        * Pro or higher plan.  
         


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-macro-scopes:
          - report:read:admin
  /report/meetings/{meetingId}:
    get:
      tags:
        - Reports
      summary: Get meeting detail reports
      operationId: Reports_getMeetingDetailReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Get a detailed report for a past meeting.   
         
        **Prerequisites:**  
         
        * Pro or a higher plan.  
         
         

        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:meeting:admin
  /report/meetings/{meetingId}/participants:
    get:
      tags:
        - Reports
      summary: Get meeting participant reports
      operationId: Reports_getMeetingParticipantReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Return a report of a past meeting with two or more participants,
        including the host. To return a report for past meeting with only
        **one** participant, use the [**List meeting
        participants**](https://developers.zoom.us) API. 


        **Note:** 


        This API may return empty values for participants' `user_name`,
        `ip_address`, `location`, and `email` responses when the account calling
        this API: 

        * Does **not** have a signed HIPAA business associate agreement (BAA). 

        * Is a [**legacy** HIPAA BAA account](https://developers.zoom.us). 


        **Prerequisites:** 

        * A Pro or a higher plan.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:list_meeting_participants:admin
  /report/meetings/{meetingId}/polls:
    get:
      tags:
        - Reports
      summary: Get meeting poll reports
      operationId: Reports_getMeetingPollReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Use this API to get a report of
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        results for a past meeting. 

         **Prerequisites:** 
        * A Pro or a higher plan.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:list_meeting_polls:admin
  /report/meetings/{meetingId}/qa:
    get:
      tags:
        - Reports
      summary: Get meeting Q&A report
      operationId: Reports_getMeetingQaReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a report on questions asked and answered by participants from
        past meetings.   
           


         
        **Prerequisites:**  
         
        * Pro plan or higher.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:meeting_qna:admin
  /report/meetings/{meetingId}/survey:
    get:
      tags:
        - Reports
      summary: Get meeting survey report
      operationId: Reports_getMeetingSurveyReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a report on past [meeting
        survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559).  
           
         
        **Prerequisites:**  
         
        * Pro or a higher plan.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:meeting_survey:admin
  /report/operationlogs:
    get:
      tags:
        - Reports
      summary: Get operation logs report
      operationId: Reports_getOperationLogsReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        The [Operations
        Logs](https://support.zoom.us/hc/en-us/articles/360032748331-Operation-Logs)
        report allows you to audit admin and user activity, such as adding a new
        user, changing account settings, and deleting recordings.  
         
        Use this API to retrieve operation logs report for a specified period of
        time.  
         
        **Prerequisites:**  
         
        * Pro or higher plan.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:operation_logs:admin
  /report/telephone:
    get:
      tags:
        - Reports
      summary: Get telephone reports
      operationId: Reports_getTelephoneReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        The [telephone
        report](https://support.zoom.us/hc/en-us/articles/206514816-Telephone-reports)
        allows you to view who dialed into meetings via phone (Audio
        Conferencing or SIP Connected Audio) and which number they dialed into
        and other details. Use this API to get telephone report for a specified
        period of time.


        **Prerequisites:**  
         
        * Pro or higher plan.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:telephone:admin
  /report/upcoming_events:
    get:
      tags:
        - Reports
      summary: Get upcoming events report
      operationId: Reports_listUpcomingEventsReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Use this API to list upcoming meeting and/or webinar events within a
        specified period of time. The report's time range is limited to one
        month.


        **Prerequisites:** 

        * A Pro or higher plan


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:upcoming_meetings_webinars:admin
  /report/users:
    get:
      tags:
        - Reports
      summary: Get active/inactive host reports
      operationId: Reports_getActiveInactiveHostReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a host report for a specified period of time within the last
        six months.  

        The report time range is limited to a month. 


        You can specify the type of report and date range using the query
        parameters.  



        * The **Active Hosts** report displays a list of meetings, participants,
        and meeting minutes.

        An **active host** is defined as any user who has hosted at least one
        meeting during the during the month specified in the `from` and `to`
        range.



        * The **Inactive Hosts** report pulls a list of users who were not
        active during a specific period of time.   

        An **inactive host** is defined as any user who has not hosted any
        meetings during the specified period of time for the report. to be
        inactive.  




         
         
         
        **Prerequisites:**  
         
        * Pro or higher plan.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:list_users:admin
  /report/users/{userId}/meetings:
    get:
      tags:
        - Reports
      summary: Get meeting reports
      operationId: Reports_getMeetingReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve
        [report](https://support.zoom.us/hc/en-us/articles/216378603-Meeting-Reporting)
        on past meetings and webinars for a specified time period. The time
        range for the report is limited to a month and the month must fall
        within the past six months.


        Meetings and webinars are returned only if they have two or more unique
        participants.    
           
         
        **Prerequisites:**  
         
        * Pro or higher plan.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:user:admin
  /report/webinars/{webinarId}:
    get:
      tags:
        - Reports
      summary: Get webinar detail reports
      operationId: Reports_getWebinarDetailsReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a
        [report](https://support.zoom.us/hc/en-us/articles/201393719-Webinar-Reporting)
        containing past webinar details.    
           
         
        **Prerequisites:**  
         
        * Pro or higher plan with Webinar add-on.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:webinar:admin
  /report/webinars/{webinarId}/participants:
    get:
      tags:
        - Reports
      summary: Get webinar participant reports
      operationId: Reports_webinarParticipantsList
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Get a detailed report on each webinar attendee. You can get webinar
        participant reports for the last 6 months. 

         **Prerequisites:** 
        * A Pro or a higher plan with Webinar add-on enabled.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:list_webinar_participants:admin
  /report/webinars/{webinarId}/polls:
    get:
      tags:
        - Reports
      summary: Get webinar poll reports
      operationId: Reports_getWebinarPollReports
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a report on past [webinar
        polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).  
           
         
        **Prerequisites:**  
         
        * Pro or a higher plan with Webinar add-on enabled.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Heavy`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:list_webinar_polls:admin
  /report/webinars/{webinarId}/qa:
    get:
      tags:
        - Reports
      summary: Get webinar Q&A report
      operationId: Reports_getWebinarQAReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a report on questions asked by participants and answered by
        panelists, co-hosts and hosts from past webinars.   


           
         
        **Prerequisites:**  
         
        * Pro or a higher plan with the Webinar add-on enabled.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:webinar_qna:admin
  /report/webinars/{webinarId}/survey:
    get:
      tags:
        - Reports
      summary: Get webinar survey report
      operationId: Reports_getWebinarSurveyReport
      security:
        - openapi_oauth:
            - report:read:admin
          openapi_authorization: []
      description: >-
        Retrieve a report on past [webinar
        survey](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0057559).  
           
         
        **Prerequisites:**  
         
        * Pro or a higher plan with Webinar add-on enabled.


        **Scopes:** `report:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - UsageReport:Read
        x-macro-scopes:
          - report:read:admin
        x-granular-scopes:
          - report:read:webinar_survey:admin
  /sip_phones:
    get:
      tags:
        - SIP Phone
      summary: List SIP phones
      operationId: SipPhone_list
      security:
        - openapi_oauth:
            - sip_phone:read:admin
          openapi_authorization: []
      description: >-
        Zoom's Phone System Integration (PSI), also referred as SIP phones,
        enables an organization to leverage the Zoom client to complete a
        softphone registration to supported premise based PBX system. End users
        will have the ability to have softphone functionality within a single
        client while maintaining a comparable interface to Zoom Phone. Use this
        API to list SIP phones on an account.  
           
         
        **Prerequisites**:

        * Currently only supported on Cisco and Avaya PBX systems. 

        * User must enable SIP Phone Integration by contacting the
        [Sales](https://zoom.us/contactsales) team.  
          

        **Scopes:** `sip_phone:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - sip_phone:read:admin
    post:
      tags:
        - SIP Phone
      summary: Enable SIP phone
      operationId: SipPhone_enableUserSipPhone
      security:
        - openapi_oauth:
            - sip_phone:write:admin
          openapi_authorization: []
      description: >-
        Zoom's Phone System Integration (PSI), also referred as SIP phones,
        enables an organization to leverage the Zoom client to complete a
        softphone registration to supported premise based PBX system. End users
        will have the ability to have softphone functionality within a single
        client while maintaining a comparable interface to Zoom Phone. Use this
        API to enable a user to use SIP phone.  
           
         
        **Prerequisites**:

        * Currently only supported on Cisco and Avaya PBX systems. 

        * The account owner or account admin must first enable SIP Phone
        Integration by contacting the [Sales](https://zoom.us/contactsales)
        team.  
          

        **Scopes:** `sip_phone:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - sip_phone:write:admin
  /sip_phones/{phoneId}:
    delete:
      tags:
        - SIP Phone
      summary: Delete SIP phone
      operationId: SipPhone_deletePhone
      security:
        - openapi_oauth:
            - sip_phone:write:admin
          openapi_authorization: []
      description: >-
        Use this API to delete a Zoom account's SIP phone. 

         **Prerequisites**: 
        * Currently only supported on Cisco and Avaya PBX systems. 

        * The user must enable **SIP Phone Integration** by contacting the [Zoom
        Sales](https://zoom.us/contactsales) team.


        **Scopes:** `sip_phone:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - sip_phone:write:admin
    patch:
      tags:
        - SIP Phone
      summary: Update SIP phone
      operationId: SipPhone_updateSpecificPhone
      security:
        - openapi_oauth:
            - sip_phone:write:admin
          openapi_authorization: []
      description: >-
        Zoom's Phone System Integration (PSI), also referred as SIP phones,
        enables an organization to leverage the Zoom client to complete a
        softphone registration to supported premise based PBX system. End users
        will have the ability to have softphone functionality within a single
        client while maintaining a comparable interface to Zoom Phone. Use this
        API to update information of a specific SIP Phone on a Zoom account.  
           
         
        **Prerequisites**:

        * Currently only supported on Cisco and Avaya PBX systems. 

        * The account owner or account admin must first enable SIP Phone
        Integration by contacting the [Sales](https://zoom.us/contactsales)
        team.  
          

        **Scopes:** `sip_phone:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - sip_phone:write:admin
  /tsp:
    get:
      tags:
        - TSP
      summary: Get account's TSP information
      operationId: Tsp_getAccountInfo
      security:
        - openapi_oauth:
            - tsp:read:admin
          openapi_authorization: []
      description: >-
        Get information on Telephony Service Provider on an account level.  
           
         
        **Prerequisites:**  
         
        * A Pro or a higher plan.


        **Scopes:** `tsp:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tsp:read:admin
    patch:
      tags:
        - TSP
      summary: Update account's TSP information
      operationId: Tsp_updateAccountTspInformation
      security:
        - openapi_oauth:
            - tsp:write:admin
          openapi_authorization: []
      description: >-
        Update information of the Telephony Service Provider set up on an
        account.  
         
        **Prerequisites**:  
         
        TSP account option should be enabled.  
         


        **Scopes:** `tsp:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tsp:write:admin
  /users/{userId}/tsp:
    get:
      tags:
        - TSP
      summary: List user's TSP accounts
      operationId: Tsp_listUserTspAccounts
      security:
        - openapi_oauth:
            - tsp:read:admin
            - tsp:read
          openapi_authorization: []
      description: >-
        A user can have a maximum of two TSP accounts. Use this API to list all
        TSP accounts of a user.  
           
         


        **Scopes:** `tsp:read:admin`,`tsp:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - tsp:read:admin
          - tsp:read
    post:
      tags:
        - TSP
      summary: Add a user's TSP account
      operationId: Tsp_addUserTspAccount
      security:
        - openapi_oauth:
            - tsp:write:admin
            - tsp:write
          openapi_authorization: []
      description: >-
        Add a user's TSP account.  
           
         


        **Scopes:** `tsp:write:admin`,`tsp:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tsp:write:admin
          - tsp:write
  /users/{userId}/tsp/settings:
    patch:
      tags:
        - TSP
      summary: Set global dial-in URL for a TSP user
      operationId: Tsp_setGlobalDialInUrl
      security:
        - openapi_oauth:
            - tsp:write:admin
            - tsp:write
          openapi_authorization: []
      description: >-
        A global dial-in page can provide a list of global access numbers using
        which audio conferencing can be conducted. By calling this API, you can
        set the url for the global dial-in page of a user whose Zoom account has
        TSP and special TSP with third-party audio conferencing options enabled.
        &lt;p&gt;&lt;/p&gt;



        **Scopes:** `tsp:write:admin`,`tsp:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tsp:write:admin
          - tsp:write
  /users/{userId}/tsp/{tspId}:
    get:
      tags:
        - TSP
      summary: Get a user's TSP account
      operationId: Tsp_getUserTspAccount
      security:
        - openapi_oauth:
            - tsp:read:admin
            - tsp:read
          openapi_authorization: []
      description: >-
        Each user can have a maximum of two TSP accounts. Use this API to
        retrieve details of a specific TSP account enabled for a specific
        user.  
           
         


        **Scopes:** `tsp:read:admin`,`tsp:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tsp:read:admin
          - tsp:read
    delete:
      tags:
        - TSP
      summary: Delete a user's TSP account
      operationId: Tsp_deleteUserTspAccount
      security:
        - openapi_oauth:
            - tsp:write:admin
            - tsp:write
          openapi_authorization: []
      description: >-
        Delete a user's TSP account.  
           
         


        **Scopes:** `tsp:write:admin`,`tsp:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tsp:write:admin
          - tsp:write
    patch:
      tags:
        - TSP
      summary: Update a TSP account
      operationId: Tsp_updateUserTspAccount
      security:
        - openapi_oauth:
            - tsp:write:admin
            - tsp:write
          openapi_authorization: []
      description: >-
        Update a user's TSP account.  
           
         


        **Scopes:** `tsp:write:admin`,`tsp:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tsp:write:admin
          - tsp:write
  /tracking_fields:
    get:
      tags:
        - Tracking Field
      summary: List tracking fields
      operationId: TrackingField_list
      security:
        - openapi_oauth:
            - tracking_fields:read:admin
          openapi_authorization: []
      description: >-
        Use this API to list all the [tracking
        fields](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields)
        on your Zoom account. Tracking fields let you analyze usage by various
        fields within an organization. 


        **Prerequisites:** 

        * A Business, Education, API or higher plan.


        **Scopes:** `tracking_fields:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - tracking_fields:read:admin
    post:
      tags:
        - Tracking Field
      summary: Create a tracking field
      operationId: TrackingField_createField
      security:
        - openapi_oauth:
            - tracking_fields:write:admin
          openapi_authorization: []
      description: >-
        Use this API to create a new [tracking
        field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields).
        Tracking fields let you analyze usage by various fields within an
        organization. When scheduling a meeting, tracking fields will be
        included in the meeting options. 


        **Prerequisites:** 

        * A Business, Education, API or higher plan.


        **Scopes:** `tracking_fields:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tracking_fields:write:admin
  /tracking_fields/{fieldId}:
    get:
      tags:
        - Tracking Field
      summary: Get a tracking field
      operationId: TrackingField_get
      security:
        - openapi_oauth:
            - tracking_fields:read:admin
          openapi_authorization: []
      description: >-
        Use this API to return information about a [tracking
        field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). 


        **Prerequisites:** 

        * A Business, Education, API or higher plan.


        **Scopes:** `tracking_fields:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tracking_fields:read:admin
    delete:
      tags:
        - Tracking Field
      summary: Delete a tracking field
      operationId: TrackingField_deleteField
      security:
        - openapi_oauth:
            - tracking_fields:write:admin
          openapi_authorization: []
      description: >-
        Use this API to delete a [tracking
        field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). 


        **Prerequisites:** 

        * A Business, Education, API or higher plan.


        **Scopes:** `tracking_fields:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tracking_fields:write:admin
    patch:
      tags:
        - Tracking Field
      summary: Update a tracking field
      operationId: TrackingField_update
      security:
        - openapi_oauth:
            - tracking_fields:write:admin
          openapi_authorization: []
      description: >-
        Use this API to update a [tracking
        field](https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields). 


        **Prerequisites:** 

        * A Business, Education, API or higher plan.


        **Scopes:** `tracking_fields:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - tracking_fields:write:admin
  /live_webinars/{webinarId}/chat/messages/{messageId}:
    delete:
      tags:
        - Webinars
      summary: Delete a live webinar message
      operationId: Webinars_deleteMessageById
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Deletes a message in a live webinar based on ID. 


        **Prerequisites:** 

        * Have Zoom enable the DLP for the in-meeting chat feature to use this
        API.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions: []
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
  /past_webinars/{webinarId}/absentees:
    get:
      tags:
        - Webinars
      summary: Get webinar absentees
      operationId: Webinars_listAbsentees
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List absentees of a webinar.  
           
         


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_absentees
          - webinar:read:list_absentees:admin
  /past_webinars/{webinarId}/instances:
    get:
      tags:
        - Webinars
      summary: List past webinar instances
      operationId: Webinars_listPastInstances
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List past webinar instances.  
           
         


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_past_instances
          - webinar:read:list_past_instances:admin
  /past_webinars/{webinarId}/participants:
    get:
      tags:
        - Webinars
      summary: List webinar participants
      operationId: Webinars_listParticipants
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        Retrieve a list of all the participants who attended a webinar hosted in
        the past. 


        **Prerequisites:** 

        * A Pro or higher plan with a webinar add-on.


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_past_participants:admin
          - webinar:read:list_past_participants
  /past_webinars/{webinarId}/polls:
    get:
      tags:
        - Webinars
      summary: List past webinar poll results
      operationId: Webinars_listPollResults
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        The polling feature for webinar lets you create single-choice or
        multiple-choice polling questions for your webinars. This API endpoint
        retrieves the results for webinar polls of a specific webinar.


        **Prerequisites:**  
         
        * [Webinar license](https://zoom.us/webinar)  
         


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_past_polls
          - webinar:read:list_past_polls:admin
  /past_webinars/{webinarId}/qa:
    get:
      tags:
        - Webinars
      summary: List Q&As of a past webinar
      operationId: Webinars_listPastWebinarQa
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List the Q&amp;A of a specific past webinar. 


        The [question &amp; answer
        (Q&amp;A)](https://support.zoom.us/hc/en-us/articles/203686015-Getting-Started-with-Question-Answer)
        feature for webinars lets attendees ask questions during the webinar and
        for the panelists, co-hosts and host to answer their questions. 


        **Prerequisites**  
         
        * [Webinar license](https://zoom.us/webinar)  
         


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:past_qa
          - webinar:read:past_qa:admin
  /users/{userId}/webinar_templates:
    get:
      tags:
        - Webinars
      summary: List webinar templates
      operationId: Webinars_listWebinarTemplates
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        Display a list of a user's [webinar
        templates](https://support.zoom.us/hc/en-us/articles/115001079746-Webinar-Templates).
        For user-level apps, pass [the `me` value](https://developers.zoom.us)
        instead of the `userId` parameter. When you schedule a webinar, save the
        settings for that webinar as a template for scheduling future webinars. 
        To use a template when scheduling a webinar, use the `id` value in this
        API response in the `template_id` field of the [**Create a
        webinar**](https://developers.zoom.us) API. **Prerequisites:** * A Pro
        or a higher account with the [Zoom Webinar
        plan](https://zoom.us/pricing/webinar).


        **Scopes:** `webinar:read:admin`,`webinar:read`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_templates
          - webinar:read:list_templates:admin
    post:
      tags:
        - Webinars
      summary: Create a webinar template
      operationId: Webinars_createWebinarTemplate
      security:
        - openapi_oauth:
            - webinar:write:admin
            - webinar:write
          openapi_authorization: []
      description: >-
        Use this API to create a webinar template from an existing webinar. 




        **Scopes:** `webinar:write:admin`,`webinar:write`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - webinar:write:admin
          - webinar:write
  /users/{userId}/webinars:
    get:
      tags:
        - Webinars
      summary: List webinars
      operationId: Webinars_listWebinars
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List all the webinars scheduled by or on behalf a webinar host. For
        user-level apps, pass [the `me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter. 

         Zoom users with a [webinar plan](https://zoom.us/webinar) have access to creating and managing webinars. Webinars let a host broadcast a Zoom meeting to up to 10,000 attendees. 

        **Note** This API only returns a user's [unexpired
        webinars](https://support.zoom.us/hc/en-us/articles/201362373-Meeting-ID#h_c73f9b08-c1c0-4a1a-b538-e01ebb98e844). 

         **Prerequisites** 
        * A Pro or higher plan with the webinar add-on.


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_webinars
          - webinar:read:list_webinars:admin
    post:
      tags:
        - Webinars
      summary: Create a webinar
      operationId: Webinars_createWebinar
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Schedule a webinar for a user who is a webinar host. For user-level
        apps, pass [the `me`
        value](https://developers.zoom.us/docs/api/rest/using-zoom-apis/#the-me-keyword)
        instead of the `userId` parameter. 

         Webinars allow a host to broadcast a Zoom meeting to up to 10,000 attendees. 

        **Rate limit:**

        Up to a maximum of **100 requests per day**. The rate limit is applied
        to the `userId` of the **webinar host** used to make the request. 


        **Prerequisites:** 

        * A Pro or higher plan with a [Webinar plan](https://zoom.us/webinar)
        add-on.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:write:webinar
          - webinar:write:webinar:admin
  /webinars/{webinarId}:
    get:
      tags:
        - Webinars
      summary: Get a webinar
      operationId: Webinars_getDetails
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        Get details for a scheduled Zoom Webinar.
          
           
         
        **Prerequisites:**

        * Pro or higher plan with a Webinar add-on.


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:webinar
          - webinar:read:webinar:admin
    delete:
      tags:
        - Webinars
      summary: Delete a webinar
      operationId: Webinars_removeWebinar
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Delete a webinar. 



        **Prerequisites:**  
         
        * Pro or higher plan with the webinar add-on.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:delete:webinar
          - webinar:delete:webinar:admin
    patch:
      tags:
        - Webinars
      summary: Update a webinar
      operationId: Webinars_updateScheduledWebinar
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Make updates to a scheduled webinar. 


        **100 requests per day**. The rate limit is applied to the `userId` of
        the **webinar host** used to make the request. 


        **Prerequisites** 

        * A Pro or higher plan with a webinar add-on.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:webinar
          - webinar:update:webinar:admin
  /webinars/{webinarId}/batch_registrants:
    post:
      tags:
        - Webinars
      summary: Perform batch registration
      operationId: Webinars_createBatchRegistrants
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Register up to 30 registrants at once for a scheduled webinar that
        requires
        [registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-webinar-with-registration).   
         

        **Prerequisites:**  
         
        * The webinar host must be a licensed user.

        * The webinar should be type `5`, a scheduled webinar. Other types of
        webinars are not supported by this API.  
           
         


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `HEAVY`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:write:batch_registrants
          - webinar:write:batch_registrants:admin
  /webinars/{webinarId}/branding:
    get:
      tags:
        - Webinars
      summary: Get webinar's session branding
      operationId: Webinars_getSessionBranding
      security:
        - openapi_oauth:
            - webinar:read
            - webinar:read:admin
          openapi_authorization: []
      description: >-
        Use this API to get the webinar's [Session
        Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)
        information. Session branding lets hosts visually customize a webinar by
        setting a webinar wallpaper that displays behind video tiles. Session
        branding also lets hosts set the Virtual Background for and apply name
        tags to hosts, alternative hosts, panelists, interpreters, and
        speakers. 

         **Prerequisites:** 
        * A Pro or higher plan with the Webinar add-on. 

        * The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:read`,`webinar:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar:read
          - webinar:read:admin
  /webinars/{webinarId}/branding/name_tags:
    post:
      tags:
        - Webinars
      summary: Create a webinar's branding name tag
      operationId: Webinars_createBrandingNameTag
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to create a webinar's [Session
        Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)
        name tag. There's a limit of 20 name tags per webinar.
        **Prerequisites:** 

        *  The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
    delete:
      tags:
        - Webinars
      summary: Delete a webinar's branding name tag
      operationId: Webinars_deleteBrandingNameTag
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to delete a webinar's [Session
        Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)
        name tag. 

         **Prerequisites:** 
        * The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
  /webinars/{webinarId}/branding/name_tags/{nameTagId}:
    patch:
      tags:
        - Webinars
      summary: Update a webinar's branding name tag
      operationId: Webinars_updateBrandingNameTag
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to update a webinar's [Session
        Branding](https://support.zoom.us/hc/en-us/articles/4836268732045-Using-Webinar-Session-Branding)
        name tag. **Prerequisites:** 

        *  The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
  /webinars/{webinarId}/branding/virtual_backgrounds:
    post:
      tags:
        - Webinars
      summary: Upload a webinar's branding Virtual Background
      operationId: Webinars_uploadBrandingVirtualBackground
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to upload a webinar's session branding [Virtual
        Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background).
        Hosts and panelists can select and use these Virtual Backgrounds during
        the webinar. Branding Virtual Background files have the following
        restrictions: 

        * A webinar cannot exceed more than 10 Virtual Background files. 

        * You can only upload image files that are in JPG/JPEG, GIF or PNG
        format. 

        * The Virtual Background file size cannot exceed 15 megabytes (MB). 

         **Prerequisites:** 
        *  The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
    delete:
      tags:
        - Webinars
      summary: Delete a webinar's branding Virtual Backgrounds
      operationId: Webinars_deleteBrandingVirtualBackground
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to delete a webinar's session branding [Virtual
        Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). 

         **Prerequisites:** 
        * The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
    patch:
      tags:
        - Webinars
      summary: Set webinar's default branding Virtual Background
      operationId: Webinars_setDefaultBrandingVirtualBackground
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to set a webinar's default session branding [Virtual
        Background](https://support.zoom.us/hc/en-us/articles/210707503-Virtual-Background). 

         **Prerequisites:** 
        * The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
  /webinars/{webinarId}/branding/wallpaper:
    post:
      tags:
        - Webinars
      summary: Upload a webinar's branding wallpaper
      operationId: Webinars_uploadBrandingWallpaper
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to upload a webinar's session branding wallpaper file.
        Webinar branding wallpaper files have the following requirements: 

        * A webinar can only have one wallpaper file. 

        * You can only upload image files that are in JPG/JPEG, GIF, or PNG
        format. 

        * Image files must be 16:9 ratio. The recommended image size is 1920 x
        1080 pixels (px). 

        * The wallpaper file size cannot exceed 15 megabytes (MB). 

         **Prerequisites:** 
        *  The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Medium`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
    delete:
      tags:
        - Webinars
      summary: Delete a webinar's branding wallpaper
      operationId: Webinars_deleteBrandingWallpaper
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to delete a webinar's session branding wallpaper file. 

         **Prerequisites:** 
        * The **Webinar Session Branding** setting enabled.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
  /webinars/{webinarId}/invite_links:
    post:
      tags:
        - Webinars
      summary: Create webinar's invite links
      operationId: Webinars_createInviteLinks
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Create a batch of invitation links for a webinar.


        **Prerequisites:**


        * Business, Education or API Plan with the Webinar add-on.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:write:invite_links
          - webinar:write:invite_links:admin
  /webinars/{webinarId}/jointoken/live_streaming:
    get:
      tags:
        - Webinars
      summary: Get a webinar's join token for live streaming
      operationId: Webinars_joinTokenLiveStreaming
      security:
        - openapi_oauth:
            - webinar_token:read:admin:live_streaming
            - webinar_token:read:live_streaming
          openapi_authorization: []
      description: >-
        Use this API to get a webinar's archive token to allow live streaming.
        The join token allows a recording bot implemented using Zoom meeting SDK
        to connect to a Zoom meeting &quot;hosted by the issuer of the
        token&quot;, and can call the streaming method automatically. It
        supports both regular live streaming, and raw streaming. 

         **Prerequisites:** 
        * A Pro or higher plan with a Webinar Add-on. 

        * The **Allow livestreaming of webinars** user setting enabled in the
        Zoom web portal.


        **Scopes:**
        `webinar_token:read:admin:live_streaming`,`webinar_token:read:live_streaming`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar_token:read:admin:live_streaming
          - webinar_token:read:live_streaming
  /webinars/{webinarId}/jointoken/local_archiving:
    get:
      tags:
        - Webinars
      summary: Get a webinar's archive token for local archiving
      operationId: Webinars_getMeetingArchiveTokenForLocalArchiving
      security:
        - openapi_oauth:
            - webinar_token:read:admin:local_archiving
          openapi_authorization: []
      description: >-
        Use this API to get a webinar's archive token to allow local archiving.
        The archive token allows a meeting SDK app or bot to get archive
        permission to access the webinar's raw audio and video media stream in
        real-time. 

         **Prerequisites:** 
        * A Pro or higher plan with a Webinar Add-on. 

        * The **Archive meetings and webinars** account setting enabled in the
        Zoom web portal.


        **Scopes:** `webinar_token:read:admin:local_archiving`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar_token:read:admin:local_archiving
  /webinars/{webinarId}/jointoken/local_recording:
    get:
      tags:
        - Webinars
      summary: Get a webinar's join token for local recording
      operationId: Webinars_getJoinTokenLocalRecording
      security:
        - openapi_oauth:
            - webinar_token:read:admin:local_recording
            - webinar_token:read:local_recording
          openapi_authorization: []
      description: >-
        Use this API to get a webinar's join token to allow for local recording.
        The join token lets a recording bot implemented using Zoom Meeting SDK
        to connect to a Zoom webinar. The recording bot can then automatically
        start locally recording. This supports both regular and raw local
        recording types. 

         **Prerequisites:** 
        * A Pro or higher plan with a Webinar Add-on. 

        * The **Local recording** user setting enabled in the Zoom web portal.


        **Scopes:**
        `webinar_token:read:admin:local_recording`,`webinar_token:read:local_recording`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar_token:read:admin:local_recording
          - webinar_token:read:local_recording
  /webinars/{webinarId}/livestream:
    get:
      tags:
        - Webinars
      summary: Get live stream details
      operationId: Webinars_getLiveStreamDetails
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        Get a webinar's live stream configuration details, such as Stream URL,
        Stream Key and Page URL.


        Zoom allows users to [live stream a
        webinar](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)
        to a custom platform.

         
        **Prerequisites:**  
         
        * Pro or higher plan with the webinar add-on.  
         
        * Live streaming details must have been
        [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)
        for the webinar.  





        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:livestream
          - webinar:read:livestream:admin
    patch:
      tags:
        - Webinars
      summary: Update a live stream
      operationId: Webinars_updateLiveStream
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Update a webinar's live stream information. 
           
         
        **Prerequisites:**  
         
        * Pro or higher plan with the webinar add-on.  
         
        * Live streaming details must be
        [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)
        for the webinar.  
           
         


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:livestream
          - webinar:update:livestream:admin
  /webinars/{webinarId}/livestream/status:
    patch:
      tags:
        - Webinars
      summary: Update live stream status
      operationId: Webinars_updateLiveStreamStatus
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Let users [live stream a
        webinar](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)
        to a custom platform. Update the status of a webinar's live stream.  
           
         
        **Prerequisites:**  
         
        * Pro or higher plan with a Webinar Add-on.  
         
        * Live streaming details must be
        [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5)
        for the webinar.  
           
         


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:livestream_status
          - webinar:update:livestream_status:admin
  /webinars/{webinarId}/panelists:
    get:
      tags:
        - Webinars
      summary: List panelists
      operationId: Webinars_listPanelists
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List all of a webinar's panelists.  


        Webinar panelists can view and send video, screen share, annotate, and
        do much more compared to webinar attendees. 



        **Prerequisites:**  
         
        * Pro or a higher plan with [Webinar Add-on](https://zoom.us/webinar).  
          

        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_panelists
          - webinar:read:list_panelists:admin
    post:
      tags:
        - Webinars
      summary: Add panelists
      operationId: Webinars_addPanelists
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Panelists in a webinar can view and send video, screen share, annotate,
        and do much more compared to attendees in a webinar.  
         [Add panelists](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_7550d59e-23f5-4703-9e22-e76bded1ed70) to a scheduled webinar.  
           
         
        **Prerequisites:**

        * Pro or a higher plan with the [Webinar
        Add-on](https://zoom.us/webinar).  
          

        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:write:panelist
          - webinar:write:panelist:admin
    delete:
      tags:
        - Webinars
      summary: Remove webinar panelists
      operationId: Webinars_removePanelists
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Remove all the panelists from a webinar.  
         
        **Prerequisites:**  
         
        * Pro or a higher plan with the [webinar
        add-on](https://zoom.us/webinar).  
          

        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:delete:panelist
          - webinar:delete:panelist:admin
  /webinars/{webinarId}/panelists/{panelistId}:
    delete:
      tags:
        - Webinars
      summary: Remove a panelist
      operationId: Webinars_removePanelist
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        [Remove](https://support.zoom.us/hc/en-us/articles/115005657826-Inviting-Panelists-to-a-Webinar#h_de31f237-a91c-4fb2-912b-ecfba8ec5ffb)
        a single panelist from a webinar.  
          Retrieve the `panelistId` by calling **List Panelists API**.  
           
         
        **Prerequisites:**  
         
        * Pro or a higher plan with the [webinar
        add-on](https://zoom.us/webinar).  
          

        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:delete:panelist
          - webinar:delete:panelist:admin
  /webinars/{webinarId}/polls:
    get:
      tags:
        - Webinars
      summary: 'List a webinar''s polls '
      operationId: Webinars_listPolls
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List all the
        [polls](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars)
        of a Webinar.  
           
         


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_polls
          - webinar:read:list_polls:admin
    post:
      tags:
        - Webinars
      summary: Create a webinar's poll
      operationId: Webinars_createPoll
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Create a
        [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars)
        for a webinar.  
           
         


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:write:poll
          - webinar:write:poll:admin
  /webinars/{webinarId}/polls/{pollId}:
    get:
      tags:
        - Webinars
      summary: Get a webinar poll
      operationId: Webinars_getPollDetails
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        Get a webinar's
        [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars)
        details.  
           
         


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:poll
          - webinar:read:poll:admin
    put:
      tags:
        - Webinars
      summary: Update a webinar poll
      operationId: Webinars_updatePoll
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Update a webinar's
        [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).  
           
         


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:poll
          - webinar:update:poll:admin
    delete:
      tags:
        - Webinars
      summary: Delete a webinar poll
      operationId: Webinars_deletePoll
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Delete a webinar's
        [poll](https://support.zoom.us/hc/en-us/articles/203749865-Polling-for-Webinars).  
           
         


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:delete:poll
          - webinar:delete:poll:admin
  /webinars/{webinarId}/registrants:
    get:
      tags:
        - Webinars
      summary: List webinar registrants
      operationId: Webinars_listRegistrants
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List all users that have registered for a given webinar. Zoom users with
        a [webinar plan](https://zoom.us/webinar) have access to creating and
        managing webinars. The webinar functionality lets a host broadcast a
        Zoom meeting to up to 10,000 attendees. Scheduling a [webinar with
        registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)
        requires your registrants to complete a brief form before receiving the
        link to join the webinar.  



        **Prerequisites**

        * Pro or higher plan with a Webinar Add-on.  
         


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_registrants
          - webinar:read:list_registrants:admin
    post:
      tags:
        - Webinars
      summary: Add a webinar registrant
      operationId: Webinars_addRegistrant
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Create and submit a user's registration for a webinar. Zoom users with a
        [Webinar plan](https://zoom.us/webinar) have access to creating and
        managing webinars. Webinars allow hosts to broadcast a Zoom meeting to
        up to 10,000 attendees. Scheduling a [webinar with
        registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)
        requires your registrants to complete a brief form before receiving the
        link to join the webinar. 


        **Prerequisites:** 

        * A Pro or higher plan with the Webinar add-on.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:write:registrant
          - webinar:write:registrant:admin
  /webinars/{webinarId}/registrants/questions:
    get:
      tags:
        - Webinars
      summary: List registration questions
      operationId: Webinars_listRegistrationQuestions
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        List registration questions and fields that are to be answered by users
        while registering for a webinar. 

         Scheduling a [webinar with registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration) requires your registrants to complete a brief form with fields and questions before they can receive the link to join the webinar.  
          
        **Prerequisites:**  
          
        * Pro or higher plan with the webinar add-on.



        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_registration_questions
          - webinar:read:list_registration_questions:admin
    patch:
      tags:
        - Webinars
      summary: Update registration questions
      operationId: Webinars_updateRegistrationQuestions
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Update registration questions and fields of a scheduled webinar for
        users to answer during webinar registration. Scheduling a [webinar with
        registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)
        requires your registrants to complete a brief form with fields and
        questions before they can receive the link to join the webinar.  
           
         
        **Prerequisites:**  
           
        * Pro or higher plan with a Webinar Add-on.

        * Registration option for Webinar should be set as required to use this
        API. 



        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:registration_question
          - webinar:update:registration_question:admin
  /webinars/{webinarId}/registrants/status:
    put:
      tags:
        - Webinars
      summary: Update registrant's status
      operationId: Webinars_updateRegistrantStatus
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Update webinar registrants' registration status. You can approve or deny
        a registrant, or revoke a registrant's approval. 


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:registrant_status
          - webinar:update:registrant_status:admin
  /webinars/{webinarId}/registrants/{registrantId}:
    get:
      tags:
        - Webinars
      summary: Get a webinar registrant
      operationId: Webinars_registrantDetails
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        Zoom users with a [webinar plan](https://zoom.us/webinar) have access to
        creating and managing webinars. The webinar feature lets a host
        broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a
        [webinar with
        registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)
        requires your registrants to complete a brief form before receiving the
        link to join the webinar.  
         Use this API to get details on a specific user who has registered for the webinar.  
           
         
        **Prerequisites:**  
         
        * The account must have a webinar plan.


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:registrant
          - webinar:read:registrant:admin
    delete:
      tags:
        - Webinars
      summary: Delete a webinar registrant
      operationId: Webinars_deleteRegistrant
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Delete a webinar registrant.  
           
         


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:delete:registrant
          - webinar:delete:registrant:admin
  /webinars/{webinarId}/sip_dialing:
    post:
      tags:
        - Webinars
      summary: Get a webinar SIP URI with Passcode
      operationId: Webinars_getSipUriWithPasscode
      security:
        - openapi_oauth:
            - webinar:write:admin:sip_dialing
            - webinar:write:sip_dialing
          openapi_authorization: []
      description: >-
        Get a webinar's SIP URI. The URI consists of the webinar ID, an optional
        user-supplied passcode, and participant identifier code. The API return
        data also includes additional fields to indicate whether the API caller
        has a valid Cloud Room Connector subscription, the participant
        identifier code from the URI, and the SIP URI validity period in
        seconds. 


        **Scopes:**
        `webinar:write:admin:sip_dialing`,`webinar:write:sip_dialing`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions: []
        x-macro-scopes:
          - webinar:write:admin:sip_dialing
          - webinar:write:sip_dialing
  /webinars/{webinarId}/status:
    put:
      tags:
        - Webinars
      summary: Update webinar status
      operationId: Webinars_updateStatus
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Update a webinar's status. Use this API to end an ongoing webinar.  
           
         
        **Prerequisites:**  
         
        * The account must hold a valid [Webinar plan](https://zoom.us/webinar).


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:status
          - webinar:update:status:admin
  /webinars/{webinarId}/survey:
    get:
      tags:
        - Webinars
      summary: Get a webinar survey
      operationId: Webinars_getSurvey
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        Return information about a [webinar
        survey](https://support.zoom.us/hc/en-us/articles/360048745651). 

         **Prerequisites:** 
        * A Pro or higher plan with the Webinar add-on. 

        * The [**Webinar
        Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey)
        feature enabled in the host's account.


        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:survey
          - webinar:read:survey:admin
    delete:
      tags:
        - Webinars
      summary: Delete a webinar survey
      operationId: Webinars_deleteSurvey
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Use this API to delete a [webinar
        survey](https://support.zoom.us/hc/en-us/articles/360048745651). 

         **Prerequisites:** 
        * A Pro or higher plan with the Webinar Add-on. 

        * The [**Webinar
        Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey)
        feature enabled in the host's account.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:delete:survey
          - webinar:delete:survey:admin
    patch:
      tags:
        - Webinars
      summary: Update a webinar survey
      operationId: Webinars_updateSurvey
      security:
        - openapi_oauth:
            - webinar:write
            - webinar:write:admin
          openapi_authorization: []
      description: >-
        Update a [webinar
        survey](https://support.zoom.us/hc/en-us/articles/360048745651). 
        **Prerequisites:** * A Pro or higher plan with the Webinar add-on. *
        Enable the [**Webinar
        Survey**](https://support.zoom.us/hc/en-us/articles/360061293191-Enabling-webinar-survey)
        feature in the host's account.


        **Scopes:** `webinar:write`,`webinar:write:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `LIGHT`
      extensions:
        x-permissions:
          - User:Edit
        x-macro-scopes:
          - webinar:write
          - webinar:write:admin
        x-granular-scopes:
          - webinar:update:survey
          - webinar:update:survey:admin
  /webinars/{webinarId}/token:
    get:
      tags:
        - Webinars
      summary: Get webinar's token
      operationId: Webinars_getWebinarToken
      security:
        - openapi_oauth:
            - webinar:read
            - webinar:read:admin
          openapi_authorization: []
      description: >-
        Use this API to get a webinar's [closed caption token (caption
        URL)](https://support.zoom.us/hc/en-us/articles/115002212983-Using-a-third-party-closed-captioning-service).
        This token lets you use a third-party service to stream text to their
        closed captioning software to the Zoom webinar. 


        **Prerequisites:** 

        * A Pro or higher plan with the Webinar add-on. 

        * The **Closed captioning** setting enabled in the Zoom web portal. 

        * 

        * The **Allow use of caption API Token to integrate with 3rd-party
        Closed Captioning services** setting enabled.


        **Scopes:** `webinar:read`,`webinar:read:admin`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `Light`
      extensions:
        x-macro-scopes:
          - webinar:read
          - webinar:read:admin
  /webinars/{webinarId}/tracking_sources:
    get:
      tags:
        - Webinars
      summary: Get webinar tracking sources
      operationId: Webinars_listTrackingSources
      security:
        - openapi_oauth:
            - webinar:read:admin
            - webinar:read
          openapi_authorization: []
      description: >-
        [Webinar Registration Tracking
        Sources](https://support.zoom.us/hc/en-us/articles/360000315683-Webinar-Registration-Source-Tracking)
        allow you to see where your registrants are coming from if you share the
        webinar registration page in multiple platforms. You can then use the
        source tracking to see the number of registrants generated from each
        platform.  
          Use this API to list information on all the tracking sources of a Webinar.  
         
        **Prerequisites**:  
         
        * [Webinar license](https://zoom.us/webinar).

        * Registration must be required for the Webinar.



        **Scopes:** `webinar:read:admin`,`webinar:read`


        **[Rate Limit
        Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):**
        `MEDIUM`
      extensions:
        x-permissions:
          - User:Read
        x-macro-scopes:
          - webinar:read:admin
          - webinar:read
        x-granular-scopes:
          - webinar:read:list_tracking_sources
          - webinar:read:list_tracking_sources:admin
components:
  securitySchemes:
    openapi_authorization:
      type: apiKey
      name: Authorization
      in: header
    openapi_oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /
          tokenUrl: ''
          refreshUrl: ''
          scopes:
            recording:read:admin: recording:read:admin
            recording:write: recording:write
            recording:write:admin: recording:write:admin
            recording:read: recording:read
            phone_recording:read:admin: phone_recording:read:admin
            device:write:admin: device:write:admin
            device:read:admin: device:read:admin
            h323:write:admin: h323:write:admin
            h323:read:admin: h323:read:admin
            meeting:write: meeting:write
            meeting:write:admin: meeting:write:admin
            meeting:master: meeting:master
            meeting_summary:read:admin: meeting_summary:read:admin
            meeting:read: meeting:read
            meeting:read:admin: meeting:read:admin
            meeting_token:read:admin:live_streaming: meeting_token:read:admin:live_streaming
            meeting_token:read:live_streaming: meeting_token:read:live_streaming
            meeting_token:read:admin:local_archiving: meeting_token:read:admin:local_archiving
            meeting_token:read:local_recording: meeting_token:read:local_recording
            meeting_token:read:admin:local_recording: meeting_token:read:admin:local_recording
            meeting_summary:read: meeting_summary:read
            meeting:write:sip_dialing: meeting:write:sip_dialing
            meeting:write:admin:sip_dialing: meeting:write:admin:sip_dialing
            pac:read:admin: pac:read:admin
            pac:read: pac:read
            report:read:admin: report:read:admin
            sip_phone:write:admin: sip_phone:write:admin
            sip_phone:read:admin: sip_phone:read:admin
            tsp:read:admin: tsp:read:admin
            tsp:write:admin: tsp:write:admin
            tsp:read: tsp:read
            tsp:write: tsp:write
            tracking_fields:write:admin: tracking_fields:write:admin
            tracking_fields:read:admin: tracking_fields:read:admin
            webinar:write: webinar:write
            webinar:write:admin: webinar:write:admin
            webinar:read:admin: webinar:read:admin
            webinar:read: webinar:read
            webinar_token:read:admin:live_streaming: webinar_token:read:admin:live_streaming
            webinar_token:read:live_streaming: webinar_token:read:live_streaming
            webinar_token:read:admin:local_archiving: webinar_token:read:admin:local_archiving
            webinar_token:read:admin:local_recording: webinar_token:read:admin:local_recording
            webinar_token:read:local_recording: webinar_token:read:local_recording
            webinar:write:admin:sip_dialing: webinar:write:admin:sip_dialing
            webinar:write:sip_dialing: webinar:write:sip_dialing
          extensions: {}