openapi: 3.0.1
info:
  title: Resistant Documents API
  description: >-

    Resistant Documents provides this API to programmatically interact with its
    document analysis engine.

    Interaction with the API can be divided into three phases:


    1. Creating document submission

    2. Uploading a file for for analysis to an address returned from step 1.

    3. Fetching analysis results


    In the first step, the submission is created by posting to the 
    `/v2/submission` endpoint. The response contains a `submission_id` uniquely
    identifying the document to be analyzed throughout the entire interaction,
    and is used to fetch analysis results later.


    Submission response also returns `upload_url` containing a pre-signed URL.
    This URL should be used to upload the actual document to be analyzed in the
    second step. Please note the document has to be uploaded using HTTP `PUT`
    method with `Content-Type` HTTP header set to `application/octet-stream`.


    In the last step, client should repeatedly poll using the
    `/v2/submission/{submission_id}/fraud` endpoint for analysis results. The
    best practice is to use polling with an [exponential
    back-off](https://en.wikipedia.org/wiki/Exponential_backoff) to reduce load
    on the API.


    # Authentication


    <SecurityDefinitions />
  version: 2.0.0b
  x-konfig-ignore:
    potential-incorrect-type: true
servers:
  - url: https://api.documents.resistant.ai
tags:
  - name: Submission
  - name: Fraud
  - name: Quality
  - name: Decision
  - name: Report
paths:
  /v2/submission:
    post:
      tags:
        - Submission
      summary: Create a submission
      operationId: Submission_analyzeDocument
      security:
        - OAuth2:
            - submissions.write
      description: Create a new submission for a document to be analyzed
  /v2/submission/{submission_id}/characteristics:
    put:
      tags:
        - Submission
      summary: Add submission characteristics
      operationId: Submission_attachCharacteristics
      security:
        - OAuth2:
            - submissions.write
      description: >-
        Attach submission characteristics to the submission. Submission
        characteristics are properties associated with the <i>original</i>
        submission of the document (i.e., from the end user).

        In descriptions of the properties, "user" refers to the person who
        initially submitted the document, "customer" refers to a customer of
        Resistant.ai using this API.


        Calling this endpoint is only allowed if
        `enable_submission_characteristics` is set to `true` when creating the
        submission. When submission characteristics are enabled for the
        submission, submitting then is <b>required</b> (the document will not be
        analyzed without them).
  /v2/submission/{submission_id}/fraud:
    get:
      tags:
        - Fraud
      summary: Fetch fraud result
      operationId: Fraud_getResult
      security:
        - OAuth2:
            - submissions.read
      description: Fetch fraud analysis result
  /v2/submission/{submission_id}/content:
    get:
      tags:
        - Submission
      summary: Fetch content result
      operationId: Submission_getContentResult
      security:
        - OAuth2:
            - submissions.read
      description: Fetch content extraction result
  /v2/submission/{submission_id}/quality:
    get:
      tags:
        - Quality
      summary: Fetch quality result
      operationId: Quality_resultFetch
      security:
        - OAuth2:
            - submissions.read
  /v2/submission/{submission_id}/decision:
    get:
      tags:
        - Decision
      summary: Fetch Adaptive Decision result
      operationId: Decision_getResult
      security:
        - OAuth2:
            - submissions.read
      description: >-
        Fetch Adaptive Decision result. Note that if the response is too large,
        the endpoint may send a 302 FOUND response with a `Location` header
        pointing to result download location. Clients must follow such redirect.
  /v2/submission/{submission_id}/classification:
    get:
      tags:
        - Submission
      summary: Fetch document classification [preview]
      operationId: Submission_getClassificationPreview
      security:
        - OAuth2:
            - submissions.read
      description: Fetch classification of the type of the submitted document
  /v2/submission/{submission_id}/report:
    get:
      tags:
        - Report
      summary: Fetch report [preview]
      operationId: Report_getFraudAnalysis
      security:
        - OAuth2:
            - submissions.read
      description: Fetch fraud analysis report of the submitted document
  /v2/submission/{submission_id}:
    delete:
      tags:
        - Submission
      summary: Delete submission
      operationId: Submission_remove
      security:
        - OAuth2:
            - submissions.write
      description: >-
        Permanently deletes the submission. Can be used, e.g., to remove a
        document before the configured retention period.
  /v2/submission/{submission_id}/feedback:
    put:
      tags:
        - Submission
      summary: Add analysis feedback
      operationId: Submission_addFeedback
      security:
        - OAuth2:
            - submissions.write
      description: >-
        Add custom feedback for the document analysis result. Comment value is
        sanitized.
    get:
      tags:
        - Submission
      summary: Get analysis feedback
      operationId: Submission_getFeedback
      security:
        - OAuth2:
            - submissions.read
      description: >-
        Get custom feedback for the document analysis result previously stored
        with a PUT request to this endpoint.
components:
  securitySchemes:
    OAuth2:
      description: >
        The standard [client
        credentials](https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/#about-the-client-credentials-grant)
        flow:


        1. Client makes a
        [request](https://developer.okta.com/docs/guides/implement-grant-type/clientcreds/main/#request-for-token)
        to authorization server using client credentials

        ```

        BASIC_AUTH=$(echo -n $CLIENT_ID:$CLIENT_SECRET | base64)

        curl --request POST \
          --url 'https://eu.id.resistant.ai/oauth2/aus2un1hkrKhPjir4417/v1/token' \
          --header 'accept: application/json' \
          --header "authorization: Basic $BASIC_AUTH" \
          --header 'content-type: application/x-www-form-urlencoded' \
          --data 'grant_type=client_credentials&scope=submissions.read submissions.write'
        ```

        2. If the credentials are valid, authorization server responds with an
        access token

        ```

        {
          "access_token": "eyJhbG[...]1LQ",
          "token_type": "Bearer",
          "expires_in": 3600,
          "scope": "submissions.read submissions.write"
        }

        ```

        3. Client uses the access token to make subsequent API requests with
        Authorization header

        ```

        Authorization: Bearer eyJhbG[...]1LQ

        ```


        Please note that Token URL is specific for a given environment. Correct
        URL is in the corresponding environment documentation.
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://eu.id.resistant.ai/oauth2/aus2un1hkrKhPjir4417/v1/token
          scopes:
            submissions.read: Read analysis results for a submission
            submissions.write: Create a new submission
