openapi: 3.0.3
info:
  title: PostHog API
  description: ''
  version: null
servers:
  - description: US Cloud
    url: https://app.posthog.com
  - description: EU Cloud
    url: https://eu.posthog.com
tags:
  - name: organizations
  - name: insights
  - name: persons
  - name: batch_exports
  - name: feature_flags
  - name: users
  - name: pipeline_destinations
  - name: pipeline_frontend_apps
  - name: pipeline_import_apps
  - name: pipeline_transformations
  - name: plugins
  - name: dashboards
  - name: session_recordings
  - name: plugin_configs
  - name: projects
  - name: roles
  - name: experiments
  - name: pipeline_destination_configs
  - name: pipeline_frontend_apps_configs
  - name: pipeline_import_apps_configs
  - name: pipeline_transformation_configs
  - name: session_recording_playlists
  - name: cohorts
  - name: notebooks
  - name: domains
  - name: dashboard_templates
  - name: surveys
  - name: actions
  - name: annotations
  - name: early_access_feature
  - name: explicit_members
  - name: property_definitions
  - name: subscriptions
  - name: event_definitions
  - name: groups
  - name: invites
  - name: members
  - name: app_metrics
  - name: exports
  - name: query
  - name: activity_log
  - name: events
  - name: groups_types
  - name: funnel
  - name: trend
paths:
  /api/organizations:
    get:
      tags:
        - organizations
      operationId: Organizations_list
      security:
        - PersonalAPIKeyAuth:
            - organization:read
    post:
      tags:
        - organizations
      operationId: Organizations_createOrganization
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/organizations/{id}:
    get:
      tags:
        - organizations
      operationId: Organizations_getById
      security:
        - PersonalAPIKeyAuth:
            - organization:read
    put:
      tags:
        - organizations
      operationId: Organizations_updateById
      security:
        - PersonalAPIKeyAuth:
            - organization:write
    patch:
      tags:
        - organizations
      operationId: partial_update
      security:
        - PersonalAPIKeyAuth:
            - organization:write
    delete:
      tags:
        - organizations
      operationId: Organizations_removeById
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/organizations/{organization_id}/batch_exports:
    get:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_batchExportsList
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
    post:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_createBatchExport
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
  /api/organizations/{organization_id}/batch_exports/{id}:
    get:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_getBatchExportsById
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
    put:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_updateBatchExport
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
    patch:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_updateBatchExport
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
    delete:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_deleteBatchExport
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
  /api/organizations/{organization_id}/batch_exports/{id}/backfill:
    post:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_triggerBackfill
      description: Trigger a backfill for a BatchExport.
  /api/organizations/{organization_id}/batch_exports/{id}/pause:
    post:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_pauseBatchExport
      description: Pause a BatchExport.
  /api/organizations/{organization_id}/batch_exports/{id}/unpause:
    post:
      tags:
        - organizations
        - batch_exports
      operationId: Organizations_unpauseBatchExport
      description: Unpause a BatchExport.
  /api/organizations/{organization_id}/domains:
    get:
      tags:
        - organizations
        - domains
      operationId: domains_list
      security:
        - PersonalAPIKeyAuth:
            - organization:read
    post:
      tags:
        - organizations
        - domains
      operationId: domains_create
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/organizations/{organization_id}/domains/{id}:
    get:
      tags:
        - organizations
        - domains
      operationId: domains_retrieve
      security:
        - PersonalAPIKeyAuth:
            - organization:read
    put:
      tags:
        - organizations
        - domains
      operationId: domains_update
      security:
        - PersonalAPIKeyAuth:
            - organization:write
    patch:
      tags:
        - organizations
        - domains
      operationId: Organizations_updateDomainById
      security:
        - PersonalAPIKeyAuth:
            - organization:write
    delete:
      tags:
        - organizations
        - domains
      operationId: domains_destroy
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/organizations/{organization_id}/domains/{id}/verify:
    post:
      tags:
        - organizations
        - domains
      operationId: Organizations_verifyDomainPost
  /api/organizations/{organization_id}/invites:
    get:
      tags:
        - organizations
        - invites
      operationId: invites_list
      security:
        - PersonalAPIKeyAuth:
            - organization_member:read
    post:
      tags:
        - organizations
        - invites
      operationId: invites_create
      security:
        - PersonalAPIKeyAuth:
            - organization_member:write
  /api/organizations/{organization_id}/invites/{id}:
    delete:
      tags:
        - organizations
        - invites
      operationId: invites_destroy
      security:
        - PersonalAPIKeyAuth:
            - organization_member:write
  /api/organizations/{organization_id}/invites/bulk:
    post:
      tags:
        - organizations
        - invites
      operationId: Organizations_bulkInviteCreate
      security:
        - PersonalAPIKeyAuth:
            - organization_member:write
  /api/organizations/{organization_id}/members:
    get:
      tags:
        - organizations
        - members
      operationId: members_list
      security:
        - PersonalAPIKeyAuth:
            - organization_member:read
  /api/organizations/{organization_id}/members/{user__uuid}:
    put:
      tags:
        - organizations
        - members
      operationId: members_update
      security:
        - PersonalAPIKeyAuth:
            - organization_member:write
    patch:
      tags:
        - organizations
        - members
      operationId: Organizations_updateMemberByUuid
      security:
        - PersonalAPIKeyAuth:
            - organization_member:write
    delete:
      tags:
        - organizations
        - members
      operationId: members_destroy
      security:
        - PersonalAPIKeyAuth:
            - organization_member:write
  /api/organizations/{organization_id}/pipeline_destinations:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_listPipelineDestinations
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_createPipelineDestinations
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_destinations/{id}:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_getPipelineDestinations
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_pipelineDestinationsUpdate
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_updatePipelineDestination
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_removePipelineDestination
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_destinations/{id}/check_for_updates:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_checkForUpdates
  /api/organizations/{organization_id}/pipeline_destinations/{id}/source:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_getPipelineDestinationsSource
  /api/organizations/{organization_id}/pipeline_destinations/{id}/update_source:
    patch:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_updatePipelineDestinationSourcePartialUpdate
  /api/organizations/{organization_id}/pipeline_destinations/{id}/upgrade:
    post:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_upgradePipelineDestination
  /api/organizations/{organization_id}/pipeline_destinations/activity:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_getPipelineDestinationsActivity
  /api/organizations/{organization_id}/pipeline_destinations/exports_unsubscribe_configs:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_getPipelineDestinationsExportsUnsubscribeConfigs
  /api/organizations/{organization_id}/pipeline_destinations/repository:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_getPipelineDestinationRepository
  /api/organizations/{organization_id}/pipeline_destinations/unused:
    get:
      tags:
        - organizations
        - pipeline_destinations
      operationId: Organizations_getPipelineDestinationsUnused
  /api/organizations/{organization_id}/pipeline_frontend_apps:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_listPipelineFrontendApps
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_createPipelineFrontendApps
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_frontend_apps/{id}:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_getPipelineFrontendAppsById
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_updatePipelineFrontendAppById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_updatePipelineFrontendAppsById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_removePipelineFrontendApps
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_frontend_apps/{id}/check_for_updates:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_pipelineFrontendAppsCheckForUpdatesRetrieve
  /api/organizations/{organization_id}/pipeline_frontend_apps/{id}/source:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_getPipelineFrontendAppsSource
  /api/organizations/{organization_id}/pipeline_frontend_apps/{id}/update_source:
    patch:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_pipelineFrontendAppsUpdateSourcePatch
  /api/organizations/{organization_id}/pipeline_frontend_apps/{id}/upgrade:
    post:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_upgradePipelineFrontendApp
  /api/organizations/{organization_id}/pipeline_frontend_apps/activity:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_getPipelineFrontendAppsActivity
  /api/organizations/{organization_id}/pipeline_frontend_apps/exports_unsubscribe_configs:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_getPipelineFrontendAppExportsUnsubscribeConfigs
  /api/organizations/{organization_id}/pipeline_frontend_apps/repository:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_getPipelineFrontendAppsRepository
  /api/organizations/{organization_id}/pipeline_frontend_apps/unused:
    get:
      tags:
        - organizations
        - pipeline_frontend_apps
      operationId: Organizations_getPipelineFrontendAppsUnused
  /api/organizations/{organization_id}/pipeline_import_apps:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_getPipelineImportApps
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_importPipelineApps
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_import_apps/{id}:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_getPipelineImportApp
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_pipelineImportAppsUpdate
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_updatePipelineImportAppsConfigs
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_deletePipelineImportApp
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_import_apps/{id}/check_for_updates:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_pipelineImportAppsCheckForUpdatesRetrieve
  /api/organizations/{organization_id}/pipeline_import_apps/{id}/source:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_getPipelineImportAppsSource
  /api/organizations/{organization_id}/pipeline_import_apps/{id}/update_source:
    patch:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_updatePipelineImportAppSource
  /api/organizations/{organization_id}/pipeline_import_apps/{id}/upgrade:
    post:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_upgradePipelineImportApp
  /api/organizations/{organization_id}/pipeline_import_apps/activity:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_getPipelineImportAppsActivity
  /api/organizations/{organization_id}/pipeline_import_apps/exports_unsubscribe_configs:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_pipelineImportAppsExportsUnsubscribeConfigsRetrieve
  /api/organizations/{organization_id}/pipeline_import_apps/repository:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_getPipelineImportAppsRepository
  /api/organizations/{organization_id}/pipeline_import_apps/unused:
    get:
      tags:
        - organizations
        - pipeline_import_apps
      operationId: Organizations_getUnusedPipelineImportApps
  /api/organizations/{organization_id}/pipeline_transformations:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_getPipelineTransformations
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_createPipelineTransformation
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_transformations/{id}:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_getPipelineTransformation
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_updatePipelineTransformationById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_updatePipelineTransformationById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_deletePipelineTransformation
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/pipeline_transformations/{id}/check_for_updates:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_getPipelineTransformationCheckForUpdates
  /api/organizations/{organization_id}/pipeline_transformations/{id}/source:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_pipelineTransformationsSourceRetrieve
  /api/organizations/{organization_id}/pipeline_transformations/{id}/update_source:
    patch:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_updatePipelineTransformationSourcePartialUpdate
  /api/organizations/{organization_id}/pipeline_transformations/{id}/upgrade:
    post:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_upgradePipelineTransformation
  /api/organizations/{organization_id}/pipeline_transformations/activity:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_getPipelineTransformationsActivity
  /api/organizations/{organization_id}/pipeline_transformations/exports_unsubscribe_configs:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_getPipelineTransformationExportsUnsubscribeConfigs
  /api/organizations/{organization_id}/pipeline_transformations/repository:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_getPipelineTransformationsRepository
  /api/organizations/{organization_id}/pipeline_transformations/unused:
    get:
      tags:
        - organizations
        - pipeline_transformations
      operationId: Organizations_getUnusedPipelineTransformations
  /api/organizations/{organization_id}/plugins:
    get:
      tags:
        - organizations
        - plugins
      operationId: plugins_list
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - organizations
        - plugins
      operationId: plugins_create
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/plugins/{id}:
    get:
      tags:
        - organizations
        - plugins
      operationId: plugins_retrieve
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - organizations
        - plugins
      operationId: plugins_update
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - organizations
        - plugins
      operationId: Organizations_updatePluginById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - organizations
        - plugins
      operationId: plugins_destroy
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/organizations/{organization_id}/plugins/{id}/check_for_updates:
    get:
      tags:
        - organizations
        - plugins
      operationId: Organizations_pluginsCheckForUpdates
  /api/organizations/{organization_id}/plugins/{id}/source:
    get:
      tags:
        - organizations
        - plugins
      operationId: Organizations_pluginsSourceRetrieve
  /api/organizations/{organization_id}/plugins/{id}/update_source:
    patch:
      tags:
        - organizations
        - plugins
      operationId: Organizations_updatePluginSource
  /api/organizations/{organization_id}/plugins/{id}/upgrade:
    post:
      tags:
        - organizations
        - plugins
      operationId: Organizations_upgradePlugin
  /api/organizations/{organization_id}/plugins/activity:
    get:
      tags:
        - organizations
        - plugins
      operationId: Organizations_getPluginsActivity
  /api/organizations/{organization_id}/plugins/exports_unsubscribe_configs:
    get:
      tags:
        - organizations
        - plugins
      operationId: Organizations_getPluginsExportsUnsubscribeConfigs
  /api/organizations/{organization_id}/plugins/repository:
    get:
      tags:
        - organizations
        - plugins
      operationId: Organizations_getPluginsRepository
  /api/organizations/{organization_id}/plugins/unused:
    get:
      tags:
        - organizations
        - plugins
      operationId: Organizations_getPluginsUnused
  /api/organizations/{organization_id}/projects:
    get:
      tags:
        - organizations
        - projects
      operationId: Organizations_getProjects
      security:
        - PersonalAPIKeyAuth:
            - project:read
      description: Projects for the current organization.
    post:
      tags:
        - organizations
        - projects
      operationId: Organizations_createProject
      security:
        - PersonalAPIKeyAuth:
            - project:write
      description: Projects for the current organization.
  /api/organizations/{organization_id}/projects/{id}:
    get:
      tags:
        - organizations
        - projects
      operationId: Organizations_getProjectsById
      security:
        - PersonalAPIKeyAuth:
            - project:read
      description: Projects for the current organization.
    put:
      tags:
        - organizations
        - projects
      operationId: Organizations_updateProjectById
      security:
        - PersonalAPIKeyAuth:
            - project:write
      description: Projects for the current organization.
    patch:
      tags:
        - organizations
        - projects
      operationId: Organizations_updateProject
      security:
        - PersonalAPIKeyAuth:
            - project:write
      description: Projects for the current organization.
    delete:
      tags:
        - organizations
        - projects
      operationId: Organizations_deleteProjectById
      security:
        - PersonalAPIKeyAuth:
            - project:write
      description: Projects for the current organization.
  /api/organizations/{organization_id}/projects/{id}/activity:
    get:
      tags:
        - organizations
        - projects
      operationId: activity_retrieve
      description: Projects for the current organization.
  /api/organizations/{organization_id}/projects/{id}/is_generating_demo_data:
    get:
      tags:
        - organizations
        - projects
      operationId: Organizations_getIsGeneratingDemoData
      description: Projects for the current organization.
  /api/organizations/{organization_id}/projects/{id}/reset_token:
    patch:
      tags:
        - organizations
        - projects
      operationId: Organizations_projectsResetTokenPartialUpdate
      description: Projects for the current organization.
  /api/organizations/{organization_id}/roles:
    get:
      tags:
        - organizations
        - roles
      operationId: roles_list
      security:
        - PersonalAPIKeyAuth:
            - organization:read
    post:
      tags:
        - organizations
        - roles
      operationId: roles_create
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/organizations/{organization_id}/roles/{id}:
    get:
      tags:
        - organizations
        - roles
      operationId: roles_retrieve
      security:
        - PersonalAPIKeyAuth:
            - organization:read
    put:
      tags:
        - organizations
        - roles
      operationId: roles_update
      security:
        - PersonalAPIKeyAuth:
            - organization:write
    patch:
      tags:
        - organizations
        - roles
      operationId: Organizations_updateRoleById
      security:
        - PersonalAPIKeyAuth:
            - organization:write
    delete:
      tags:
        - organizations
        - roles
      operationId: roles_destroy
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/organizations/{organization_id}/roles/{role_id}/role_memberships:
    get:
      tags:
        - organizations
        - roles
      operationId: Organizations_listRoleMemberships
      security:
        - PersonalAPIKeyAuth:
            - organization:read
    post:
      tags:
        - organizations
        - roles
      operationId: Organizations_createRoleMemberships
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/organizations/{organization_id}/roles/{role_id}/role_memberships/{id}:
    delete:
      tags:
        - organizations
        - roles
      operationId: Organizations_removeRoleMembership
      security:
        - PersonalAPIKeyAuth:
            - organization:write
  /api/projects/{project_id}/actions:
    get:
      tags:
        - actions
      operationId: actions_list
      security:
        - PersonalAPIKeyAuth:
            - action:read
    post:
      tags:
        - actions
      operationId: actions_create
      security:
        - PersonalAPIKeyAuth:
            - action:write
  /api/projects/{project_id}/actions/{id}:
    get:
      tags:
        - actions
      operationId: actions_retrieve
      security:
        - PersonalAPIKeyAuth:
            - action:read
    put:
      tags:
        - actions
      operationId: actions_update
      security:
        - PersonalAPIKeyAuth:
            - action:write
    patch:
      tags:
        - actions
      operationId: Actions_updateById
      security:
        - PersonalAPIKeyAuth:
            - action:write
    delete:
      tags:
        - actions
      operationId: actions_destroy
      security:
        - PersonalAPIKeyAuth:
            - action:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/activity_log:
    get:
      tags:
        - activity_log
      operationId: Activitylog_getActivityLog
      security:
        - PersonalAPIKeyAuth:
            - activity_log:read
  /api/projects/{project_id}/activity_log/bookmark_activity_notification:
    post:
      tags:
        - activity_log
      operationId: Activitylog_createBookmarkActivityNotification
  /api/projects/{project_id}/activity_log/important_changes:
    get:
      tags:
        - activity_log
      operationId: Activitylog_getImportantChanges
  /api/projects/{project_id}/annotations:
    get:
      tags:
        - annotations
      operationId: annotations_list
      security:
        - PersonalAPIKeyAuth:
            - annotation:read
      description: >-
        Create, Read, Update and Delete annotations. [See
        docs](https://posthog.com/docs/user-guides/annotations) for more
        information on annotations.
    post:
      tags:
        - annotations
      operationId: annotations_create
      security:
        - PersonalAPIKeyAuth:
            - annotation:write
      description: >-
        Create, Read, Update and Delete annotations. [See
        docs](https://posthog.com/docs/user-guides/annotations) for more
        information on annotations.
  /api/projects/{project_id}/annotations/{id}:
    get:
      tags:
        - annotations
      operationId: annotations_retrieve
      security:
        - PersonalAPIKeyAuth:
            - annotation:read
      description: >-
        Create, Read, Update and Delete annotations. [See
        docs](https://posthog.com/docs/user-guides/annotations) for more
        information on annotations.
    put:
      tags:
        - annotations
      operationId: annotations_update
      security:
        - PersonalAPIKeyAuth:
            - annotation:write
      description: >-
        Create, Read, Update and Delete annotations. [See
        docs](https://posthog.com/docs/user-guides/annotations) for more
        information on annotations.
    patch:
      tags:
        - annotations
      operationId: Annotations_crudById
      security:
        - PersonalAPIKeyAuth:
            - annotation:write
      description: >-
        Create, Read, Update and Delete annotations. [See
        docs](https://posthog.com/docs/user-guides/annotations) for more
        information on annotations.
    delete:
      tags:
        - annotations
      operationId: annotations_destroy
      security:
        - PersonalAPIKeyAuth:
            - annotation:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/app_metrics/{id}:
    get:
      tags:
        - app_metrics
      operationId: Appmetrics_getAppMetricsById
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
  /api/projects/{project_id}/app_metrics/{id}/error_details:
    get:
      tags:
        - app_metrics
      operationId: Appmetrics_getErrorDetails
  /api/projects/{project_id}/app_metrics/{plugin_config_id}/historical_exports:
    get:
      tags:
        - app_metrics
      operationId: Appmetrics_getHistoricalExports
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
  /api/projects/{project_id}/app_metrics/{plugin_config_id}/historical_exports/{id}:
    get:
      tags:
        - app_metrics
      operationId: Appmetrics_getHistoricalExportsById
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
  /api/projects/{project_id}/batch_exports:
    get:
      tags:
        - batch_exports
      operationId: Batchexports_getMultipleRuns
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
    post:
      tags:
        - batch_exports
      operationId: Batchexports_createNewRun
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
  /api/projects/{project_id}/batch_exports/{batch_export_id}/logs:
    get:
      tags:
        - batch_exports
      operationId: Batchexports_getLogs
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
  /api/projects/{project_id}/batch_exports/{batch_export_id}/runs:
    get:
      tags:
        - batch_exports
      operationId: Batchexports_getRuns
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
      description: Get all BatchExportRuns for a BatchExport.
  /api/projects/{project_id}/batch_exports/{batch_export_id}/runs/{id}:
    get:
      tags:
        - batch_exports
      operationId: Batchexports_getRunsRetrieve
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
  /api/projects/{project_id}/batch_exports/{batch_export_id}/runs/{run_id}/logs:
    get:
      tags:
        - batch_exports
      operationId: Batchexports_getLogs
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
  /api/projects/{project_id}/batch_exports/{id}:
    get:
      tags:
        - batch_exports
      operationId: Batchexports_getMultipleRuns
      security:
        - PersonalAPIKeyAuth:
            - batch_export:read
    put:
      tags:
        - batch_exports
      operationId: Batchexports_updateByIdPatch
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
    patch:
      tags:
        - batch_exports
      operationId: Batchexports_updateByIdPatch
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
    delete:
      tags:
        - batch_exports
      operationId: Batchexports_deleteById
      security:
        - PersonalAPIKeyAuth:
            - batch_export:write
  /api/projects/{project_id}/batch_exports/{id}/backfill:
    post:
      tags:
        - batch_exports
      operationId: Batchexports_triggerBackfill
      description: Trigger a backfill for a BatchExport.
  /api/projects/{project_id}/batch_exports/{id}/pause:
    post:
      tags:
        - batch_exports
      operationId: Batchexports_pauseAction
      description: Pause a BatchExport.
  /api/projects/{project_id}/batch_exports/{id}/unpause:
    post:
      tags:
        - batch_exports
      operationId: Batchexports_unpauseAction
      description: Unpause a BatchExport.
  /api/projects/{project_id}/cohorts:
    get:
      tags:
        - cohorts
      operationId: cohorts_list
      security:
        - PersonalAPIKeyAuth:
            - cohort:read
    post:
      tags:
        - cohorts
      operationId: cohorts_create
      security:
        - PersonalAPIKeyAuth:
            - cohort:write
  /api/projects/{project_id}/cohorts/{id}:
    get:
      tags:
        - cohorts
      operationId: cohorts_retrieve
      security:
        - PersonalAPIKeyAuth:
            - cohort:read
    put:
      tags:
        - cohorts
      operationId: cohorts_update
      security:
        - PersonalAPIKeyAuth:
            - cohort:write
    patch:
      tags:
        - cohorts
      operationId: Cohorts_updateDetails
      security:
        - PersonalAPIKeyAuth:
            - cohort:write
    delete:
      tags:
        - cohorts
      operationId: cohorts_destroy
      security:
        - PersonalAPIKeyAuth:
            - cohort:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/cohorts/{id}/duplicate_as_static_cohort:
    get:
      tags:
        - cohorts
      operationId: Cohorts_duplicateAsStaticCohortRetrieve
  /api/projects/{project_id}/cohorts/{id}/persons:
    get:
      tags:
        - cohorts
      operationId: Cohorts_listPersons
      security:
        - PersonalAPIKeyAuth:
            - cohort:read
            - person:read
  /api/projects/{project_id}/dashboard_templates:
    get:
      tags:
        - dashboard_templates
      operationId: Dashboardtemplates_getList
      security:
        - PersonalAPIKeyAuth:
            - dashboard_template:read
    post:
      tags:
        - dashboard_templates
      operationId: Dashboardtemplates_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - dashboard_template:write
  /api/projects/{project_id}/dashboard_templates/{id}:
    get:
      tags:
        - dashboard_templates
      operationId: Dashboardtemplates_getById
      security:
        - PersonalAPIKeyAuth:
            - dashboard_template:read
    put:
      tags:
        - dashboard_templates
      operationId: Dashboardtemplates_updateById
      security:
        - PersonalAPIKeyAuth:
            - dashboard_template:write
    patch:
      tags:
        - dashboard_templates
      operationId: Dashboardtemplates_updateByIdPatch
      security:
        - PersonalAPIKeyAuth:
            - dashboard_template:write
    delete:
      tags:
        - dashboard_templates
      operationId: Dashboardtemplates_removeById
      security:
        - PersonalAPIKeyAuth:
            - dashboard_template:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/dashboard_templates/json_schema:
    get:
      tags:
        - dashboard_templates
      operationId: Dashboardtemplates_getJsonSchema
  /api/projects/{project_id}/dashboards:
    get:
      tags:
        - dashboards
      operationId: dashboards_list
      security:
        - PersonalAPIKeyAuth:
            - dashboard:read
    post:
      tags:
        - dashboards
      operationId: dashboards_create
      security:
        - PersonalAPIKeyAuth:
            - dashboard:write
  /api/projects/{project_id}/dashboards/{dashboard_id}/collaborators:
    get:
      tags:
        - dashboards
      operationId: Dashboards_listCollaborators
      security:
        - PersonalAPIKeyAuth:
            - dashboard:read
    post:
      tags:
        - dashboards
      operationId: Dashboards_addCollaborator
      security:
        - PersonalAPIKeyAuth:
            - dashboard:write
  /api/projects/{project_id}/dashboards/{dashboard_id}/collaborators/{user__uuid}:
    delete:
      tags:
        - dashboards
      operationId: Dashboards_deleteCollaboratorByUuid
      security:
        - PersonalAPIKeyAuth:
            - dashboard:write
  /api/projects/{project_id}/dashboards/{dashboard_id}/sharing:
    get:
      tags:
        - dashboards
      operationId: Dashboards_sharingList
      security:
        - PersonalAPIKeyAuth:
            - sharing_configuration:read
  /api/projects/{project_id}/dashboards/{id}:
    get:
      tags:
        - dashboards
      operationId: dashboards_retrieve
      security:
        - PersonalAPIKeyAuth:
            - dashboard:read
    put:
      tags:
        - dashboards
      operationId: dashboards_update
      security:
        - PersonalAPIKeyAuth:
            - dashboard:write
    patch:
      tags:
        - dashboards
      operationId: Dashboards_updateById
      security:
        - PersonalAPIKeyAuth:
            - dashboard:write
    delete:
      tags:
        - dashboards
      operationId: dashboards_destroy
      security:
        - PersonalAPIKeyAuth:
            - dashboard:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/dashboards/{id}/move_tile:
    patch:
      tags:
        - dashboards
      operationId: Dashboards_moveTilePatch
  /api/projects/{project_id}/dashboards/create_from_template_json:
    post:
      tags:
        - dashboards
      operationId: Dashboards_createFromTemplateJsonPost
  /api/projects/{project_id}/early_access_feature:
    get:
      tags:
        - early_access_feature
      operationId: Earlyaccessfeature_getEarlyAccessFeature
      security:
        - PersonalAPIKeyAuth:
            - early_access_feature:read
    post:
      tags:
        - early_access_feature
      operationId: Earlyaccessfeature_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - early_access_feature:write
  /api/projects/{project_id}/early_access_feature/{id}:
    get:
      tags:
        - early_access_feature
      operationId: Earlyaccessfeature_getData
      security:
        - PersonalAPIKeyAuth:
            - early_access_feature:read
    put:
      tags:
        - early_access_feature
      operationId: Earlyaccessfeature_updateContent
      security:
        - PersonalAPIKeyAuth:
            - early_access_feature:write
    patch:
      tags:
        - early_access_feature
      operationId: Earlyaccessfeature_updateContent
      security:
        - PersonalAPIKeyAuth:
            - early_access_feature:write
    delete:
      tags:
        - early_access_feature
      operationId: Earlyaccessfeature_deleteById
      security:
        - PersonalAPIKeyAuth:
            - early_access_feature:write
  /api/projects/{project_id}/event_definitions:
    get:
      tags:
        - event_definitions
      operationId: Eventdefinitions_list
      security:
        - PersonalAPIKeyAuth:
            - event_definition:read
  /api/projects/{project_id}/event_definitions/{id}:
    get:
      tags:
        - event_definitions
      operationId: Eventdefinitions_getById
      security:
        - PersonalAPIKeyAuth:
            - event_definition:read
    put:
      tags:
        - event_definitions
      operationId: Eventdefinitions_updateById
      security:
        - PersonalAPIKeyAuth:
            - event_definition:write
    patch:
      tags:
        - event_definitions
      operationId: Eventdefinitions_updateByIdPatch
      security:
        - PersonalAPIKeyAuth:
            - event_definition:write
    delete:
      tags:
        - event_definitions
      operationId: Eventdefinitions_deleteById
      security:
        - PersonalAPIKeyAuth:
            - event_definition:write
  /api/projects/{project_id}/events:
    get:
      tags:
        - events
      operationId: events_list
      security:
        - PersonalAPIKeyAuth:
            - query:read
      description: |2-

                This endpoint allows you to list and filter events.
                It is effectively deprecated and is kept only for backwards compatibility.
                If you ever ask about it you will be advised to not use it...
                If you want to ad-hoc list or aggregate events, use the Query endpoint instead.
                If you want to export all events or many pages of events you should use our CDP/Batch Exports products instead.
                
  /api/projects/{project_id}/events/{id}:
    get:
      tags:
        - events
      operationId: events_retrieve
      security:
        - PersonalAPIKeyAuth:
            - query:read
  /api/projects/{project_id}/events/values:
    get:
      tags:
        - events
      operationId: Events_getValues
  /api/projects/{project_id}/experiments:
    get:
      tags:
        - experiments
      operationId: experiments_list
      security:
        - PersonalAPIKeyAuth:
            - experiment:read
    post:
      tags:
        - experiments
      operationId: experiments_create
      security:
        - PersonalAPIKeyAuth:
            - experiment:write
  /api/projects/{project_id}/experiments/{id}:
    get:
      tags:
        - experiments
      operationId: experiments_retrieve
      security:
        - PersonalAPIKeyAuth:
            - experiment:read
    put:
      tags:
        - experiments
      operationId: experiments_update
      security:
        - PersonalAPIKeyAuth:
            - experiment:write
    patch:
      tags:
        - experiments
      operationId: Experiments_updateExperimentById
      security:
        - PersonalAPIKeyAuth:
            - experiment:write
    delete:
      tags:
        - experiments
      operationId: experiments_destroy
      security:
        - PersonalAPIKeyAuth:
            - experiment:write
  /api/projects/{project_id}/experiments/{id}/results:
    get:
      tags:
        - experiments
      operationId: Experiments_getResults
  /api/projects/{project_id}/experiments/{id}/secondary_results:
    get:
      tags:
        - experiments
      operationId: Experiments_getSecondaryResults
  /api/projects/{project_id}/experiments/requires_flag_implementation:
    get:
      tags:
        - experiments
      operationId: Experiments_getRequiresFlagImplementation
  /api/projects/{project_id}/explicit_members:
    get:
      tags:
        - explicit_members
      operationId: Explicitmembers_getMembers
    post:
      tags:
        - explicit_members
      operationId: Explicitmembers_createOrUpdateMembers
  /api/projects/{project_id}/explicit_members/{parent_membership__user__uuid}:
    get:
      tags:
        - explicit_members
      operationId: Explicitmembers_getMembersByParentMembershipUserUuid
    put:
      tags:
        - explicit_members
      operationId: Explicitmembers_updateParentMembershipUserUuid
    patch:
      tags:
        - explicit_members
      operationId: Explicitmembers_updateParentMembershipUserUuid
    delete:
      tags:
        - explicit_members
      operationId: Explicitmembers_deleteExplicitMembers
  /api/projects/{project_id}/exports:
    get:
      tags:
        - exports
      operationId: exports_list
      security:
        - PersonalAPIKeyAuth:
            - export:read
    post:
      tags:
        - exports
      operationId: exports_create
      security:
        - PersonalAPIKeyAuth:
            - export:write
  /api/projects/{project_id}/exports/{id}:
    get:
      tags:
        - exports
      operationId: exports_retrieve
      security:
        - PersonalAPIKeyAuth:
            - export:read
  /api/projects/{project_id}/exports/{id}/content:
    get:
      tags:
        - exports
      operationId: Exports_contentRetrieve
  /api/projects/{project_id}/feature_flags:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_getFeatureFlags
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:read
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
    post:
      tags:
        - feature_flags
      operationId: Featureflags_createFeatureFlag
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:write
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/{feature_flag_id}/role_access:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_getRoleAccess
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:read
    post:
      tags:
        - feature_flags
      operationId: Featureflags_roleAccessCreate
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:write
  /api/projects/{project_id}/feature_flags/{feature_flag_id}/role_access/{id}:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_getRoleAccessById
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:read
    delete:
      tags:
        - feature_flags
      operationId: Featureflags_deleteRoleAccess
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:write
  /api/projects/{project_id}/feature_flags/{id}:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_readFeatureFlagById
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:read
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
    put:
      tags:
        - feature_flags
      operationId: Featureflags_createOrUpdateFlag
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:write
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
    patch:
      tags:
        - feature_flags
      operationId: Featureflags_updateFeatureFlagById
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:write
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
    delete:
      tags:
        - feature_flags
      operationId: Featureflags_deleteFeatureFlag
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/feature_flags/{id}/activity:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_getFeatureFlagActivity
      security:
        - PersonalAPIKeyAuth:
            - activity_log:read
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/{id}/create_static_cohort_for_flag:
    post:
      tags:
        - feature_flags
      operationId: Featureflags_createStaticCohortForFlag
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/{id}/dashboard:
    post:
      tags:
        - feature_flags
      operationId: Featureflags_createOrUpdateDashboard
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/{id}/enrich_usage_dashboard:
    post:
      tags:
        - feature_flags
      operationId: Featureflags_enrichUsageDashboardCreate
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/activity:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_getFeatureFlagsActivity
      security:
        - PersonalAPIKeyAuth:
            - activity_log:read
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/evaluation_reasons:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_getEvaluationReasons
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/local_evaluation:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_localEvaluationRetrieve
      security:
        - PersonalAPIKeyAuth:
            - feature_flag:read
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/my_flags:
    get:
      tags:
        - feature_flags
      operationId: Featureflags_readMyFlags
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/feature_flags/user_blast_radius:
    post:
      tags:
        - feature_flags
      operationId: Featureflags_createFeatureFlagUserBlastRadius
      description: >-
        Create, read, update and delete feature flags. [See
        docs](https://posthog.com/docs/user-guides/feature-flags) for more
        information on feature flags.


        If you're looking to use feature flags on your application, you can
        either use our JavaScript Library or our dedicated endpoint to check if
        feature flags are enabled for a given user.
  /api/projects/{project_id}/groups:
    get:
      tags:
        - groups
      operationId: groups_list
      security:
        - PersonalAPIKeyAuth:
            - group:read
      description: >-
        List all groups of a specific group type. You must pass
        ?group_type_index= in the URL. To get a list of valid group types, call
        /api/:project_id/groups_types/
  /api/projects/{project_id}/groups/find:
    get:
      tags:
        - groups
      operationId: Groups_getGroupsFind
  /api/projects/{project_id}/groups/property_definitions:
    get:
      tags:
        - groups
      operationId: Groups_getPropertyDefinitions
  /api/projects/{project_id}/groups/property_values:
    get:
      tags:
        - groups
      operationId: Groups_getPropertyValues
  /api/projects/{project_id}/groups/related:
    get:
      tags:
        - groups
      operationId: Groups_getRelatedGroups
  /api/projects/{project_id}/groups_types:
    get:
      tags:
        - groups_types
      operationId: Groupstypes_list
      security:
        - PersonalAPIKeyAuth:
            - group:read
  /api/projects/{project_id}/groups_types/update_metadata:
    patch:
      tags:
        - groups_types
      operationId: Groupstypes_updateMetadataPatch
  /api/projects/{project_id}/insights:
    get:
      tags:
        - insights
      operationId: insights_list
      security:
        - PersonalAPIKeyAuth:
            - insight:read
    post:
      tags:
        - insights
      operationId: insights_create
      security:
        - PersonalAPIKeyAuth:
            - insight:write
  /api/projects/{project_id}/insights/{insight_id}/sharing:
    get:
      tags:
        - insights
      operationId: Insights_getSharing
      security:
        - PersonalAPIKeyAuth:
            - sharing_configuration:read
  /api/projects/{project_id}/insights/{id}:
    get:
      tags:
        - insights
      operationId: insights_retrieve
      security:
        - PersonalAPIKeyAuth:
            - insight:read
    put:
      tags:
        - insights
      operationId: insights_update
      security:
        - PersonalAPIKeyAuth:
            - insight:write
    patch:
      tags:
        - insights
      operationId: Insights_updateInsightPath
      security:
        - PersonalAPIKeyAuth:
            - insight:write
    delete:
      tags:
        - insights
      operationId: insights_destroy
      security:
        - PersonalAPIKeyAuth:
            - insight:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/insights/{id}/activity:
    get:
      tags:
        - insights
      operationId: Insights_getActivityData
      security:
        - PersonalAPIKeyAuth:
            - activity_log:read
  /api/projects/{project_id}/insights/{id}/viewed:
    post:
      tags:
        - insights
      operationId: Insights_markAsViewed
  /api/projects/{project_id}/insights/activity:
    get:
      tags:
        - insights
      operationId: Insights_getActivityData
      security:
        - PersonalAPIKeyAuth:
            - activity_log:read
  /api/projects/{project_id}/insights/cancel:
    post:
      tags:
        - insights
      operationId: Insights_cancelCreate
  /api/projects/{project_id}/insights/funnel:
    get:
      tags:
        - insights
      operationId: Insights_getFunnelSummary
      security:
        - PersonalAPIKeyAuth:
            - insight:read
    post:
      tags:
        - funnel
        - insights
      operationId: Funnel_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - insight:read
  /api/projects/{project_id}/insights/funnel/correlation:
    get:
      tags:
        - insights
      operationId: Insights_funnelCorrelationRetrieve
    post:
      tags:
        - insights
      operationId: Insights_funnelCorrelationCreate
  /api/projects/{project_id}/insights/my_last_viewed:
    get:
      tags:
        - insights
      operationId: Insights_listLastViewed
      description: >-
        Returns basic details about the last 5 insights viewed by this user.
        Most recently viewed first.
  /api/projects/{project_id}/insights/path:
    get:
      tags:
        - insights
      operationId: Insights_getPath
      security:
        - PersonalAPIKeyAuth:
            - insight:read
    post:
      tags:
        - insights
      operationId: Insights_createOrUpdatePath
      security:
        - PersonalAPIKeyAuth:
            - insight:read
  /api/projects/{project_id}/insights/retention:
    get:
      tags:
        - insights
      operationId: Insights_projectRetentionGet
      security:
        - PersonalAPIKeyAuth:
            - insight:read
    post:
      tags:
        - insights
      operationId: Insights_createRetention
      security:
        - PersonalAPIKeyAuth:
            - insight:read
  /api/projects/{project_id}/insights/timing:
    post:
      tags:
        - insights
      operationId: Insights_createTimingInsight
  /api/projects/{project_id}/insights/trend:
    get:
      tags:
        - insights
      operationId: Insights_getTrend
      security:
        - PersonalAPIKeyAuth:
            - insight:read
    post:
      tags:
        - trend
        - insights
      operationId: Trend_createOrUpdatePath
      security:
        - PersonalAPIKeyAuth:
            - insight:read
  /api/projects/{project_id}/notebooks:
    get:
      tags:
        - notebooks
      operationId: notebooks_list
      security:
        - PersonalAPIKeyAuth:
            - notebook:read
      description: >-
        The API for interacting with Notebooks. This feature is in early access
        and the API can have breaking changes without announcement.
    post:
      tags:
        - notebooks
      operationId: notebooks_create
      security:
        - PersonalAPIKeyAuth:
            - notebook:write
      description: >-
        The API for interacting with Notebooks. This feature is in early access
        and the API can have breaking changes without announcement.
  /api/projects/{project_id}/notebooks/{short_id}:
    get:
      tags:
        - notebooks
      operationId: notebooks_retrieve
      security:
        - PersonalAPIKeyAuth:
            - notebook:read
      description: >-
        The API for interacting with Notebooks. This feature is in early access
        and the API can have breaking changes without announcement.
    put:
      tags:
        - notebooks
      operationId: notebooks_update
      security:
        - PersonalAPIKeyAuth:
            - notebook:write
      description: >-
        The API for interacting with Notebooks. This feature is in early access
        and the API can have breaking changes without announcement.
    patch:
      tags:
        - notebooks
      operationId: Notebooks_updateNotebook
      security:
        - PersonalAPIKeyAuth:
            - notebook:write
      description: >-
        The API for interacting with Notebooks. This feature is in early access
        and the API can have breaking changes without announcement.
    delete:
      tags:
        - notebooks
      operationId: notebooks_destroy
      security:
        - PersonalAPIKeyAuth:
            - notebook:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/notebooks/{short_id}/activity:
    get:
      tags:
        - notebooks
      operationId: Notebooks_getActivityList
      security:
        - PersonalAPIKeyAuth:
            - activity_log:read
      description: >-
        The API for interacting with Notebooks. This feature is in early access
        and the API can have breaking changes without announcement.
  /api/projects/{project_id}/notebooks/activity:
    get:
      tags:
        - notebooks
      operationId: Notebooks_getActivityList
      description: >-
        The API for interacting with Notebooks. This feature is in early access
        and the API can have breaking changes without announcement.
  /api/projects/{project_id}/persons:
    get:
      tags:
        - persons
      operationId: persons_list
      security:
        - PersonalAPIKeyAuth:
            - person:read
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/{id}:
    get:
      tags:
        - persons
      operationId: persons_retrieve
      security:
        - PersonalAPIKeyAuth:
            - person:read
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
    put:
      tags:
        - persons
      operationId: persons_update
      security:
        - PersonalAPIKeyAuth:
            - person:write
      description: >-
        Only for setting properties on the person. "properties" from the request
        data will be updated via a "$set" event.

        This means that only the properties listed will be updated, but other
        properties won't be removed nor updated.

        If you would like to remove a property use the `delete_property`
        endpoint.
    patch:
      tags:
        - persons
      operationId: Persons_updatePersonById
      security:
        - PersonalAPIKeyAuth:
            - person:write
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
    delete:
      tags:
        - persons
      operationId: persons_destroy
      security:
        - PersonalAPIKeyAuth:
            - person:write
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/{id}/activity:
    get:
      tags:
        - persons
      operationId: Persons_getActivity
      security:
        - PersonalAPIKeyAuth:
            - activity_log:read
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/{id}/delete_property:
    post:
      tags:
        - persons
      operationId: Persons_deletePropertyApi
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/{id}/properties_timeline:
    get:
      tags:
        - persons
      operationId: Persons_getPropertiesTimeline
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/{id}/split:
    post:
      tags:
        - persons
      operationId: Persons_createOrUpdateSplit
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/{id}/update_property:
    post:
      tags:
        - persons
      operationId: Persons_createOrUpdateProperty
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/activity:
    get:
      tags:
        - persons
      operationId: Persons_getActivity
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/cohorts:
    get:
      tags:
        - persons
      operationId: Persons_listCohorts
      security:
        - PersonalAPIKeyAuth:
            - person:read
            - cohort:read
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/funnel:
    get:
      tags:
        - persons
      operationId: Persons_getFunnel
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
    post:
      tags:
        - persons
      operationId: Persons_createOrUpdateFunnel
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/funnel/correlation:
    get:
      tags:
        - persons
      operationId: Persons_funnelCorrelationRetrieve
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
    post:
      tags:
        - persons
      operationId: Persons_createOrUpdateFunnelCorrelation
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/lifecycle:
    get:
      tags:
        - persons
      operationId: Persons_getLifecyclePath
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/path:
    get:
      tags:
        - persons
      operationId: Persons_getPath
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
    post:
      tags:
        - persons
      operationId: Persons_createOrUpdatePath
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/retention:
    get:
      tags:
        - persons
      operationId: Persons_retentionRetrieve
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/stickiness:
    get:
      tags:
        - persons
      operationId: Persons_getStickiness
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/trends:
    get:
      tags:
        - persons
      operationId: Persons_getTrends
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/persons/values:
    get:
      tags:
        - persons
      operationId: Persons_getValues
      description: >-
        To create or update persons, use a PostHog library of your choice and
        [use an identify call](https://app.posthog.com). This API endpoint is
        only for reading and deleting.
  /api/projects/{project_id}/pipeline_destination_configs:
    get:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_getList
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_destination_configs/{id}:
    get:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_get
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_updateById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_patchById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_deleteById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_destination_configs/{id}/frontend:
    get:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_getFrontend
  /api/projects/{project_id}/pipeline_destination_configs/{id}/job:
    post:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_createJob
  /api/projects/{project_id}/pipeline_destination_configs/rearrange:
    patch:
      tags:
        - pipeline_destination_configs
      operationId: Pipelinedestinationconfigs_rearrangePartialUpdate
  /api/projects/{project_id}/pipeline_frontend_apps_configs:
    get:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_get
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_frontend_apps_configs/{id}:
    get:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_getById
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_updateById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_updateByIdPatch
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_deleteById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_frontend_apps_configs/{id}/frontend:
    get:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_getFrontend
  /api/projects/{project_id}/pipeline_frontend_apps_configs/{id}/job:
    post:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_createJob
  /api/projects/{project_id}/pipeline_frontend_apps_configs/rearrange:
    patch:
      tags:
        - pipeline_frontend_apps_configs
      operationId: Pipelinefrontendappsconfigs_rearrangePartialUpdate
  /api/projects/{project_id}/pipeline_import_apps_configs:
    get:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_getPipelineImportAppsConfigsList
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_postPipelineImportAppsConfigs
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_import_apps_configs/{id}:
    get:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_getById
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_updatePipelineImportAppsConfigsById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_patchById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_deleteById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_import_apps_configs/{id}/frontend:
    get:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_frontendRetrieve
  /api/projects/{project_id}/pipeline_import_apps_configs/{id}/job:
    post:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_createJob
  /api/projects/{project_id}/pipeline_import_apps_configs/rearrange:
    patch:
      tags:
        - pipeline_import_apps_configs
      operationId: Pipelineimportappsconfigs_rearrangePartialUpdate
  /api/projects/{project_id}/pipeline_transformation_configs:
    get:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_list
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_transformation_configs/{id}:
    get:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_getById
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_updateById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_patchById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_deleteById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/pipeline_transformation_configs/{id}/frontend:
    get:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_frontendRetrieve
  /api/projects/{project_id}/pipeline_transformation_configs/{id}/job:
    post:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_createJob
  /api/projects/{project_id}/pipeline_transformation_configs/rearrange:
    patch:
      tags:
        - pipeline_transformation_configs
      operationId: Pipelinetransformationconfigs_rearrangePartialUpdate
  /api/projects/{project_id}/plugin_configs:
    get:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_getByProjectId
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    post:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/plugin_configs/{id}:
    get:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_getByProjectId
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
    put:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_updateByProjectId
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    patch:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_updateByIdPatch
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
    delete:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_deleteById
      security:
        - PersonalAPIKeyAuth:
            - plugin:write
  /api/projects/{project_id}/plugin_configs/{id}/frontend:
    get:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_getFrontend
  /api/projects/{project_id}/plugin_configs/{id}/job:
    post:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_createJob
  /api/projects/{project_id}/plugin_configs/{plugin_config_id}/logs:
    get:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_getLogs
      security:
        - PersonalAPIKeyAuth:
            - plugin:read
  /api/projects/{project_id}/plugin_configs/rearrange:
    patch:
      tags:
        - plugin_configs
      operationId: Pluginconfigs_rearrangePatch
  /api/projects/{project_id}/property_definitions:
    get:
      tags:
        - property_definitions
      operationId: Propertydefinitions_getByProjectIdPropertyDefinitions
      security:
        - PersonalAPIKeyAuth:
            - property_definition:read
  /api/projects/{project_id}/property_definitions/{id}:
    get:
      tags:
        - property_definitions
      operationId: Propertydefinitions_getById
      security:
        - PersonalAPIKeyAuth:
            - property_definition:read
    put:
      tags:
        - property_definitions
      operationId: Propertydefinitions_putByIdCamelCase
      security:
        - PersonalAPIKeyAuth:
            - property_definition:write
    patch:
      tags:
        - property_definitions
      operationId: Propertydefinitions_patchByIdProperty
      security:
        - PersonalAPIKeyAuth:
            - property_definition:write
    delete:
      tags:
        - property_definitions
      operationId: Propertydefinitions_deleteById
      security:
        - PersonalAPIKeyAuth:
            - property_definition:write
  /api/projects/{project_id}/property_definitions/seen_together:
    get:
      tags:
        - property_definitions
      operationId: Propertydefinitions_getEventNamesSeenTogether
      security:
        - PersonalAPIKeyAuth:
            - property_definition:read
      description: >-
        Allows a caller to provide a list of event names and a single property
        name

        Returns a map of the event names to a boolean representing whether that
        property has ever been seen with that event_name
  /api/projects/{project_id}/query:
    post:
      tags:
        - query
      operationId: query_create
      security:
        - PersonalAPIKeyAuth:
            - query:read
  /api/projects/{project_id}/query/{id}:
    get:
      tags:
        - query
      operationId: query_retrieve
      security:
        - PersonalAPIKeyAuth:
            - query:read
      description: (Experimental)
    delete:
      tags:
        - query
      operationId: query_destroy
      security:
        - PersonalAPIKeyAuth:
            - query:read
      description: (Experimental)
  /api/projects/{project_id}/query/draft_sql:
    get:
      tags:
        - query
      operationId: Query_draftSqlRetrieve
  /api/projects/{project_id}/session_recording_playlists:
    get:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_list
      security:
        - PersonalAPIKeyAuth:
            - session_recording_playlist:read
    post:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_createOrUpdate
      security:
        - PersonalAPIKeyAuth:
            - session_recording_playlist:write
  /api/projects/{project_id}/session_recording_playlists/{short_id}:
    get:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_getByShortId
      security:
        - PersonalAPIKeyAuth:
            - session_recording_playlist:read
    put:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_updateRecordingPlaylist
      security:
        - PersonalAPIKeyAuth:
            - session_recording_playlist:write
    patch:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_updateShortId
      security:
        - PersonalAPIKeyAuth:
            - session_recording_playlist:write
    delete:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_deleteById
      security:
        - PersonalAPIKeyAuth:
            - session_recording_playlist:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/session_recording_playlists/{short_id}/recordings:
    get:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_getRecordings
  /api/projects/{project_id}/session_recording_playlists/{short_id}/recordings/{session_recording_id}:
    post:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_createRecording
    delete:
      tags:
        - session_recording_playlists
      operationId: Sessionrecordingplaylists_deleteRecording
  /api/projects/{project_id}/session_recordings:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_getMultiple
      security:
        - PersonalAPIKeyAuth:
            - session_recording:read
  /api/projects/{project_id}/session_recordings/{id}:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_getById
      security:
        - PersonalAPIKeyAuth:
            - session_recording:read
    delete:
      tags:
        - session_recordings
      operationId: Sessionrecordings_deleteById
      security:
        - PersonalAPIKeyAuth:
            - session_recording:write
  /api/projects/{project_id}/session_recordings/{id}/persist:
    post:
      tags:
        - session_recordings
      operationId: Sessionrecordings_persistSessionRecording
  /api/projects/{project_id}/session_recordings/{id}/similar_sessions:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_getSimilarSessions
  /api/projects/{project_id}/session_recordings/{id}/snapshots:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_snapshotsRetrieve
      description: >-
        Snapshots can be loaded from multiple places:

        1. From S3 if the session is older than our ingestion limit. This will
        be multiple files that can be streamed to the client

        2. or from Redis if the session is newer than our ingestion limit.


        Clients need to call this API twice.

        First without a source parameter to get a list of sources supported by
        the given session.

        And then once for each source in the returned list to get the actual
        snapshots.


        NB version 1 of this API has been deprecated and ClickHouse stored
        snapshots are no longer supported.
  /api/projects/{project_id}/session_recordings/{id}/summarize:
    post:
      tags:
        - session_recordings
      operationId: Sessionrecordings_summarizeCreate
  /api/projects/{project_id}/session_recordings/{recording_id}/sharing:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_getSharing
      security:
        - PersonalAPIKeyAuth:
            - sharing_configuration:read
  /api/projects/{project_id}/session_recordings/error_clusters:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_getErrorClusters
  /api/projects/{project_id}/session_recordings/matching_events:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_getSessionRecordingMatchingEvents
      description: |2-

                Gets a list of event ids that match the given session recording filter.
                The filter must include a single session ID.
                And must include at least one event or action filter.
                This API is intended for internal use and might have unannounced breaking changes.
  /api/projects/{project_id}/session_recordings/properties:
    get:
      tags:
        - session_recordings
      operationId: Sessionrecordings_getProperties
  /api/projects/{project_id}/subscriptions:
    get:
      tags:
        - subscriptions
      operationId: subscriptions_list
      security:
        - PersonalAPIKeyAuth:
            - subscription:read
    post:
      tags:
        - subscriptions
      operationId: subscriptions_create
      security:
        - PersonalAPIKeyAuth:
            - subscription:write
  /api/projects/{project_id}/subscriptions/{id}:
    get:
      tags:
        - subscriptions
      operationId: subscriptions_retrieve
      security:
        - PersonalAPIKeyAuth:
            - subscription:read
    put:
      tags:
        - subscriptions
      operationId: subscriptions_update
      security:
        - PersonalAPIKeyAuth:
            - subscription:write
    patch:
      tags:
        - subscriptions
      operationId: Subscriptions_updateById
      security:
        - PersonalAPIKeyAuth:
            - subscription:write
    delete:
      tags:
        - subscriptions
      operationId: subscriptions_destroy
      security:
        - PersonalAPIKeyAuth:
            - subscription:write
      description: >-
        Hard delete of this model is not allowed. Use a patch API call to set
        "deleted" to true
  /api/projects/{project_id}/surveys:
    get:
      tags:
        - surveys
      operationId: surveys_list
      security:
        - PersonalAPIKeyAuth:
            - survey:read
    post:
      tags:
        - surveys
      operationId: surveys_create
      security:
        - PersonalAPIKeyAuth:
            - survey:write
  /api/projects/{project_id}/surveys/{id}:
    get:
      tags:
        - surveys
      operationId: surveys_retrieve
      security:
        - PersonalAPIKeyAuth:
            - survey:read
    put:
      tags:
        - surveys
      operationId: surveys_update
      security:
        - PersonalAPIKeyAuth:
            - survey:write
    patch:
      tags:
        - surveys
      operationId: Surveys_updateSurveyById
      security:
        - PersonalAPIKeyAuth:
            - survey:write
    delete:
      tags:
        - surveys
      operationId: surveys_destroy
      security:
        - PersonalAPIKeyAuth:
            - survey:write
  /api/projects/{project_id}/surveys/responses_count:
    get:
      tags:
        - surveys
      operationId: Surveys_getResponsesCount
  /api/users:
    get:
      tags:
        - users
      operationId: users_list
      security:
        - PersonalAPIKeyAuth:
            - user:read
  /api/users/{uuid}:
    get:
      tags:
        - users
      operationId: users_retrieve
      security:
        - PersonalAPIKeyAuth:
            - user:read
    put:
      tags:
        - users
      operationId: users_update
      security:
        - PersonalAPIKeyAuth:
            - user:write
    patch:
      tags:
        - users
      operationId: Users_patchUuid
      security:
        - PersonalAPIKeyAuth:
            - user:write
  /api/users/{uuid}/request_email_verification:
    post:
      tags:
        - users
      operationId: Users_requestEmailVerificationCreate
      security:
        - {}
  /api/users/{uuid}/scene_personalisation:
    post:
      tags:
        - users
      operationId: Users_createScenePersonalisation
  /api/users/{uuid}/start_2fa_setup:
    get:
      tags:
        - users
      operationId: Users_start2faSetupRetrieve
  /api/users/{uuid}/validate_2fa:
    post:
      tags:
        - users
      operationId: Users_validate2faCreate
  /api/users/{uuid}/verify_email:
    post:
      tags:
        - users
      operationId: Users_verifyEmailCreate
      security:
        - {}
components:
  securitySchemes:
    PersonalAPIKeyAuth:
      type: http
      scheme: bearer
x-tagGroups:
  - tags:
      - actions
      - activity_log
      - annotations
      - app_metrics
      - batch_exports
      - cohorts
      - dashboard_templates
      - dashboards
      - domains
      - early_access_feature
      - event_definitions
      - events
      - experiments
      - explicit_members
      - exports
      - feature_flags
      - funnel
      - groups
      - groups_types
      - insights
      - invites
      - members
      - notebooks
      - organizations
      - persons
      - pipeline_destination_configs
      - pipeline_destinations
      - pipeline_frontend_apps
      - pipeline_frontend_apps_configs
      - pipeline_import_apps
      - pipeline_import_apps_configs
      - pipeline_transformation_configs
      - pipeline_transformations
      - plugin_configs
      - plugins
      - projects
      - property_definitions
      - query
      - roles
      - session_recording_playlists
      - session_recordings
      - subscriptions
      - surveys
      - trend
      - users
    name: All endpoints
